= Lista de Códigos Télex de Destino (CTD) y Códigos de Identificación de Red Télex (CIRT)
:bureau: T
:docnumber: 978-15.IV.2011
:title: LISTA DE CÓDIGOS TÉLEX DE DESTINO (CTD) Y CÓDIGOS DE IDENTIFICACIÓN DE RED TÉLEX (CIRT)
:complements: F.69 (06/1994), F.68 (11/1988)
:published-date: 2011-04-15
:status: draft
:doctype: service-publication
:imagesdir: images
:docfile: document.adoc
:mn-document-class: itu
:language: es
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:



== Notas de la TSB

. Por Circular TSB 80 del 3 de junio de 1994, la TSB ha anunciado la aprobación de la Recomendación UIT-T F.69 (06/1994) de conformidad con la Resolución N.° 1, Sección 8 de la CMNT (Helsinki, 1993). Por consiguiente, la TSB ha preparado una lista de Códigos Télex de Destino (CTD) y Códigos de Identificación de Red Télex (CIRT) correspondientes, atribuidos de conformidad con la Recomendación UIT-T F.68 (11/1988). La lista, basada en el Anexo A a la Recomendación UIT-T F.69 publicada en el Libro Azul (Tomo II – Fascículo II.4 – páginas 142 a 145), refleja los cambios de códigos o nombres de países/zonas geográficas.

. La nueva lista en Anexo al Boletín de Explotación de la UIT N.° 978 del 15 de abril de 2011, sustituye a la anterior. Además, se han añadido a esta lista los códigos de red de telegramas de dos letras mencionados en el párrafo 7.3 de la Recomendación UIT-T F.32 (10/1995), que corresponden a los códigos de identificación de red télex de una letra y países o zonas geográficas para los cuales una información sobre a la cesación de servicio télex ha sido publicada en el Boletín de Explotación de la UIT (N.º).

. Con el fin de mantener actualizada la lista, se ruega a las administraciones/EER que comprueben la exactitud de la información publicada en la misma y que informen a la TSB de cualquier cambio que deba realizarse (Fax: *+41 22 730 5853*, ó E-mail: *tsbtson@itu.int*). Los cambios se publicarán como Enmiendas a la Lista en el siguiente Boletín de Explotación de la UIT.

. Asimismo, la información que contiene este Anexo al Boletín de Explotación de la UIT N.° 978 está disponible en la página web de la UIT link:http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Las denominaciones utilizadas y la presentación del material en esta lista no entrañan por parte de la UIT, ninguna opinión acerca del estatuto jurídico de los países o zonas geográficas o de las autoridades de los mismos.



== Lista de Códigos Télex de Destino (CTD) y Códigos de Identificación de Red Télex (CIRT)

NOTE: No se han atribuido todavía los códigos sin indicación.

[source,yaml]
----
include::T-SP-F.68-2011-MSW-data.yaml[]
----


[appendix]
== Códigos de red de telegramas de dos letras correspondientes a los Códigos de Identificación de Red Télex (CIRT) de una letra

[source,yaml]
----
include::T-SP-F.68-2011-MSW-appendix-1.yaml[]
----


[appendix]
== Países o zonas geográficas para los cuales una información sobre la cesación de servicio de télex ha sido publicada en el Boletín de Explotación de la UIT (N.°)

[source,yaml]
----
include::T-SP-F.68-2011-MSW-appendix-2.yaml[]
----


== ABREVIATURAS

AACR:: All America Cables and Radio, Inc.

AT&T:: American Telephone and Telegraph Company – EasyLink Services

CANTV:: Compañía Anónima Nacional Teléfonos de Venezuela (Gerencia Internacional)

CAPWIRE:: Capitol Wireless, Inc.

CCI:: Consortium Communications International, Inc.

CDT:: Compañía Dominicana de Télex, C. por A.

ENTEL:: Empresa Nacional de Telecomunicaciones

ENTEL-CHILE:: Empresa Nacional de Telecomunicaciones S.A.

ETISALAT:: The Emirates Telecommunications Corporation Ltd

ETPI:: Eastern Telecommunications Philippines, Inc.

GMCR:: Globe-Mackay Cable and Radio Corporation

GRAPHNET:: GRAPHNET, Inc.

GTC:: Government Telecommunications Centre (Malta)

INTEL:: Instituto Nacional de Telecomunicaciones

MCI/WUI:: MCI International/WUI, Inc.

MIRADOR:: Red Agencia Mirador

MMR:: Mobile Marine Radio, Inc.

PHILCOM:: Philippine Global Communications, Inc.

PRCA:: Puerto Rico Communication Authority

PTT:: Philippine Telegraph and Telephone Corp.

RCPI:: Radio Communications of the Philippines, Inc.

TELENET:: Telenet Communications Corporation

TELEX CHILE:: Télex Chile Comunicaciones Telegráficas S.A.

TELEYEMEN:: Yemen International Telecommunications Company (LLC)

TEXCOM:: Sistemas y Equipos de Telecomunicaciones LTDA

TRT/FTC:: TRT/FTC Communication, Inc.

VTRVTR:: Telecomunicaciones S.A.

VTR/CM:: VTR Comunicaciones Mundiales S.A.

WUH:: Western Union of Hawaii, Inc.


== AMENDEMENTS

[%unnumbered,cols="^.^,^.^,^.^",options="header"]
|===
|Enmienda N.° |Boletín de Explotación N.° |País o zona geográfica

|1 | |
|2 | |
|3 | |
|4 | |
|5 | |
|6 | |
|7 | |
|8 | |
|9 | |
|10 | |
|11 | |
|12 | |
|13 | |
|14 | |
|15 | |
|16 | |
|17 | |
|18 | |
|19 | |
|20 | |
|21 | |
|22 | |
|23 | |
|24 | |
|25 | |
|26 | |
|27 | |
|28 | |
|29 | |
|30 | |

|===





