= List of Telex Destination Codes (TDC) and Telex Network Identification Codes (TNIC)
:bureau: T
:docnumber: 978
:title: LIST OF TELEX DESTINATION CODES (TDC) AND TELEX NETWORK IDENTIFICATION CODES (TNIC)
:complements: F.69 (06/1994), F.68 (11/1988)
:published-date: 2011-04-15
:status: draft
:doctype: service-publication
:docfile: document.adoc
:mn-document-class: itu
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:


== Notes from TSB

. By TSB Circular 80 of 3 June 1994, TSB announced the approval of ITU T Recommendation F.69 (06/1994), in accordance with Resolution No. 1, Section 8, of the WTSC (Helsinki, 1993). Consequently, TSB prepared a list of Telex Destination Codes (TDC) and the corresponding Telex Network Identification Codes (TNIC), which are allocated in accordance with ITU-T Recommendation F.68 (11/1988). This list, based on Annex A to ITU-T Recommendation  F.69 as published in the Blue Book (Volume II – Fascicle II.4 – pages 142 to 145), incorporates the changes of codes or designations of names of countries/geographical areas.

. The new list, annexed to ITU Operational Bulletin No. 978 of 15 April 2011, replaces the previous one. In addition, the two-letter telegram network codes, referring to paragraph 7.3 of ITU T Recommendation F.32 (10/1995), corresponding to one-letter telex network identification codes and countries or geographical areas for which information regarding cessation of telex service has been published in ITU Operational Bulletin (No.), are appended to this list.

. In the interests of keeping the list up to date, administrations/ROAs are requested to check the accuracy of the information it contains and to inform TSB of any changes which should be made for its updating (Fax: *+41 22 730 5853*, or E-mail: *tsbtson@itu.int*). Changes will be published in the following ITU Operational Bulletin as Amendments to the list.

. Furthermore, the information contained in this Annex to ITU Operational Bulletin No. 978 is also available on the ITU web page link:http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. The designations employed and the presentation of material in this list do not imply the expression of any opinion whatsoever on the part of ITU concerning the legal status of any country or geographical area, or of its authorities.


== List of Telex Destination Codes (TDC) and Telex Network Identification Codes (TNIC)

[source,yaml]
----
include::T-SP-F.68-2011-MSW-data.yaml[]
----

[appendix]
== Two-letter telegram network codes corresponding to one-letter Telex Network Identification Codes (TNIC)

[source,yaml]
----
include::T-SP-F.68-2011-MSW-appendix-1.yaml[]
----

[appendix]
== Countries or geographical areas for which information regarding cessation of telex service has been published in the ITU Operational Bulletin (No.)

[source,yaml]
----
include::T-SP-F.68-2011-MSW-appendix-2.yaml[]
----


== ABBREVIATIONS

AACR:: All America Cables and Radio, Inc.

AT&T:: American Telephone and Telegraph Company – EasyLink Services

CANTV:: Compañía Anónima Nacional Teléfonos de Venezuela (Gerencia Internacional)

CAPWIRE:: Capitol Wireless, Inc.

CCI:: Consortium Communications International, Inc.

CDT:: Compañía Dominicana de Télex, C. por A.

ENTEL:: Empresa Nacional de Telecomunicaciones

ENTEL-CHILE:: Empresa Nacional de Telecomunicaciones S.A.

ETISALAT:: The Emirates Telecommunications Corporation Ltd

ETPI:: Eastern Telecommunications Philippines, Inc.

GMCR:: Globe-Mackay Cable and Radio Corporation

GRAPHNET:: GRAPHNET, Inc.

GTC:: Government Telecommunications Centre (Malta)

INTEL:: Instituto Nacional de Telecomunicaciones

MCI/WUI:: MCI International/WUI, Inc.

MIRADOR:: Red Agencia Mirador

MMR:: Mobile Marine Radio, Inc.

PHILCOM:: Philippine Global Communications, Inc.

PRCA:: Puerto Rico Communication Authority

PTT:: Philippine Telegraph and Telephone Corp.

RCPI:: Radio Communications of the Philippines, Inc.

TELENET:: Telenet Communications Corporation

TELEX CHILE:: Télex Chile Comunicaciones Telegráficas S.A.

TELEYEMEN:: Yemen International Telecommunications Company (LLC)

TEXCOM:: Sistemas y Equipos de Telecomunicaciones LTDA

TRT/FTC:: TRT/FTC Communication, Inc.

VTR:: VTR Telecomunicaciones S.A.

VTR/CM:: VTR Comunicaciones Mundiales S.A.

WUH:: Western Union of Hawaii, Inc.


== AMENDMENTS

[%unnumbered,cols="^,^,^"]
|===

|Amendment No. |Operational Bulletin No. |Country or geographical area

|1 | |
|2 | |
|3 | |
|4 | |
|5 | |
|6 | |
|7 | |
|8 | |
|9 | |
|10 | |
|11 | |
|12 | |
|13 | |
|14 | |
|15 | |
|16 | |
|17 | |
|18 | |
|19 | |
|20 | |
|21 | |
|22 | |
|23 | |
|24 | |
|25 | |
|26 | |
|27 | |
|28 | |
|29 | |
|30 | |

|===




