= Comunicaciones por intermediario (Call-Back) y procedimientos alternativos de llamada (Resolución 21 Revisión PP-2006)
:bureau: T
:docnumber: 991-1.XI.2011
:title: COMUNICACIONES POR INTERMEDIARO (CALL-BACK) Y PROCEDIMIENTOS ALTERNATIVOS DE LLAMADA
:published-date: 2011-11-01
:status: draft
:doctype: service-publication
:docfile: document.adoc
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:


== Nota de la TSB

. Para mantener la Lista al día, se solicita a las administraciones que notifiquen a la TSB, a la dirección indicada más abajo, cualquier modificación en su país relativa a las comunicaciones por intermediario (Call-Back).

. Sírvase comunicar sus comentarios o modificaciones con respecto a esta Lista al Director de la TSB:
+
--
Unión Internacional de Telecomunicaciones +
Director de la TSB +
Place des Nations +
CH-1211 GINEBRA 20 +
Suiza +
Tel: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: tsbtson@itu.int
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no implican, de parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas, o de sus autoridades.


== Comunicaciones por intermediario (Call-Back) y procedimientos alternativos de llamada (Res. 21 Rev. PP-2006)

=== Nota de la TSB
Países/zonas geográficas para los cuales una información sobre las "Comunicaciones por intermediario (Call Back) y ciertos procedimientos alternativos de llamada no conformes con la reglamentación vigente":

[source,yaml]
----
include::T-SP-PP.RES.21-2011.yaml[]
----

Se solicita a todos los países/zonas geográficas que prohíben las comunicaciones por intermediario (Call-Back) de notificarlo debidamente a la UIT a la siguiente dirección de correo electrónico: link:mailto:tsbtson@itu.int[tsbtson@itu.int]

