= Call-Back and alternative calling procedures (Resolution 21 Revision PP-2006)
:bureau: T
:docnumber: 991
:title: CALL-BACK AND ALTERNATIVE CALLING PROCEDURES
:published-date: 2011-11-01
:status: draft
:doctype: service-publication
:docfile: document.adoc
:language: en
:mn-document-class: itu
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:


== Note from TSB

. In order to keep the list up to date, administrations are, therefore, requested to notify TSB of any modifications concerning Call-Back in their country at the address below.

. Please address any comments or any modifications concerning this List to the Director of TSB:
+
--
Director of TSB +
International Telecommunication Union +
Place des Nations +
CH-1211 GENEVA 20 +
Switzerland +
Tel: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: tsbtson@itu.int
--

. The designations employed and the presentation of material in this List do not imply the expression of any opinion whatsoever on the part of ITU concerning the legal status of any country or geographical area, or of its authorities.


== Call-Back and alternative calling procedures (Res. 21 Rev. PP-2006)

=== Note from TSB
Countries/geographical areas for which "Call-Back and certain alternative calling procedures not in accordance with the relevant regulations" are prohibited in their territory.

[source,yaml]
----
include::T-SP-PP.RES.21-2011.yaml[]
----

All the countries/geographical areas which prohibit the practice of "Call-Back" should inform ITU accordingly by sending e-mail to the following address: link:mailto:tsbtson@itu.int[tsbtson@itu.int]
