= Systèmes de rappel (Call-Back) et procédures d'appel alternatives (Résolution 21 Révision PP-2006)
:bureau: T
:docnumber: 991
:title: SYSTÈMES DE RAPPEL (CALL-BACK) ET PROCÉDURES D'APPEL ALTERNATIVES
:published-date: 2011-11-01
:status: draft
:doctype: service-publication
:docfile: document.adoc
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:


== Note du TSB

. Pour que la Liste puisse être tenue à jour, les Administrations sont priées d'aviser le TSB de toute modification concernant les systèmes de rappel (Call-Back) dans leur pays, en utilisant l'adresse indiquée ci-dessous.

. Veuillez adresser vos commentaires concernant cette Liste au Directeur du TSB:
+
--
Union internationale des télécommunications +
Directeur du TSB +
Place des Nations +
CH-1211 GENÈVE 20 +
Suisse +
Tél: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: tsbtson@itu.int
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques ou de leurs autorités.

== Systèmes de rappel (Call-Back) et procédures d'appel alternatives (Rés. 21 Rév. PP-2006)

=== Note du TSB
Pays/zones géographiques pour lesquels les "Systèmes de rappel (Call Back) et certaines procédures d'appel alternatives non conformes à la réglementation en vigueur" sont interdits sur leur territoire.

[source,yaml]
----
include::T-SP-PP.RES.21-2011.yaml[]
----

Tous les pays/zones géographiques interdisant la pratique du système de rappel devraient aviser dûment l’UIT par
e-mail à l'adresse suivante: link:mailto:tsbtson@itu.int[tsbtson@itu.int]


