= ФОРМА ПОЗЫВНЫХ СИГНАЛОВ, ПРИСВОЕННЫХ КАЖДОЙ АДМИНИСТРАЦИЕЙ СВОИМ ЛЮБИТЕЛЬСКИМ И ЭКСПЕРИМЕНТАЛЬНЫМ СТАНЦИЯМ
:bureau: T
:docnumber: 1154
:series: СТАТУС РАДИОСВЯЗИ МЕЖДУ ЛЮБИТЕЛЬСКИМИ СТАНЦИЯМИ РАЗНЫХ СТРАН
:series1: (в соответствии с положением необязательного характера п. 25.1 Регламента радиосвязи)
:series2: И
:published-date: 2018-08-15
:status: published
:doctype: recommendation-status
:keywords: 
:imagesdir: images
:docfile: T-SP-RR.25.1-2018-MSW-R.adoc
:language: ru
:mn-document-class: itu
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:


[preface]
== Примечание БР

В Циркулярном письме CR/430 от 14 мая 2018 года Бюро радиосвязи предложило администрациям сообщить в Союз о занимаемой ими позиции в отношении положения п. 25.1 Регламента радиосвязи, касающегося радиосвязи между станциями своей любительской службы и любительской спутниковой службы с аналогичными станциями других стран. В этом Циркулярном письме указывается также, что в случае если такая информация от администрации не поступит, то будет считаться, что соответствующая администрация не имеет возражений против такой радиосвязи. 

В том же Циркулярном письме администрациям предлагается далее сообщить Бюро форму позывных сигналов, которые они присвоили своим любительским и экспериментальным станциям. 

Приложение к Оперативному бюллетеню № 1154 от 15 августа 2018 года отменяет и заменяет предыдущее Приложение к Оперативному бюллетеню № 1055 от 1 июля 2014 года. В Приложении учитывается информация, полученная от администраций в отношении положения п. 25.1 Регламента радиосвязи. Что касается формы позывных сигналов, присвоенных любительским и экспериментальным станциям, в отсутствие новой информации, полученной от администрации, воспроизводится информация, хранящаяся в настоящее время в соответствующих реестрах Бюро. 

Настоящее Приложение обновляется с помощью нумерованной серии поправок, публикуемых в Оперативном бюллетене МСЭ. Наряду с этим информация, содержащаяся в настоящем Приложении, размещена также на домашней странице МСЭ по адресу: http://www.itu.int/pub/T-SP/e[http://www.itu.int/pub/T-SP/e], и для пользователей предусмотрен дистанционный доступ. 

Администрациям предлагается проверить правильность опубликованной в настоящем документе информации и сообщить в Союз о любых несоответствиях. Об изменениях к представленной информации следует заявить в Бюро в кратчайшие сроки. 

International Telecommunication Union 

The Director of the Radiocommunication Bureau 

Place des Nations 

1211 GENEVA 20

Switzerland

Тел.: + 41 22 730 5800 

Факс: + 41 22 730 5785 

Эл. почта: brmail@itu.int

NOTE: Ничто в способе представлении информации в настоящем Приложении или в размещении данных не подразумевает одобрения или принятия со стороны МСЭ по вопросам, затрагивающим статус и границы государств и территорий.

== РАДИОСВЯЗЬ МЕЖДУ ЛЮБИТЕЛЬСКИМИ СТАНЦИЯМИ (РР 25.1)

[%unnumbered]
|===
.2+^.^| Администрация страны или географический район 2+^.^| МЕЖДУ СТАНЦИЯМИ РАЗНЫХ СТРАН .2+^.^| Примечания и наложенные ограничения ^.^| Форма позывных сигналов

^.^| Разрешено ^.^| Запрещено ^.^| Страницы

^.^| 1 ^.^| 2 ^.^| 3 ^.^| 4 ^.^| 5

| Афганистан ^.^| x | | {blank}footnote:tab1[Данная администрация не выразила явно своей позиции. В контексте процедуры консультаций предполагается, что данная администрация не имеет возражений против радиосвязи между любительскими станциями своей страны и станциями других стран (см. Циркулярное письмо CR/430 от 14 мая 2018 г.).] | 
| Аляска (Штат) ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Албания (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Алжирская Народная Демократическая Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 11
| Американское Самоа ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Андорра (Княжество) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Ангола (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Ангилья ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Антигуа и Барбуда ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Аргентинская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 11
| Армения (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Аруба ^.^| x | | {blank}footnote:tab1[] ^.^| 11
| Остров Вознесения ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Австралия ^.^| x | | ^.^| 11−12
| Австрия ^.^| x | | {blank}footnote:tab1[] ^.^| 12
| Азербайджан (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Азорские острова ^.^| x | | {blank}footnote:tab1[] ^.^| 35−36
| Содружество Багамских Островов ^.^| x | | {blank}footnote:tab1[] ^.^| 12
| Бахрейн (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 12
| Бангладеш (Народная Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Барбадос ^.^| x | | {blank}footnote:tab1[] ^.^| 13
| Беларусь (Республика) ^.^| x | | ^.^| 13
| Бельгия ^.^| x | | {blank}footnote:tab1[] ^.^| 13–14
| Белиз ^.^| x | | {blank}footnote:tab1[] ^.^| 14
| Бенин (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 14
| Бермудские острова ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Бутан (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 14
| Боливия (Многонациональное Государство) ^.^| x | | {blank}footnote:tab1[] ^.^|  14
| Бонэйр, Синт-Эстатиус и Саба ^.^| х | | {blank}footnote:tab1[] ^.^| 14
| Босния и Герцеговина ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Ботсвана (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 14
| Остров Буве ^.^| x | | {blank}footnote:tab1[] ^.^| 33
| Бразилия (Федеративная Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 15−16
| Британские Виргинские Острова ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Бруней-Даруссалам ^.^| x | | {blank}footnote:tab1[] ^.^| 16
| Болгария (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 16
| Буркина-Фасо ^.^| x | | {blank}footnote:tab1[] ^.^| 16
| Бурунди (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 16
| Кабо-Верде (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 16
| Камбоджа (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Камерун (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 16
| Канада ^.^| x | | {blank}footnote:tab1[] ^.^| 16−17
| Канарские острова ^.^| x | | {blank}footnote:tab1[] ^.^| 39
| Каймановы острова ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Центральноафриканская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 17
| Чад (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 17
| Острова Чагос (Индийский океан) ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Чили ^.^| x | | {blank}footnote:tab1[] ^.^| 17
| Китайская Народная Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Остров Рождества (Индийский океан) ^.^| x | | ^.^| 11−12
| Остров Клиппертон ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Кокосовы (Килинг) острова ^.^| x | | ^.^| 11−12
| Колумбия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 17
| Союз Коморских Островов ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Конго (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Острова Кука ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Коста-Рика ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Кот-д'Ивуар(Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Хорватия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Архипелаг Крозе ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Куба ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Кюрасао ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Кипр (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 18
| Чешская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 19
| Корейская Народно-Демократическая Республика | ^.^| x | {blank}footnote:tab1[] | 
| Демократическая Республика Конго ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Дания ^.^| x | | {blank}footnote:tab1[] ^.^| 19
| Диего-Гарсия ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Джибути (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 19
| Содружество Доминики ^.^| x | | {blank}footnote:tab1[] ^.^| 19
| Доминиканская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 19
| Остров Пасхи ^.^| x | | {blank}footnote:tab1[] ^.^| 17
| Эквадор ^.^| x | | {blank}footnote:tab1[] ^.^| 19−20
| Египет (Арабская Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 20
| Сальвадор (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 20
| Экваториальная Гвинея (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Эритрея | ^.^| x | {blank}footnote:tab1[] | 
| Эстонская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 20
| Эфиопия (Федеративная Демократическая Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Фолклендские (Мальвинские) острова ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Фарерские острова ^.^| x | | {blank}footnote:tab1[] ^.^| 19
| Фиджи (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Финляндия ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Франция ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Французская Полинезия ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Габонская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Гамбия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Грузия ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Германия (Федеративная Республика) ^.^| x | | ^.^| 22
| Гана ^.^| x | | {blank}footnote:tab1[] ^.^| 23
| Гибралтар ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Греция ^.^| x | | {blank}footnote:tab1[] ^.^| 23
| Гренландия ^.^| x | | {blank}footnote:tab1[] ^.^| 19
| Гренада ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Гваделупа (департамент Франции) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Гуам ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Гватемала (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 23
| Гвиана (департамент Франции) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Гвинейская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 23
| Гвинея-Бисау (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 23
| Гайана ^.^| x | | {blank}footnote:tab1[] ^.^| 24
| Гаити (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 24
| Гавайи (Штат) ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Острова Херд и Макдональд ^.^| x | | ^.^| 11−12
| Гондурас (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 24
| Гонконг (Специальный административный район Китая) ^.^| x | | {blank}footnote:tab1[] | 
| Остров Хауленд ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Венгрия ^.^| x | | {blank}footnote:tab1[] ^.^| 24
| Исландия ^.^| x | | {blank}footnote:tab1[] ^.^| 24
| Индия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 24
| Индонезия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 24
| Иран (Исламская Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 25
| Ирак (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 25
| Ирландия ^.^| x | | {blank}footnote:tab1[] ^.^| 25
| Израиль (Государство) ^.^| x | | {blank}footnote:tab1[] ^.^| 25
| Италия ^.^| x | | {blank}footnote:tab1[] ^.^| 25−26
| Ямайка ^.^| x | | {blank}footnote:tab1[] ^.^| 26
| Япония ^.^| x | | {blank}footnote:tab1[] ^.^| 26
| Остров Джарвис ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Остров Джонстон ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Иорданское Хашимитское Королевство ^.^| x | | {blank}footnote:tab1[] ^.^| 26
| Казахстан (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Кения (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 26
| Острова Кергелен ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Кирибати (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 27
| Корея (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 27
| Кувейт (Государство) ^.^| x | | {blank}footnote:tab1[] ^.^| 27
| Кыргызская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 27
| Лаосская Народно-Демократическая Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 27
| Латвийская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 27
| Ливан ^.^| x | | За исключением Израиля ^.^| 27
| Лесото (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 27
| Либерия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Ливия ^.^| x | | {blank}footnote:tab1[] ^.^| 28
| Лихтенштейн (Княжество) ^.^| x | | {blank}footnote:tab1[] ^.^| 28
| Литовская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 28
| Люксембург ^.^| x | | {blank}footnote:tab1[] ^.^| 28
| Макао (Специальный административный район Китая) ^.^| x | | {blank}footnote:tab1[] | 
| Мадагаскар (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 28
| Мадейра ^.^| x | | {blank}footnote:tab1[] ^.^| 35
| Малави ^.^| x | | {blank}footnote:tab1[] ^.^| 28
| Малайзия ^.^| x | | {blank}footnote:tab1[] ^.^| 29
| Мальдивская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 29
| Мали (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Мальта ^.^| x | | {blank}footnote:tab1[] ^.^| 29
| Остров Марион ^.^| x | | {blank}footnote:tab1[] ^.^| 39
| Маршалловы Острова (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Мартиника (департамент Франции) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Мавритания (Исламская Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 29
| Маврикий (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 29
| Майотта (территориальное сообщество). ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Мексика ^.^| x | | {blank}footnote:tab1[] ^.^| 30
| Федеративные Штаты Микронезии ^.^| x | | {blank}footnote:tab1[] ^.^| 30
| Острова Мидуэй ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Молдова (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 30–31
| Монако (Княжество) ^.^| x | | {blank}footnote:tab1[] ^.^| 31
| Монголия ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Черногория ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Монтсеррат ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Марокко (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 31
| Мозамбик (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 31
| Мьянма (Союз) ^.^| x | | {blank}footnote:tab1[] ^.^| 31
| Намибия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 31
| Науру (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 31
| Непал (Федеративная Демократическая Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 31
| Нидерланды (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 31
| Новая Каледония ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Новая Зеландия ^.^| x | | {blank}footnote:tab1[] ^.^| 32
| Никарагуа ^.^| x | | {blank}footnote:tab1[] ^.^| 32
| Нигер (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 33
| Нигерия (Федеративная Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 33
| Ниуэ ^.^| x | | {blank}footnote:tab1[] ^.^| 33
| Остров Норфолк ^.^| x | | ^.^| 11−12
| Содружество Северных Марианских островов ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Норвегия ^.^| x | | {blank}footnote:tab1[] ^.^| 33
| Оман (Султанат) ^.^| x | | {blank}footnote:tab1[] ^.^| 33
| Пакистан (Исламская Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 33
| Палау (Республика) ^.^| х | | {blank}footnote:tab1[] | 
| Остров Пальмира ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Панама (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Папуа-Новая Гвинея ^.^| x | | {blank}footnote:tab1[] ^.^| 34
| Парагвай (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 34
| Перу ^.^| x | | {blank}footnote:tab1[] ^.^| 34
| Филиппины (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 34
| Острова Феникс ^.^| x | | {blank}footnote:tab1[] ^.^| 27
| Остров Питкэрн ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Польша (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 34−35
| Португалия ^.^| x | | {blank}footnote:tab1[] ^.^| 35−36
| Пуэрто-Рико ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Катар (Государство) ^.^| x | | {blank}footnote:tab1[] ^.^| 36
| Реюньон (департамент Франции) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Родригес ^.^| x | | {blank}footnote:tab1[] ^.^| 29
| Румыния ^.^| x | | {blank}footnote:tab1[] ^.^| 36
| Российская Федерация ^.^| x | | {blank}footnote:tab1[] ^.^| 36−37
| Руандийская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 37
| Сен-Бартельми (департамент Франции) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Остров Святой Елены ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Сент-Китс и Невис (Федерация) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Сент-Люсия ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Сен-Мартен (департамент Франции) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Острова Сен-Поль и Амстердам ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Сен-Пьер и Микелон (территориальное сообщество) ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Сент-Винсент и Гренадины ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Самоа (Независимое Государство) ^.^| x | | {blank}footnote:tab1[] ^.^| 37
| Сан-Марино (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 37
| Сан-Томе и Принсипи (Демократическая Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 37
| Саудовская Аравия (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 37
| Сенегал (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 38
| Сербия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Сейшельские Острова (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 38
| Сьерра-Леоне ^.^| x | | {blank}footnote:tab1[] ^.^| 38
| Сингапур (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 38
| Синт-Мартен (голландская часть) ^.^| x | | {blank}footnote:tab1[] ^.^| 38
| Словацкая Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 38
| Словения (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 38
| Соломоновы Острова ^.^| x | | {blank}footnote:tab1[] ^.^| 38
| Сомали (Федеративная Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Южно-Африканская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 39
| Южный Судан (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Испания ^.^| x | | {blank}footnote:tab1[] ^.^| 39
| Шри-Ланка (Демократическая Социалистическая Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 39
| Судан (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Суринам (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 39
| Лебединые острова ^.^| x | | {blank}footnote:tab1[] ^.^| 24
| Свазиленд (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 39
| Швеция ^.^| x | | {blank}footnote:tab1[] ^.^| 39
| Швейцария (Конфедерация) ^.^| x | | {blank}footnote:tab1[] ^.^| 40
| Сирийская Арабская Республика ^.^| x | | За исключением Израиля ^.^| 40
| Таджикистан (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Танзания (Объединенная Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 40
| Таиланд ^.^| x | | {blank}footnote:tab1[] ^.^| 40
| бывшая югославская Республика Македония ^.^| x | | {blank}footnote:tab1[] | 
| Тимор-Лешти (Демократическая Республика) ^.^| x | | {blank}footnote:tab1[] | 
| Тоголезская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Токелау ^.^| x | | {blank}footnote:tab1[] ^.^| 32
| Тонга (Королевство) ^.^| x | | {blank}footnote:tab1[] ^.^| 40
| Тринидад и Тобаго ^.^| x | | {blank}footnote:tab1[] ^.^| 40
| Тристан-да-Кунья ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Тунис ^.^| x | | {blank}footnote:tab1[] ^.^| 41
| Турция ^.^| x | | {blank}footnote:tab1[] ^.^| 41
| Туркменистан ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Острова Теркс и Кайкос ^.^| x | | {blank}footnote:tab1[] ^.^| 42
| Тувалу ^.^| x | | {blank}footnote:tab1[] ^.^| 41
| Уганда (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 41
| Украина ^.^| x | | {blank}footnote:tab1[] ^.^| 41
| Объединенные Арабские Эмираты ^.^| x | | {blank}footnote:tab1[] ^.^| 41
| Соединенное Королевство Великобритании и Северной Ирландии ^.^| x | | {blank}footnote:tab1[] ^.^| 41−42
| Соединенные Штаты Америки ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Американские Виргинские Острова ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Уругвай (Восточная Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Узбекистан (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Вануату (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Государство-город Ватикан ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Венесуэла (Боливарианская Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Вьетнам (Социалистическая Республика) ^.^| x | | За исключением связи между станциями любительской спутниковой службы ^.^| 43
| Остров Уэйк ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Острова Уоллис и Футуна ^.^| x | | {blank}footnote:tab1[] ^.^| 21
| Йеменская Республика ^.^| x | | {blank}footnote:tab1[] ^.^| 
| Замбия (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 43
| Зимбабве (Республика) ^.^| x | | {blank}footnote:tab1[] ^.^| 43

|===


== ФОРМА ПОЗЫВНЫХ СИГНАЛОВ, ПРИСВОЕННЫХ КАЖДОЙ АДМИНИСТРАЦИЕЙ СВОИМ ЛЮБИТЕЛЬСКИМ И ЭКСПЕРИМЕНТАЛЬНЫМ СТАНЦИЯМ

=== Алжирская Народная Демократическая Республика

Любительские станции:: 7X0, 7X2, 7X3, 7X4 и 7X5, за которыми следуют 2 или 3 буквы.

Экспериментальные станции:: 7X6 и 7X7, за которыми следуют 2 или 3 буквы.

=== Аргентинская Республика

Любительские станции:: AY, AZ, LU, LW, за которыми следуют цифра (0–9) и 2 или 3 буквы, первая из которых обозначает провинцию, где расположена станция.

Буквы, обозначающие провинцию:: A−B и C – Федеральная столица 
+
D−E – провинция Буэнос-Айрес 
+
F – провинция Санта-Фе 
+
GA–GOZ – провинция Чако 
+
GP–GZZ – провинция Формоса 
+
H – провинция Кордова 
+
I – провинция Мисьонес 
+
J – провинция Энтре-Риос 
+
K – провинция Тукуман 
+
L – провинция Корриентес 
+
M – провинция Мендоса 
+
N – провинция Сантьяго-дель-Эстеро 
+
O – провинция Сальта 
+
P – провинция Сан-Хуан 
+
Q – провинция Сан-Луис 
+
R – провинция Катамарка 
+
S – провинция Ла-Риоха 
+
T – провинция Жужуй 
+
U – провинция Ла-Пампа 
+
V – провинция Рио-Негро 
+
W – провинция Чубут 
+
XA–XOZ – провинция Санта-Крус 
+
XP–XZZ – провинция Огненная Земля, Антарктика и острова Южной Атлантики
+
Y – Неукен 
+
Z – Антарктика.

NOTE: Новички должны использовать префикс AZ.

=== Аруба

Любительские станции:: P43 или P49, за которыми следует группа не более чем из трех букв.

[NOTE]
====
. Иностранные любители используют позывной сигнал, присвоенный им их администрацией за которым следуют косая черта (/) и далее P4 для обозначения периода длительностью один год.

. Префикс P40 или P41, за которым следует группа не более чем из трех букв, присваивается в рамках особых событий на период, не превышающий одного месяца.
====

=== Австралия

Любительские станции:: VK, AX {blank}footnote:a1[Для случаев особого национального значения или значения уровня штата/местного значения.]
или VI{blank}footnote:a1[], за которыми следуют цифра (обозначающая штат или территорию, где расположена станция) и 2, 3 или 4 буквы.
+
Для позывных сигналов, имеющих суффиксы длиной 3 или 4 буквы, первая буква обозначает категорию лицензии.
+
Любительские станции класса "Высокий" обозначаются позывными сигналами с суффиксом из 2 букв и суффиксами из 3 букв, где первой буквой является A, B, C, D, E, F, G, I, J, K, S, T, U, W, X, Y или Z.
+
Любительские станции класса "Стандартный" обозначаются позывными сигналами с суффиксом из 3 букв, где первой буквой является H, L, M, N, P или V.
+
Любительские станции класса "Базовый" обозначаются позывными сигналами с суффиксом из 4 букв, где первой буквой является F.

Экспериментальные станции:: AX, за которыми следуют цифра (2–9) и 3 буквы, первая из которых обозначает штат или территорию, где расположена станция.

[%unnumbered]
|===
.2+^.^| Станция 10+^.^| Штат или территория
^.^| Австра-лийская столичная терр-итория ^.^| Новый Южный Уэльс ^.^| Виктория ^.^| Квинсленд ^.^| Южная Австралия ^.^| Западная Австралия ^.^| Тасма-ния ^.^| Северная терри-тория ^.^| Внешние терри-тории Австра-лии ^.^| Антаркти-ческая терри-тория 
| Любительская ^.^| 1 ^.^| 2 ^.^| 3 ^.^| 4 ^.^| 5 ^.^| 6 ^.^| 7 ^.^| 8 ^.^| 9 ^.^| –
| Эксперимента-льная ^.^| A ^.^| N ^.^| V ^.^| Q ^.^| S ^.^| W ^.^| T ^.^| D ^.^| – ^.^| –

|===

=== Австрия

Любительские станции:: OE, за которыми следуют цифра (0–9, обозначающая провинцию или район, где расположена станция) и 2 или 3 буквы.

Экспериментальные станции:: OE, за которыми следуют цифра (2–9, обозначающая провинцию, в которой расположена станция) и 2 буквы (QA−QZ).

Цифры, обозначающие провинцию или районы:: 1 – Вена (только любительские станции) 
+
2 – Зальцбург 
+
3 – Вена (только экспериментальные станции) и Нижняя Австрия 
+
4 – Бургенланд 
+
5 – Верхняя Австрия 
+
6 – Штирия 
+
7 – Тироль 
+
8 – Каринтия 
+
9 – Форарльберг 
+
0 – Экстерриториальные 
+
» – На борту морских судов или на борту воздушных судов.

=== Содружество Багамских Островов

Любительские станции и экспериментальные станции:: C62AA−C69ZZ.

=== Бахрейн (Королевство)

Любительские станции:: A9, за которыми следуют цифра (от 0 до 9), далее следуют 2, 3 или 4 знака, последний из которых должен быть буквой.

[%unnumbered]
|===
^.^h| Префикс ^.^h| Цифра ^.^h| Суффикс
^.^| A9 ^.^| 0–9 ^.^| До 4 знаков, последний из которых должен быть буквой.

|===


=== Барбадос

Любительские станции:: 8P6AA−8P6ZZ {blank}footnote:[Для национальных радиолюбителей.] 
+
8P9AA−8P9ZZ {blank}footnote:[Для иностранных радиолюбителей, гостей и владельцев краткосрочной лицензии.].


=== Беларусь (Республика)

Любительские станции:: EU, EV или EW, за которыми следует цифра (1–4, 6–8, указывающая город или область, в которой находится станция) и одна, две или три буквы.

Номера, обозначающие город или область:: 1) Город Минск 
+
2) Минская область 
+
3) Брестская область 
+
4) Гродненская область 
+
5) Витебская область 
+
6) Могилевская область 
+
7) Гомельская область.

Позывной сигнал, содержащий:: 4 знака – класс A (оператор, имеющий лицензию СЕПТ, свидетельство HAREC) 
+
5 знаков – класс A и класс B (оператор, имеющий лицензию СЕПТ, свидетельство HAREC) 
+
6 знаков – класс C (оператор, имеющий лицензию новичка, сертификат ARNEC) 
+
5 знаков – четвертым символом является W, X, Z для станций клубов.

Экспериментальные станции:: EU1A00R−EU8Z99R (кроме EU5A00R–EU5Z99R) – ретрансляторы 
+
EU1A00B−EU8Z99B (кроме EU5A00B–EU5Z99B) – радиомаяки 
+
EU10S−EU89S – спутники 
+
EV0AA−EV9ZZ – для станций, участвующих в соревнованиях по радиосвязи 
+
EV10ISS−EV89ISS – для экспедиций на космические объекты 
+
EV0ANA−EV0ANZ – для станций, работающих в Антарктике 
+
EV0A−EV9999Z – для станций, работающих в дни национальных и международных особых событий.

EU5, EV5, EW5, за которыми следует одна буква, – только для участников международных соревнований по КВ и УКВ радиосвязи (до одного года).

NOTE: Имеющие лицензию иностранные радиолюбители должны использовать EW, за которыми следуют косая черта (/) и их собственный позывной сигнал.

=== Бельгия

[%unnumbered]
|===
2+^.^| Любительские станции
| ON0AA−ON0ZZ +
ON0AAA−ON0ZZZ | Автоматические станции
| ON1AA−ON1ZZ +
ON1AAA−ON1ZZZ | Станции класса 2
| ON2AA−ON2ZZ +
ON2AAA−ON2ZZZ | В настоящее время не используются
| ON3AA−ON3ZZ +
ON3AAA−ON3ZZZ | Станции класса 3
| ON4AA−ON4ZZ +
ON4AAA−ON4ZZZ +
ON5AA−ON5ZZ +
ON5AAA−ON5ZZZ +
ON6AA−ON6ZZ +
ON6AAA−ON6ZZZ +
ON7AA−ON7ZZ +
ON7AAA−ON7ZZZ +
ON8AA−ON8ZZ +
ON8AAA−ON8ZZZ | Станции класса 1
| ON9AAA−ON9AZZ | Станции класса 3 для иностранцев
| ON9BAA−ON9BZZ | Станции класса 2 для иностранцев
| ON9CAA−ON9CZZ | Станции класса 1 для иностранцев
| OP0LE или OP0OL | Станции клубов в Антарктике
| OR3AA−OR3ZZ +
OR3AAA−OR3ZZZ | Станции класса 3 в Антарктике (временное использование)
| OR4AA−OR4ZZ +
OR4AAA−OR4ZZZ | Станции класса 1 в Антарктике (временное использование)
| OR4ISS | На борту ISS
| OO0A−OO9Z +
OP0A−OP9Z +
OQ0A−OQ9Z +
OR0A−OR4Z +
OR6A−OR9Z +
OS0A−OS9Z +
OT0A−OT4Z +
OT6A−OT9Z | Дополнительные позывные сигналы для станций класса 1
| OR5A−OR5Z +
OT5A−OT5Z | Станции для соревнований, в которых используется оборудование высокой мощности

|===

=== Белиз

Любительские станции:: V31AA−V31ZZ  –  лицензия класса 1. 
+
V32AA−V32ZZ  –  лицензия класса 2.

=== Бенин (Республика)

Любительские станции:: TY, за которыми следуют цифра (1–9) и 2 буквы.

=== Бутан (Королевство)

Любительские станции:: A50AA−A50ZZ {blank}footnote:[Для клубов и станций любителей.] 
+
A51AA−A51ZZ {blank}footnote:[Для национальных радиолюбителей.]
+
A52AA−A52ZZ {blank}footnote:[Для гостевых радиолюбителей.].

=== Боливия (Многонациональное Государство)

Любительские станции:: CP1AA−CP9ZZ.

Цифры, обозначающие департамент:: 1 – Ла-Пас 
+
2 – Чукисака 
+
3 – Оруро 
+
4 – Потоси 
+
5 – Кочабамба 
+
6 – Санта-Крус 
+
7 – Тариха 
+
8 – Бени 
+
9 – Пандо.

За позывным могут следовать буквы "M", "MA", "MF", "MM", "S" или "C" в следующих случаях:

M:: для подвижных земных станций 

MA:: для подвижных воздушных станций 

MF:: для подвижных речных станций 

MM:: для подвижных морских станций 

S:: для станций второй категории 

C:: для станций, эксплуатируемых на временной основе.

=== Бонэйр, Синт-Эстатиус и Саба 

Любительские станции:: PJ4AA−PJ4ZZZ –  Бонэйр 
+
PJ5AA−PJ5ZZZ –  С. Эстатиус 
+
PJ6AA−PJ6ZZZ –  Саба.

=== Ботсвана (Республика)

Любительские станции:: A22AA−A22ZZ.


=== Бразилия (Федеративная Республика)

[%unnumbered]
|===
5+^.^| Любительские станции
^.^| Штат 3+^.^| Классы A и B ^.^| Класс C
.2+| Акри | PT8AA−PT8ZZ 2+| PT8AAA−PT8ZZZ | PU8JAA−PU8LZZ
2+| {blank}footnote:b1[Специальные позывные сигналы: в рамках национальных и международных соревнований и экспедиций.] ZZ8HA−ZZ8MZ 2+| ZZ8HAA−ZZ8MZZ
.2+| Алагоас | PP7AA−PP7ZZ 2+| PP7AAA−PP7ZZZ | PU7AAA−PU7DZZ
2+| {blank}footnote:b1[] ZZ7AA−ZZ7ZZ 2+| ZZ7AAA−ZZ7ZZZ
.2+| Амапа | PQ8AA−PQ8ZZ 2+| PQ8AAA−PQ8YZZ | PU8GAA−PU8IZZ
2+| {blank}footnote:b1[] ZV8AA−ZV8ZZ 2+| ZV8AAA−ZV8YZZ
.2+| Амазонас | PP8AA−PP8ZZ 2+| PP8AAA−PP8YZZ | PU8AAA−PU8CZZ
2+| {blank}footnote:b1[] ZZ8AA−ZZ8GZ 2+| ZZ8AAA−ZZ8GZZ
.2+| Баия | PY6AA−PY6ZZ 2+| PY6AAA−PY6YZZ | PU6JAA−PU6YZZ
2+| {blank}footnote:b1[] ZY6AA−ZY6ZZ 2+| ZY6AAA−ZY6YZZ
.2+| Сеара | PT7AA−PT7ZZ 2+| PT7AAA−PT7YZZ | PU7MAA−PU7PZZ
2+| {blank}footnote:b1[] ZV7AA−ZV7ZZ 2+| ZV7AAA−ZV7YZZ
.2+| Федеральный округ | PT2AA−PT2ZZ 2+| PT2AAA−PT2YZZ | PU2AAA−PU2EZZ
2+| {blank}footnote:b1[] ZV2AA−ZV2ZZ 2+| ZV2AAA−ZV2YZZ
.2+| Эспириту-Санту | PPlAA−PPlZZ 2+| PP1AAA−PP1YZZ | PU1AAA−PU1IZZ
2+| {blank}footnote:b1[] ZZ1AA−ZZlZZ 2+| ZZlAAA−ZZlYZZ
.2+| Гояс | PP2AA−PP2ZZ 2+| PP2AAA−PP2YZZ | PU2FAA−PU2HZZ
2+| {blank}footnote:b1[] ZZ2AA−ZZ2ZZ 2+| ZZ2AAA−ZZ2YZZ
.2+| Мараньян | PR8AA−PR8ZZ 2+| PR8AAA−PR8YZZ | PU8MAA−PU8OZZ
2+| {blank}footnote:b1[] ZX8AA−ZX8ZZ 2+| ZX8AAA−ZX8YZZ
.2+| Мату-Гросу | PY9AA−PY9ZZ 2+| PY9AAA−PY9YZZ | PU9OAA−PU9YZZ
2+| {blank}footnote:b1[] ZY9AA−ZY9ZZ 2+| ZY9AAA−ZY9YZZ
.2+| Мату-Гросу-ду-Сул | PT9AA−PT9ZZ 2+| PT9AAA−PT9YZZ | PU9AAA−PU9NZZ
2+| {blank}footnote:b1[] ZV9AA−ZV9ZZ 2+| ZV9AAA−ZV9YZZ
.2+| Минас Жерайс | PY4AA−PY4ZZ 2+| PY4AAA−PY4YZZ | PU4AAA−PU4YZZ
2+| {blank}footnote:b1[] ZY4AA−ZY4ZZ 2+| ZY4AAA−ZY4YZZ
.2+| Пара | PY8AA−PY8ZZ 2+| PY8AAA−PY8YZZ | PU8WAA−PU8YZZ
2+| {blank}footnote:b1[] ZY8AA−ZY8ZZ 2+| ZY8AAA−ZY8YZZ
.2+| Параиба | PR7AA−PR7ZZ 2+| PR7AAA−PR7YZZ | PU7EAA−PU7HZZ
2+| {blank}footnote:b1[] ZX7AA−ZX7ZZ 2+| ZX7AAA−ZX7YZZ
.2+| Парана | PY5AA−PY5ZZ 2+| PY5AAA−PY5YZZ | PU5MAA−PU5YZZ
2+| {blank}footnote:b1[] ZY5AA−ZY5ZZ 2+| ZY5AAA−ZY5YZZ
.2+| Пернамбуку | PY7AA−PY7ZZ 2+| PY7AAA−PY7YZZ | PU7RAA−PU7YZZ
2+| {blank}footnote:b1[] ZY7AA−ZY7ZZ 2+| ZY7AAA−ZY7YZZ
.2+| Пеауи | PS8AA−PS8ZZ 2+| PS8AAA−PS8YZZ | PU8PAA−PU8SZZ
2+| {blank}footnote:b1[] ZW8AA−ZW8ZZ 2+| ZW8AAA−ZW8YZZ
.2+| Рио-де-Жанейро | PYlAA−PYlZZ 2+| PYlAAA−PYlYZZ | PUlJAA−PUlYZZ
2+| {blank}footnote:b1[] ZYlAA−ZYlZZ 2+| ZYlAAA−ZYlYZZ
.2+| Риу-Гранди-ду-Норти | PS7AA−PS7ZZ 2+| PS7AAA−PS7YZZ | PU7IAA−PU7LZZ
2+| {blank}footnote:b1[] ZW7AA−ZW7ZZ 2+| ZW7AAA−ZW7YZZ
.2+| Риу-Гранди-ду-Сул | PY3AA−PY3ZZ 2+| PY3AAA−PY3YZZ | PU3AAA−PU3YZZ
2+| {blank}footnote:b1[] ZY3AA−ZY3ZZ 2+| ZY3AAA−ZY3YZZ
.2+| Рондония | PW8AA−PW8ZZ 2+| PW8AAA−PW8YZZ | PU8DAA−PU8FZZ
2+| {blank}footnote:b1[] ZZ8NA−ZZ8SZ 2+| ZZ8NAA−ZZ8SZZ
.2+| Рорайма | PV8AA−PV8ZZ 2+| PV8AAA−PV8YZZ | PU8TAA−PU8VZZ
2+| {blank}footnote:b1[] ZZ8TA−ZZ8ZZ 2+| ZZ8AAA−ZZ8YZZ
.2+| Санта-Катарина | PP5AA−PP5ZZ 2+| PP5AAA−PP5YZZ | PU5AAA−PU5LZZ
2+| {blank}footnote:b1[] ZZ5AA−ZZ5ZZ 2+| ZZ5AAA−ZZ5YZZ
.2+| Сан-Паулу | PY2AA−PY2ZZ 2+| PY2AAA−PY2YZZ | PU2KAA−PU2YZZ
2+| {blank}footnote:b1[] ZY2AA−ZY2ZZ 2+| ZY2AAA−ZY2YZZ
.2+| Сержипи | PP6AA−PP6ZZ 2+| PP6AAA−PP6YZZ | PU6AAA−PU6IZZ
2+| {blank}footnote:b1[] ZZ6AA−ZZ6ZZ 2+| ZZ6AAA−ZZ6YZZ
.2+| Токантинс | PQ2AA−PQ2ZZ 2+| PQ2AAA−PQ2YZZ | PU2IAA−PU2JZZ
2+| {blank}footnote:b1[] ZX2AA−ZX2ZZ 2+| ZX2AAA−ZX2YZZ
.2+| Острова Маритимас | PY0AA−PY0ZZ 2+| PY0AAA−PY0ZZZ | PU0AAA−PU0ZZZ
2+| {blank}footnote:b1[] ZY0AA−ZY0ZZ 2+| ZY0AAA−ZY0ZZZ

|===


=== Бруней-Даруссалам

Любительские станции:: V85, за которыми следуют 2 или 3 буквы для связи на ВЧ и ОВЧ. 
+
V85, за которыми следует 1 буква только для связи на ОВЧ.

=== Болгария (Республика)

Любительские станции:: LZ1−LZ9, за которыми следует группа не более чем из трех букв.

=== Буркина-Фасо

Любительские станции и экспериментальные станции:: XT2 или XT3, за которыми следуют 2 буквы.

=== Бурунди (Республика)

Любительские станции:: 9U5, за которыми следуют 2 буквы.

=== Кабо-Верде (Республика)

Любительские станции:: D44AA−D44ZZ.

=== Камерун (Республика)

Любительские станции:: TJ1, за которыми следуют 2 буквы.

=== Канада

Любительские станции:: VE1, VA1, за которыми следуют 1, 2 или 3 буквы – провинции Новая Шотландия и Нью-Брансуик 
+
VE2, VA2, за которыми следуют 1, 2 или 3 буквы – провинция Квебек 
+
VE3, VA3, за которыми следуют 1, 2 или 3 буквы – провинция Онтарио 
+
VE4, VA4, за которыми следуют 1, 2 или 3 буквы – провинция Манитоба 
+
VE5, VA5, за которыми следуют 1, 2 или 3 буквы – провинция Саскачеван
+
VE6, VA6, за которыми следуют 1, 2 или 3 буквы – провинция Альберта 
+
VE7, VA7, за которыми следуют 1, 2 или 3 буквы – провинция Британская Колумбия 
+
VE8, за которыми следуют 1, 2 или 3 буквы – Северо-Западные территории (исключая Нунавут) 
+
VE9, за которыми следуют 1, 2 или 3 буквы – провинция Нью-Брансуик 
+
VE0 {blank}footnote:[VE0 предназначен для использования в тех случаях, когда любительская радиостанция работает с корабля, совершающего международные рейсы.], за которыми следуют 1, 2 или 3 буквы – любительская станция на борту морского судна 
+
VO1, за которыми следуют 1, 2 или 3 буквы – провинция Ньюфаундлен (исключая Лабрадор) 
+
VO2, за которыми следуют 1, 2 или 3 буквы – Лабрадор 
+
VY0, за которыми следуют 1, 2 или 3 буквы – территория Нунавут 
+
VY1, за которыми следуют 1, 2 или 3 буквы – территория Юкон 
+
VY2, за которыми следуют 1, 2 или 3 буквы – провинция Остров Принца Эдуарда.


Экспериментальные станции:: VX9, за которыми следуют 2 или 3 буквы – Канада (все провинции и территории).

=== Центральноафриканская Республика

Любительские станции и экспериментальные станции:: TL8, за которыми следуют 2 или 3 буквы.

=== Чад (Республика)

Любительские станции и экспериментальные станции:: TT8, за которыми следуют 2 буквы, первая из которых буква A.

=== Чили

Любительские станции:: CE или XQ, за которыми следуют цифра (обозначающая зону, в которой расположена станция) и 2 или 3 буквы.
+
CE1−CE8, за которыми следуют 2 или 3 буквы – материковая часть Чили 
+
CE9, за которыми следуют 2 или 3 буквы – Антарктика 
+
CE0Y, за которыми следуют 2 или 3 буквы – остров Пасхи 
+
CE0Z, за которыми следуют 2 буквы – острова Хуан‑Фернандес и Сан‑Феликс.

=== Колумбия (Республика)

Любительские станции:: HJ или HK, за которыми следуют цифра (0–9, обозначающая зону, к которой относится радиолюбитель) и 1, 2 или 3 буквы.

Цифры, обозначающие зону:: 0 – островная территория Колумбии и подвижная морская служба 
+
1 – департаменты Атлантико, Боливар, Кордоба и Сукре 
+
2 – департаменты Гуахира, Магдалена, Сесар и Северный Сантандер 
+
3 – департаменты Кундинамарка, Мета и Вичада 
+
4 – департаменты Антьокия и Чоко 
+
5 – департаменты Каука и Валье-дель-Каука 
+
6 – департаменты Кальдас, Толима, Рисаральда, Киндио и Уила 
+
7 – департаменты Сантандер, Бояка, Араука и Касанаре 
+
8 – департаменты Нариньо, Какета и Путумайо 
+
9 – департаменты Амасонас, Ваупес, Гуайниа и Гуавьяре.

NOTE: 5J или 5K, за которыми следуют цифра (0–9) и 1, 2 или 3 буквы, разрешены на временной основе для любительских станций, эксплуатируемых в ходе соревнований или особых событий.

=== Союз Коморских Островов

Любительские станции:: D68, за которыми следуют 2 буквы {blank}footnote:[2 буквы являются идентификатором оператора.].


=== Конго (Республика)

Любительские станции и экспериментальные станции:: TN8AA−TN8ZZ.

=== Острова Кука

Любительские станции:: ZK1, за которыми следуют 2 буквы.

=== Коста-Рика

Любительские станции:: TE или TI, за которыми следуют цифра и группа не более чем из трех букв.

=== Кот-д'Ивуар(Республика)

Любительские станции:: TU2AA−TU2ZZ.

Экспериментальные станции:: TU3AA−TU3ZZ.

=== Хорватия (Республика)

Любительские станции:: 9A, за которыми следуют цифра и 1, 2 или 3 буквы.

=== Куба

Любительские станции:: T4, CL, CM или CO, за которыми следуют цифра (обозначающая провинцию или зону, в которой расположена станция) и 1, 2 или 3 буквы.

Цифры, обозначающие провинцию или зону:: 1 – провинция Пинар-дель-Рио 
+
2 – провинция Гавана-сити 
+
3 – провинция Гавана 
+
4 – муниципалитет Остров Хувентуд 
+
5 – провинция Матансас 
+
6 – провинции Вилья-Клара, Сьенфуэгос и Санкти-Спиритус 
+
7 – провинции Сьего-де-Авила и Камагуэй 
+
8 – провинции Сантьяго-де-Куба, Гранма, Ольгин, Лас-Тунас и Гуантанамо.

=== Кюрасао 

Любительские станции:: PJ2AA−PJ2ZZZ.

=== Кипр (Республика)

Любительские станции:: 5B4AAA−5B4ZZZ.

NOTE: Иностранные радиолюбители используют позывной сигнал, присвоенный им их администрацией, за которым следуют косая черта (/) и далее 5B4, на временной основе.


=== Чешская Республика

Любительские станции:: OK0−OK8, за которыми следуют 1, 2 или 3 буквы
+
OL0−OL9, за которыми следуют 1, 2 или 3 буквы
+
OK8, за которыми следуют 2 или 3 буквы для иностранцев, осуществляющих передачу с территории Чешской Республики
+
OK0, за которыми следуют 2 или 3 буквы исключительно для непредвиденных задач
+
OL0−OL9, за которыми следует 1 буква только для целей международных соревнований любителей
+
OL0−OL9, за которыми следуют 2 или 3 буквы только для непредвиденных задач и только на период существования этих задач.

Экспериментальные станции:: OK9, за которыми следуют 2 или 3 буквы.

=== Дания

[%unnumbered]
|===
4+^.^| Любительские станции
^.^| Район ^.^| Префикс ^.^| Цифра ^.^| Суффикс
| Дания ^.^| OU, OV, OZ, 5P, 5Q ^.^| 0–9 | До 4 знаков, последний из которых должен быть буквой
| Фарерские острова ^.^| OY ^.^| 1–9 | 1, 2 или 3 буквы
| Гренландия ^.^| OX ^.^| 1–9 | 2 или 3 буквы

|===

=== Джибути (Республика)

Любительские станции:: J28AA−J28ZZ {blank}footnote:[Для любительских станций, эксплуатируемых на постоянной основе.] 
+
J20AA−J20ZZ {blank}footnote:[Для любительских станций, эксплуатируемых на временной основе.].

NOTE: Для особых событий радиолюбители используют J20, за которыми следует группа из 3 букв.

=== Содружество Доминики

Любительские станции и экспериментальные станции:: J73AA−J73ZZ.

=== Доминиканская Республика

Любительские станции:: HI, за которыми следуют цифра (обозначающая зону, в которой расположена станция) и группа не более чем из трех букв.

Цифры, обозначающие зону:: 1 – остров Беата 
+
2 – остров Саона 
+
3 – Регион центрального Сибао 
+
4 – Регион северо-западной линии 
+
5 – Юго-западный регион 
+
6 – Южный центральный регион 
+
7 – Восточный регион 
+
8 – Южный регион 
+
9 – Северо-западный регион.

=== Эквадор

Любительские станции:: HC или HD, за которыми следуют цифра (1–8, обозначающая провинцию, в которой расположена станция) и 1, 2 или 3 буквы.
+
Новички после цифры, обозначающей провинцию, должны использовать букву N.

Цифры, обозначающие провинцию:: 1 – провинции Карчи, Имбабура и Пичинча 
+
2 – провинции Гуаяс (побережье) и Лос-Риос 
+
3 – провинции Эль-Оро (побережье) и Лоха 
+
4 – провинции Манаби (побережье) и Эсмеральдас (побережье) 
+
5 – провинции Чимборасо, Каньяр и Асуай 
+
6 – провинции Котопахи, Тунгурауа и Боливар 
+
7 – провинции Напо, Пастаса, Морона-Сантьяго, Самора и Сукаумбиос 
+
8 – провинция Галапагосские острова.

Экспериментальные станции:: HD9, за которыми следуют 3 буквы.

NOTE: Радиолюбители, работающие в рамках состязаний, должны использовать HD9, за которыми следует 1 буква, на временной основе.

=== Египет (Арабская Республика)

Любительские станции:: SU, за которыми следуют цифра и 2 буквы.

=== Сальвадор (Республика)

Любительские станции:: YS, за которыми следуют цифра (1–9, обозначающая зону, в которой расположена станция) и группа не более чем из трех букв.

Цифры, обозначающие зону:: 1 – департамент Сан-Сальвадор 
+
2 – департамент Санта-Ана 
+
3 – департамент Сан-Мигель 
+
4 – департамент Ла-Либертад 
+
5 – департаменты Ла-Пас, Кускатлан и Чалатенанго 
+
6 – департаменты Усулутан, Сан-Висенте и Кабаньяс 
+
7 – департамент Сонсонате 
+
8 – департамент Ауачапан 
+
9 – департаменты Морасан и Ла-Унион.

Экспериментальные станции:: HU9, за которыми следуют 2 буквы.

NOTE: Иностранные радиолюбители должны использовать YS, за которыми следуют цифра (1–9, обозначающая рабочую зону), косая черта (/) и их собственный позывной сигнал.

=== Эстонская Республика

Любительские станции:: ES, за которыми следуют цифра (0–9, обозначающая уезд, в котором расположена станция) и 1, 2 или 3 буквы.

Цифры, обозначающие уезды:: 0 – уезды Хийумаа, Сааремаа и все малые острова Вяйнамере 
+
1 – Таллин 
+
2 – уезд Харьюмааа 
+
3 – уезды Ляэне, Рапла и Ярвамаа 
+
4 – уезды Ляэне-Вирумаа и Ида-Вирумаа 
+
5 – уезды Йыгева и Тартумаа 
+
6 – уезды Пылва, Валга и Вырумаа 
+
7 – уезд Вльяндимаа 
+
8 – уезд Пярнумаа 
+
9 – экстерриториальный (для официального использования Эстонским радиолюбительским союзом).

Если любительские станции работают как переносные или подвижные станции, за их позывными сигналами следуют косая черта (/) и буквы "MM", "AM", "M" или "P" в следующих случаях:

* "MM", если станция эксплуатируется на борту эстонского судна в международных водах 

* "AM", если станция эксплуатируется на борту эстонского воздушного судна 

* "M", если станция эксплуатируется на борту какого-либо иного транспортного средства, в том числе на борту судна, находящегося в национальных водах 

* "P", в случае переносимой вручную станции.

Иностранные радиолюбители во время своего визита в Эстонию должны использовать ES, за которыми следуют цифра (0–8), обозначающая уезд, в котором находится станция, косая черта (/) и их собственный позывной сигнал.


=== Эфиопия (Федеративная Демократическая Республика)

Любительские станции:: ET3AA−ET3ZZ 
+
9E3AA−9F3ZZ.

=== Фиджи (Республика)

Любительские станции:: 3D2, за которыми следуют 2 буквы.

Экспериментальные станции:: 3D3, за которыми следуют 2 буквы.

=== Финляндия

Любительские станции и экспериментальные станции:: OF, OG, OH, OI или OJ, за которыми следуют цифра и группа не более чем из 4 знаков, последний из которых должен быть буквой.

=== Франция

[%unnumbered]
|===
4+^.^| Любительские станции
^.^| F {blank}footnote:[F, за которыми следует буква (A, B, C, D или E), обозначающая группу, к которой относится данный радиолюбитель, далее следует буква F, обозначающая станцию радиоклуба.] ^.^| 0–9 {blank}footnote:[Цифра от 0 до 9 (кроме цифры 7).] ^.^| AA−ZZZ {blank}footnote:c3[2 или 3 буквы, характеризующие радиолюбителя.] ^.^| Франция (континентальная)
| | | | _Корсика, заморские департаменты и территории (за исключением Новой Каледонии):_
^.^| FG ^.^| 1−5 {blank}footnote:[Цифра, обозначающая группу, к которой относится радиолюбитель (1: группа A, 2: группа B, 3: группа C, 4: группа D и 5: группа E), цифра 0, обозначающая станцию радиоклуба.] ^.^| AA−ZZZ {blank}footnote:c3[] | Гваделупа
^.^| FH ^.^| » ^.^| » | Майотта
^.^| FJ ^.^| » ^.^| » | Сен-Бартельми
^.^| FM ^.^| » ^.^| » | Мартиника
^.^| FO ^.^| » ^.^| » | Французская Полинезия
^.^| FP ^.^| » ^.^| » | Сен-Пьер и Микелон
^.^| FR ^.^| » ^.^| » | Реюньон
^.^| FT ^.^| » ^.^| » | Южные и Антарктические территории
^.^| FW ^.^| » ^.^| » | Уоллис и Футуна
^.^| FY ^.^| » ^.^| » | Гвиана
^.^| TK ^.^| » ^.^| » | Корсика
^.^| FK ^.^| 8 ^.^| AA−ZZZ {blank}footnote:[2 или 3 буквы, характеризующие радиолюбителя, K в качестве первой буквы обозначает станцию радиоклуба.] | Новая Каледония

|===


=== Габонская Республика

Любительские станции:: TR8AA−TR8ZZ.

=== Гамбия (Республика)

Любительские станции:: C53AA−C53ZZ.

=== Грузия

Любительские станции:: 4L, за которыми следуют цифра и 1, 2 или 3 буквы.

=== Германия (Федеративная Республика)

[%unnumbered]
|===
3+^.^| Любительские станции
^.^| Позывные сигналы ^.^| Цель использования ^.^| Класс
^.^| 1 ^.^| 2 ^.^| 3
| DA0A−DA0ZZZ | Станции клубов ^.^| A
| DA1A−DA1Z {blank}footnote:d1[Только для персонала в рамках SOFA (Соглашение о статусе сил).] | Станции клубов ^.^| A
| DA1AA−DA1ZZZ {blank}footnote:d1[] | Станции индивидуального пользования, станции клубов, ретрансляторы, маяки ^.^| A
| DA2A−DA3Z | Станции клубов ^.^| A
| DA2AA−DA2ZZZ | Станции индивидуального пользования, станции клубов, ретрансляторы, маяки ^.^| A
| DA4A−DA4Z | Специальные экспериментальные исследования – как станции клубов ^.^| E
| DA4AA−DA4ZZZ {blank}footnote:d2[Также для персонала в рамках SOFA (Соглашение о статусе сил).] | Специальные экспериментальные исследования – как станции индивидуального пользования ^.^| E
| DA5A−DA5Z | Специальные экспериментальные исследования – как станции клубов ^.^| A
| DA5AA−DA5ZZZ {blank}footnote:d2[] | Специальные экспериментальные исследования – как станции индивидуального пользования ^.^| A
| DA6A−DA6Z {blank}footnote:d1[] | Станции клубов ^.^| E
| DA6AA−DA6ZZZ {blank}footnote:d1[] | Станции индивидуального пользования, станции клубов, ретрансляторы, маяки ^.^| E
| DA7A−DA9Z | Станции клубов ^.^| E
| DB0A−DD9Z | Станции клубов ^.^| A
| DB0AA−DB0ZZZ | Ретрансляторы, маяки ^.^| A
| DB1AA−DD9ZZZ | Станции индивидуального пользования ^.^| A
| DF0A−DH9Z | Станции клубов ^.^| A
| DF0AA−DF0ZZZ | Станции клубов ^.^| A
| DF1AA−DH9ZZZ | Станции индивидуального пользования ^.^| A
| DJ0A−DM9Z | Станции клубов ^.^| A
| DJ0AA−DJ9ZZZ | Станции индивидуального пользования ^.^| A
| DK0AA−DK0ZZZ | Станции клубов ^.^| A
| DK1AA−DK9ZZZ | Станции индивидуального пользования ^.^| A
| DL0AA−DL0ZZZ | Станции клубов ^.^| A
| DL1AA−DL9ZZZ | Станции индивидуального пользования ^.^| A
| DM0AA−DM0ZZZ | Ретрансляторы, маяки (DM0ZA−DM0ZZZ: ретрансляторы с новой технологией) ^.^| A
| DM1AA−DM9ZZZ | Станции индивидуального пользования ^.^| A
| DN0A−DN0ZZZ | Станции клубов ^.^| E
| DN1AA−DN6ZZZ {blank}footnote:d2[] | Станции, используемые для передачи действующих команд по радио ^.^| A
| DN7AA−DN8ZZZ {blank}footnote:d2[] | Станции, используемые для передачи действующих команд по радио ^.^| E
| DO0A−DO9Z | Станции клубов ^.^| E
| DO0AA−DO0ZZZ | Ретрансляторы, маяки (DO0ZA−DO0ZZZ: ретрансляторы с новой технологией) ^.^| E
| DO1AA−DO9ZZZ | Станции индивидуального пользования ^.^| E
| DP0A−DP1Z | Станции клубов (экстерриториальные местоположения) ^.^| A
| DP0AA−DP1ZZZ | Станции клубов, ретрансляторы, маяки, специальные экспериментальные исследования (экстерриториальные местоположения) ^.^| A
| DP2A−DP2Z | Станции клубов (экстерриториальные местоположения) ^.^| E
| DP2AA−DP2ZZZ | Станции клубов, ретрансляторы, маяки, специальные экспериментальные исследования (экстерриториальные местоположения) ^.^| E
| DP3A−DR9Z | Станции клубов ^.^| A

|===


NOTE: Иностранные радиолюбители, не имеющие постоянного местожительства в Германии, используют DL, за которыми следуют косая черта (/) и их национальный позывной сигнал для класса A, или DO, за которыми следуют косая черта (/) и их национальный позывной сигнал для класса E, или персональный обязательный позывной сигнал.

Экспериментальные станции:: DI2AA−DI2ZZ.

=== Гана

Любительские станции:: 9G1, за которыми следуют 2 или боле букв {blank}footnote:[Для национальных радиолюбителей.].
+
9G5, за которыми следуют 2 или боле букв {blank}footnote:[Для иностранных радиолюбителей.].

Экспериментальные станции:: 9G2, за которыми следуют 2 буквы.


=== Греция

Любительские станции и экспериментальные станции:: SV {blank}footnote:[Класс 1.] или SW {blank}footnote:[Класс 2.], за которыми следуют цифра (обозначающая округ, в котором расположена станция) и 2 или 3 буквы.

Цифры, обозначающие округа:: 1 – Центральная Греция 
+
2 – Центральная и Западная Македония 
+
3 – Пелопоннес 
+
4 – Фессалия 
+
5 – префектура Додеканес 
+
6 – Эпир 
+
7 – Восточная Македония и Фракия 
+
8 – все острова (за исключением относящихся к префектурам Крита и к префектуре Додеканес) 
+
9 – префектуры Крита и относящиеся к ним острова.


[NOTE]
==== 
. SV0 или SW0, за которыми следуют 2 или 3 буквы, присваиваются греческим радиолюбителям, имеющим иностранную лицензию, и иностранным радиолюбителям, имеющим постоянное проживание.

. Префикс J4, SX или SY присваивается как специальный позывной сигнал греческим союзам радиолюбителей, греческим командам радиолюбителей, греческим радиолюбителям и иностранным радиолюбителям.

. Префикс SZ присваивается Греческому радиолюбительскому союзу и университетским лабораториям Греции, работающим в области беспроводной электросвязи.
====

=== Гватемала (Республика)

Любительские станции:: TG, за которыми следуют цифра (4–9, обозначающая департамент, в которой расположена станция) и 2 буквы.

Цифры, обозначающие департамент:: 4 – Солола, Чимальтенанго, Сучитепекес, Эскуинтла и Санта-Роса 
+
5 – Уэуэтенанго, Киче и Тотоникапан 
+
6 – Сакапа, Чикимула и Хутьяпа 
+
7 – Петен, Альта-Верапас и Исабаль 
+
8 – Сан-Маркос, Кесальтенанго и Реталулеу 
+
9 – Гватемала, Халапа, Эль-Прогресо, Баха-Верапас и Сакатепекес.

Экспериментальные станции:: TD9A−TD9Z.

=== Гвинейская Республика

Любительские станции:: 3X0AA−3X9ZZ.

Экспериментальные станции:: 3X2AAA−3X9ZZZ.

=== Гвинея-Бисау (Республика)

Любительские станции:: J52UAB−J52UAI.


=== Гайана

Любительские станции и экспериментальные станции:: 8R1AAA−8R1ZZZ –  Демерара 
+
8R2AAA−8R2ZZZ –  Бербис 
+
8R3AAA−8R3ZZZ –  Эссекибо.

=== Гаити (Республика)

Любительские станции:: HH, за которыми следуют цифра (обозначающая зону, в которой расположена станция) и 2 буквы.

=== Гондурас (Республика)

Любительские станции:: HR, за которыми следуют цифра (1–9, обозначающая зону, в которой расположена станция) и:

* 1 буква для высшего класса при условии 20 и более лет удовлетворительной работы;

* 2 буквы для высшего класса при условии менее 20 лет удовлетворительной работы;

* 3 буквы для высокого и общего класса.

+

HQ, за которыми следуют цифра (1–9, обозначающая зону, в которой расположена станция) и:

* 1 буква для национальных и международных особых событий, в которых участвуют местные и иностранные радиолюбители из администраций, имеющих соглашения на основе взаимности;

* 3 буквы для класса новичка.

=== Венгрия

Любительские станции:: HA или HG, за которыми следуют цифра (0–9) и группа не более чем из 4 знаков, последний из которых должен быть буквой.

=== Исландия

Любительские станции:: TF, за которыми следуют цифра (обозначающая район, в котором расположена станция) и 1, 2 или 3 буквы.
+
Для владельцев лицензии новичка последняя цифра должна быть N.

Позывные сигналы, за которыми следуют косая черта (/) и буквы "M" или "P", используются в следующих случаях:

* буква "M" обозначает подвижную станцию, 

* буква "P" обозначает переносную станцию.

=== Индия (Республика)

Любительские станции:: VU2 или VU3, за которыми следуют 2 или 3 буквы – континентальная Индия 
+
VU4 или VU7, за которыми следуют 2 или 3 буквы – национальные острова.

Экспериментальные станции:: VU4, за которыми следуют 2 буквы.

=== Индонезия (Республика)

Любительские станции:: YB или YE, за которыми следуют цифра (0–9) и 1 {blank}footnote:e1[Однобуквенный суффикс предназначен не для личного позывного сигнала, а только для станций организаций в рамках мероприятий особых событий.], 2 или 3 буквы  –лицензия высокого класса 
+
YC или YF, за которыми следуют цифра (0–9) и 1 {blank}footnote:e1[], 2 или 3 буквы  –лицензия общего класса 
+
YD, YG или YH, за которыми следуют цифра (0–9) и 1 {blank}footnote:e1[], 2 или 3 буквы  –лицензия новичка.

=== Иран (Исламская Республика)

Любительские станции:: EP1AA−EP9ZZ.

=== Ирак (Республика)

Любительские станции:: YI1, за которыми следуют 3 буквы.

=== Ирландия

Любительские станции:: EI, за которыми следуют цифра (2–9) и группа не более чем из трех букв.

=== Израиль (Государство)

Любительские станции:: 4X1, за которыми следуют 2 или 3 буквы 
+
4X4, за которыми следуют 2 или 3 буквы 
+
4X6, за которыми следуют 2 или 3 буквы 
+
4X8, за которыми следуют 2 или 3 буквы 
+
4Z1, за которыми следуют 2 или 3 буквы 
+
4Z4, за которыми следуют 2 или 3 буквы 
+
4Z5, за которыми следуют 2 или 3 буквы 
+
4Z7, за которыми следуют 2 или 3 буквы 
+
4Z9, за которыми следуют 2 или 3 буквы.

=== Италия

Любительские станции:: I0 или IK0, за которыми следуют 2 или 3 буквы – Лацио и Умбрия
+
I1 или IK1, за которыми следуют 2 или 3 буквы – Лигурия, Пьемонт и провинция Новара
+
I2 или IK2, за которыми следуют 2 или 3 буквы – Ломбардия и провинция Мантуя
+
I3 или IK3, за которыми следуют 2 или 3 буквы – Венето и провинция Ровиго
+
I4 или IK4, за которыми следуют 2 или 3 буквы – Эмилия-Романья и провинция Пьяченца
+
I5 или IK5, за которыми следуют 2 или 3 буквы – Тоскана
+
I6 или IK6, за которыми следуют 2 или 3 буквы – Марке и Абруццо
+
I7 или IK7, за которыми следуют 2 или 3 буквы – Апулия и провинция Матера
+
I8 или IK8, за которыми следуют 2 или 3 буквы – Кампания, Молизе, Калабрия и провинция Потенца
+
IA5, за которыми следуют 2 или 3 буквы – "Тосканские" острова (Капрая, Черболи, Эльба, Формика-ди-Бурано, Формике-ди-Гроссето, Джаннутри, Джильо, Горгона, Монтекристо, Пьяноса, Сколио а'Африка)
+
IB0, за которыми следуют 2 или 3 буквы – "Понтийские" острова (Пальмарола, Понца, Сколио-делла-Ботте, Санто-Стефано, Вентотене, Дзаноне)
+
IC8, за которыми следуют 2 или 3 буквы – "Неаполитанские" острова (Капри, Искья, Ли Галли, Прочида, Вивара)
+
ID9, за которыми следуют 2 или 3 буквы – "Эолийские" острова (Аликуди, Басилуццо, Дино, Филикуди, Формике, Липари, Лиска- Бьянка, Панареа, Салина, Сан-Пьетро, Ла Канна, Стромболи, Стромболиччио, Вулькано)
+
IE9, за которыми следуют 2 или 3 буквы – острова Устика
+
IF9, за которыми следуют 2 или 3 буквы – "Эгадские" острова (Асинелли, Фавиньяна, Ла Формика, Леванцо, Мараоне, Мареттимо, Станьоне)
+
IG9, за которыми следуют 2 или 3 буквы – "Пелагские" острова (Лампедуза, Лампионе, Линоза)
+
IH9, за которыми следуют 2 или 3 буквы – острова Пантеллерия
+
IJ7, за которыми следуют 2 или 3 буквы – архипелаг "Черади"
+
IL7, за которыми следуют 2 или 3 буквы – острова "Тремити" (Капрара, Пьяноза, Сан-Домино, Сан‑Никола)
+
IM0, за которыми следуют 2 или 3 буквы – "Сардинские" острова (Азинара, Бисче, Буделли, Карбонара, Капрера, Каволи, Корчелли, Кретачо, Форадада, Эль-Каталано, Эль-Торо, Эль-Вителло, Ла‑Маддалена, Ла-Вакка, Маль-ди-Вентре, Молара, Морторио, Нибани, Ольястра, Пан-ди-Дзуккеро, Пьяна, Кирра, Радзоли, Росса, Рулья, С.-Антиоко, С.‑Пьетро, С.‑Макарио, С.-Мария, Серпентара, Соффи, Спарджи, Су‑Гвидеу,Таволара)
+
IN3, за которыми следуют 2 или 3 буквы – Трентино-Альто-Адидже
+
IP1, за которыми следуют 2 или 3 буквы – "Лигурийские" острова
+
IS0, за которыми следуют 2 или 3 буквы – Сардиния
+
IT9, за которыми следуют 2 или 3 буквы – Сицилия
+
IV3, за которыми следуют 2 или 3 буквы – Фриули и Венеция Джулия
+
IW0, за которыми следуют 2 или 3 буквы – Специальные лицензии
+
IX1, за которыми следуют 2 или 3 буквы – Валле д'Аоста.

=== Ямайка

Любительские станции и экспериментальные станции:: 6Y5AA−6Y5ZZ.

NOTE: Иностранные любители используют позывной сигнал, присвоенный им их администрацией, за которыми следуют косая черта (/) и далее 6Y5.

=== Япония

Любительские станции:: JA _n_ AA−JA _n_ ZZ (_n_ = 0–9)
+
JR6AA−JR6NZ
+
JR _n_ VA−JR _n_ WZ (_n_ = 0–9)
+
JR6YA−JR6YZ
+
J _xn_ AAA−J _xn_ QQZ (_x_ = A, E−S) (_n_ = 0–9)
+
J _xn_ QUA−J _xn_ ZZZ (_x_ = A, E−S) (_n_ = 0–9)
+
JD1AAA−JD1QQZ
+
JD1QUA−JD1ZZZ
+
7J _n_ AAA−7J _n_ BZZ (_n_ = 0, 4, 5, 7−9)
+
7J _n_ AAA−7J _n_ CZZ (_n_ = 2, 3, 6)
+
7J1AAA−7J1DZZ
+
7J _n_ YAA−7J _n_ YMZ (_n_ = 0−5, 7−9)
+
7J6YAA−7J6YQZ
+
7 _xn_ AAA−7 _xn_ QQZ (_x_ = K−N) (_n_ = 1−4)
+
7 _xn_ QUA−7 _xn_ ZZZ (_x_ = K−N) (_n_ = 1−4)
+
8 _xn_ AAA−8 _xn_ QZZ (_x_ = J, N) (_n_ = 0–9)
+
8 _xn_ QUA−8 _xn_ ZZZ (_x_ = J, N) (_n_ = 0–9).

Экспериментальные станции:: J _xn_ A−J _xn_ Z (_x_ = B, G, J, O, S) (_n_ = 2–9) 
+
J _xn_ AA−J _xn_ ZZ (x= B, G, J, O, S) (_n_ = 2–9).

=== Иорданское Хашимитское Королевство

Любительские станции:: JY1AA−JY9ZZ.

=== Кения (Республика)

Любительские станции:: 5Z4AA−5Z4ZZ.

Экспериментальные станции:: 5Z5AA−5Z5ZZ.

=== Кирибати (Республика)

Любительские станции:: T3, за которыми следуют цифра (0–9) и группа не более чем из трех букв.

Экспериментальные станции:: T3, за которыми следуют цифра (не являющаяся 0 или 1) и группа не более чем из трех букв.

=== Корея (Республика)

Любительские станции:: 1) HL1AA−HL9ZZ +
HL1AAA−HL9ZZZ
+
2) HL0, за которыми следуют 2 или 3 буквы (группа любителей).

Экспериментальные станции:: 6M2AA−6M2ZZ 
+
6N2AA−6N2ZZ.

NOTE: DS, DT, D7, D8, D9, 6K, 6L, 6M, 6N, за которыми следуют цифра и 2 или 3 буквы, присваиваются на временной основе в особых случаях.

=== Кувейт (Государство)

Любительские станции:: 9K2, за которыми следуют 1 или 2 буквы 
+
9K9, за которыми следует 1 буква

=== Кыргызская Республика

Любительские станции:: EX, за которыми следуют цифра (0–9) и 1 или 2 буквы.

NOTE: Иностранные радиолюбители используют EX, за которыми следуют косая черта (/) и их национальный позывной сигнал.

=== Лаосская Народно-Демократическая Республика

Любительские станции:: XW8AA−XW8DZ.

Экспериментальные станции:: XW8EA−XW8EZ.

=== Латвийская Республика

Любительские станции и экспериментальные станции:: YL, за которыми следуют цифра и 1, 2 или 3 буквы.

=== Ливан

Любительские станции:: OD5, за которыми следуют 2 буквы.

Экспериментальные станции:: OD9, за которыми следуют 2 буквы.

=== Лесото (Королевство)

Любительские станции и экспериментальные станции:: 7P8, за которыми следует группа не более чем из трех букв.

=== Ливия

Любительские станции:: 5A, за которыми следуют цифра (0–9) и группа не более чем из трех букв.

Экспериментальные станции:: 5A, за которыми следуют цифра (не являющаяся 0 или 1) и группа не более чем из трех букв.

=== Лихтенштейн (Княжество)

Любительские станции:: HB0AAA−HB0XXX 
+
HB0YAA−HB0YZZ  –  лицензия новичка 
+
HB0ZAA−HB0ZZZ.

=== Литовская Республика

Любительские станции и экспериментальные станции:: LY, за которыми следуют цифра (1–4) и 1–4 буквы.

NOTE: LY, за которыми следуют 2–4 цифры и 1 буква, присваиваются только для формирования нерегулярно используемых позывных радиосигналов.

=== Люксембург

[%unnumbered]
|===
| LX0A−LX0ZZZZ | Ретрансляторы, маяки, групповые станции
| LX1A−LX1ZZZZ .3+| Станции индивидуального пользования, эксплуатируемые со свидетельством HAREC.
| LX2A−LX2ZZZZ
| LX3A−LX3ZZZZ
| LX4A−LX4ZZZZ | Групповые станции
| LX5A−LX5ZZZZ | Групповые станции, экспериментальные станции
| LX6A−LX6ZZZZ | Станции индивидуального пользования, эксплуатируемые новичками.
| LX7A−LX7ZZZZ | Станции индивидуального пользования, эксплуатируемые в рамках состязаний.
| LX8A−LX8ZZZZ .2+| Групповые станции
| LX9A−LX9ZZZZ

|===

NOTE: Имеющие временную лицензию иностранные радиолюбители должны использовать LX, за которыми следуют косая черта (/) и их собственный позывной сигнал.

=== Мадагаскар (Республика)

Любительские станции:: 5R8, за которыми следует группа не более чем из трех букв.

Экспериментальные станции:: 5S6, за которыми следует группа не более чем из трех букв.

=== Малави

Любительские станции:: 7Q7, за которыми следуют 2 буквы.


=== Малайзия

[%unnumbered]
|===
3+^.^| Любительские станции
^.^| Позывные сигналы ^.^| Класс ^.^| Территория
| 9M2AAA−9M2ZZZ ^.^| A .2+^.^| Полуостров Малайзия
| 9W2AAA−9W2ZZZ ^.^| B
| 9M6AAA−9M6ZZZ ^.^| A .2+^.^| Сабах
| 9W6AAA−9W6ZZZ ^.^| B
| 9M8AAA−9M8ZZZ ^.^| A .2+^.^| Саравак
| 9W8AAA−9W8ZZZ ^.^| B
3+^.^| Экспериментальные станции
3+| 9M4EAA−9M4EZZ

|===

=== Мальдивская Республика

Любительские станции:: 8Q7AA−8Q7ZZ.

=== Мальта

[width=496]
|===
3+^.^| Любительские станции
^.^| Позывные сигналы ^.^| Класс ^.^| Район
| 9H1A−9H1ZZ ^.^| A | Мальта
| 9H4A−9H4ZZ ^.^| A | остров Гоцо
| 9H5A−9H5ZZ ^.^| B | Мальта и остров Гоцо
3+^.^| Экспериментальные станции
3+| [[OLE_LINK3]]9H3A−9H3ZZ {blank}footnote:[Также для временно используемых станций.]

|===


=== Мавритания (Исламская Республика)

Любительские станции:: 5T5, за которыми следуют 2 буквы.

Экспериментальные станции:: 5T2, за которыми следуют 2 буквы.

=== Маврикий (Республика)

Любительские станции:: 3B6, за которыми следуют 2 буквы –  Агалега 
+
3B7, за которыми следуют 2 буквы –  Св. Брандон 
+
3B8, за которыми следуют 2 буквы –  Маврикий 
+
3B9, за которыми следуют 2 буквы –  Родригес.

NOTE: Иностранные радиолюбители, имеющие гостевую лицензию, должны использовать 3B8, за которыми следуют косая черта (/) и их собственный позывной сигнал.

=== Мексика

[%unnumbered]
|===
2+^.^| Любительские станции
2+| Континентальная часть 
2+| XE0A−XE0ZZZ 
| XE1A−XE1ZZZ | _Зона 1_: Федеральный округ, Колима, Гуанахуато, Идальго, Халиско, штат Мехико, Мичоакан, Морелос, Наярит, Пуэбла, Керетаро, Тласкала и Веракрус
| XE2A−XE2ZZZ | _Зона 2:_ Агуаскальентес, Нижняя Калифорния (северная), Нижняя Калифорния (южная), Коауила, Чиуауа, Дуранго, Нуэво-Леон, Сан‑Луис-Потоси, Синалоа, Сонора, Тамаулипас и Сакатекас
| XE3A−XE3ZZZ | _Зона 3_: Кампече, Чьяпас, Герреро, Оахака, Кинтана-Роо, Табаско и Юкатан
2+| Островная часть 
| XF0A−XF0ZZZ | 
| XF1A−XF1ZZZ | _Зона 1_: Нижняя Калифорния (Северная), Нижняя Калифорния (Южная), Сонора, Синалоа и Наярит
| XF2A−XF2ZZZ | _Зона 2_: Тамаулипас, Веракрус, Табаско и Кампече
| XF3A−XF3ZZZ | _Зона 3_: Юкатан и Кинтана-Роо
| XF4A−XF4ZZZ | _Зона 4_: Халиско, Колима, Мичоакан, Герреро, Оахака и Чьяпас

|===

[NOTE]
====
. Иностранные радиолюбители, работающие в континентальной части, используют XE1, XE2 или XE3, за которыми следуют косая черта (/) и их национальный позывной сигнал.

. Только для особых событий радиолюбители используют XA, XB, XC, XD, XE, XF, XG, XH, XI, 4A, 4B, 4C, 6D, 6E, 6F или 6J, за которыми следуют цифра и группа не более чем из 3 букв.
====

=== Федеративные Штаты Микронезии‎

Любительские станции:: V63, за которыми следуют 2 буквы.

Экспериментальные станции:: V62, за которыми следуют буква X и 2 буквы.

=== Молдова (Республика)

Любительские станции:: ER1–ER5, за которыми следуют одна, две или три буквы.

Суффикс может состоять из:: 
* двух или трех букв для станций индивидуального пользования (буква K запрещена в качестве первой буквы);

* трех букв для станций клубов (первой из которых является буква K);

* одной, двух, трех или более цифр и/или букв для специальных позывных сигналов, маяков и ретрансляторов.

Позывной сигнал, содержащий:: 4 знака  класс A
+
5 знаков  класс A и класс B
+
6 знаков  класс C.
+
ER6–ER0, за которыми следуют две или более цифры, используются для специальных позывных сигналов, распределенных для особых событий.
+
ER1–ER0, за которыми следуют две или более цифры, могут быть распределены:

* физическому лицу – гражданину Республики Молдова;

* иностранному гражданину или гражданину ЕС, который имеет постоянное место жительства в Республике Молдова (подтвержденное соответствующими документами);

* юридическим лицам Республики Молдова.


Позывные сигналы, за которыми следуют косая черта (/) и буквы "MM", "AM", "M" и "P", используются в следующих случаях:

MM:: для подвижных морских или речных станций,

AM:: для подвижных воздушных станций,

M:: для подвижных наземных станций,

P:: для переносных наземных станций.

NOTE: Имеющие разрешение иностранные радиолюбители используют ER, за которыми следуют косая черта (/) и их национальный позывной сигнал.

=== Монако (Княжество)

Любительские станции:: 3A2AA−3A2ZZ – Класс 1 – Общая лицензия
+
3A1AA−3A1ZZ – Класс 2 – Лицензия, ограниченная полосами 144–146 МГц и 430–440 МГц
+
3A2AAA−3A2ZZZ – Радиоклуб.

Экспериментальные станции:: 3A9A−3A9Z.

=== Марокко (Королевство)

Любительские станции:: CN2AA−CN2ZZ 
+
CN8AA−CN8ZZ.

Экспериментальные станции:: CN4AA−CN4ZZ.

=== Мозамбик (Республика)

Любительские станции:: C9, за которыми следуют цифра (обозначающая провинцию, в которой расположена станция) и группа не более чем из трех букв

Цифры, обозначающие провинции:: 1 – Мапуто 
+
2 – Газа-Иньямбане 
+
3 – Софала-Маника 
+
4 – Замбезия-Нампула 
+
5 – Тете-Ньяса 
+
6 – Кабу-Делгаду.

=== Мьянма (Союз)

Любительские станции и экспериментальные станции:: XZ2AA−XZ2ZZ.

=== Намибия (Республика)

Любительские станции:: V50A−V50ZZZ – Станция с ограниченной лицензией 
+
V51A−V51ZZZ – Станция с полной лицензией
+
V5, за которыми следует существующий позывной сигнал – Гостевая станция.

Экспериментальные станции:: V59A−V59ZZZ.

=== Науру (Республика)

Любительские станции:: C2, за которыми следуют цифра, определяющая категорию станции, и 2 буквы.

=== Непал (Федеративная Демократическая Республика‎)

Любительские станции:: 9N1AA−9N1ZZZ.

=== Нидерланды (Королевство)

Любительские станции:: PA0, PA1, PA6, PI4, PI6, PI7 или PI8, за которыми следуют 2 или 3 буквы 
+
PA2, PA3, PB0, PD0, PE0, PE1, PI1, PI2 или PI3, за которыми следуют 3 буквы.

Экспериментальные станции:: PI5 или PI9, за которыми следуют 2 или 3 буквы.

=== Новая Зеландия

[%unnumbered]
|===
2+^.^| Любительские станции и экспериментальные станции
^.^| Позывные сигналы ^.^| Районы
^.^| 1 ^.^| 2
| ZL1AA−ZL4WZ +
ZL1AAA−ZL4WZZ +
ZL1AAAA−ZL4WZZZ | Новая Зеландия
| ZK0A−ZK9ZZZZ +
ZL0A−ZL0ZZZZ +
ZL1A−ZL4W +
ZM0A−ZM0ZZZZ +
ZM1A−ZM9ZZZZ {blank}footnote:[Для соревнований и других особых событий любители используют префикс ZM вместо ZL.] | Особые события в Новой Зеландии
| ZL5AA−ZL5WZ +
ZL5AAA−ZL5WZZ +
ZL5AAAA−ZL5WZZZ
| Антарктика
| ZL5A−ZL5W | Особые события в Антарктике
| ZL6AA−ZL6WZ +
ZL6AAA−ZL6WZZ +
ZL6AAAA−ZL6WZZZ | NZART {blank}footnote:f1[Ассоциация радиопередатчиков Новой Зеландии‎ (NZART).]
| ZL6A−ZL6W | Особые события NZART {blank}footnote:f1[]
| ZL7AA−ZL7WZ +
ZL7AAA−ZL7WZZ +
ZL7AAAA−ZL7WZZZ | Острова Чатем
| ZL7A−ZL7W | Особые события на островах Чатем
| ZL8AA−ZL8WZ +
ZL8AAA−ZL8WZZ +
ZL8AAAA−ZL8WZZZ | Острова Кермадек
| ZL8A−ZL8W | Особые события на островах Кермадек
| ZL9AA−ZL9WZ +
ZL9AAA−ZL9WZZ +
ZL9AAAA−ZL9WZZZ | Окленд/острова Кемпбелл
| ZL9A−ZL9W | Особые события в Окленде/на островах Кемпбелл

|===


=== Никарагуа

Любительские станции:: YN, за которыми следуют цифра (обозначающая зону, в которой расположена станция) и 2 или 3 буквы.

Цифры, обозначающие зоны:: 1 – Манагуа 
+
2 – Гранада 
+
3 – Леон 
+
4 – Селая 
+
5 – Карасо и Ривас 
+
6 – Чинандега 
+
7 – Масая 
+
8 – Эстели, Мадрис и Нуэва-Сеговия 
+
9 – Матагальпа, Хинотега, Боако, Чонталес и Рио-Сан-Хуан.

=== Нигер (Республика)

Любительские станции и экспериментальные станции:: 5U2−5U9, за которыми следуют буква V и 1 или 2 буквы.

При работе станций в качестве фиксированных станций за их позывными сигналами следует буква "F".

При работе станций в качестве подвижных станций за их позывными сигналами следуют буквы "MOB".

=== Нигерия (Федеративная Республика)

Любительские станции:: 5N, за которыми следуют цифра (обозначающая зону, в которой расположена станция) и 3 буквы.

Цифры, обозначающие зоны:: 0 – Штат Лагос и Федеральная столичная территория 
+
1 – Штаты Огун, Ойо, Ондо и Экити 
+
2 – Штаты Осун, Квара, Коги и Нигер 
+
3 – Штаты Эдо, Дельта, Байельса и Анамбра 
+
4 – Штаты Энугу, Абия, Эбоньи и Риверс 
+
5 – Штаты Имо, Аква-Ибом и Кросс-Ривер 
+
6 – Штаты Бенуэ, Плато, Нассарава и Табара 
+
7 – Штаты Баучи, Гомбе, Адамава и Борно 
+
8 – Штаты Джигава, Кано, Йобе и Кацина 
+
9 – Штаты Замфара, Сокото, Кадуна и Кебби.

Экспериментальные станции:: 5N2XA−5N2ZZ 
+
5N3EA−5N3EZ 
+
5N4XA−5N4ZZ 
+
5N5EA−5N5EZ 
+
5N6XA−5N6ZZ 
+
5N7EA−5N7EZ 
+
5N8XA−5N8ZZ 
+
5N9EA−5N9EZ.

=== Ниуэ

Любительские станции:: ZK2, за которыми следуют 2 буквы.

=== Норвегия

Любительские станции:: JW0AAA−JW9ZZZ 
+
JX0AAA−JX0ZZZ 
+
LA0AAA−LA9ZZZ 
+
LB0AAA−LB9ZZZ 
+
LC0AAA−LC9ZZZ 
+
LD0AAA−LD9ZZZ 
+
3Y0AAA−3Y9ZZZ.

Экспериментальные станции:: LF2AAA−LF9ZZZ.

=== Оман (Султанат)

Любительские станции:: A40AA−A48ZZ.

Экспериментальные станции:: A49AA−A49ZZ.

=== Пакистан (Исламская Республика)

Любительские станции и экспериментальные станции:: AP2−AP9, за которыми следует группа не более чем из 3 букв.

=== Папуа-Новая Гвинея

Любительские станции:: P29BAA−P29BZZ –  Маяки 
+
P29CAA−P29CZZ –  Станции клубов 
+
P29KAA−P29KZZ –  Комбинированные лицензии 
+
P29NAA−P29NZZ –  Лицензия новичка 
+
P29RAA−P29RZZ –  Ретрансляторы 
+
P29ZAA−P29ZZZ –  Ограниченная лицензия.

=== Парагвай (Республика)

Любительские станции:: ZP, за которыми следуют цифра (1−9, обозначающая зону, в которой расположена станция) и 2 или 3 буквы, характеризующие радиолюбителя (первой из которых не является ни одна из букв I, O или Q).

Цифры, обозначающие зоны:: 1 – Департаменты Альто-Парагвай и Бокерон 
+
2 – Департамент Пресиденте-Аес 
+
3 – Департаменты Консепсьон и Амамбай 
+
4 – Департаменты Сан-Педро и Канендию 
+
5 – Асунсьон (столица) – Округ Асунсьон 
+
6 – Департаменты Кордильера, Парагуари и Сентраль 
+
7 – Департаменты Гуайра, Каагуасу и Каасапа 
+
8 – Департаменты Мисьонес и Ньеэмбуку 
+
9 – Департаменты Итапуа и Альто-Парана.

NOTE: Цифра 0 распределена любительским станциям для использования в особых случаях.

=== Перу

Любительские станции:: OA, за которыми следуют цифра (0−9, обозначающая зону, в которой расположена станция) и 1, 2 или 3 буквы.

Цифры, обозначающие зоны:: 0 – Перуанская антарктическая станция 
+
1 – Тумбес, Пьюра, Ламбаеке 
+
2 – Кахамарка, Ла-Либертад 
+
3 – Уануко, Анкаш 
+
4 – Лима, Паско, Хунин 
+
5 – Ика, Аякучо, Апуримак, Уанкавелика 
+
6 – Арекипа, Мокегуа, Такна 
+
7 – Куско, Пуно, Мадре-де-Дьос 
+
8 – Лорето, Укаяли 
+
9 – Амасонас, Сан-Мартин

NOTE: Префикс 4T присваивается на временной основе.

=== Филиппины (Республика)

Любительские станции:: DU {blank}footnote:[Радиолюбители класса A имеют право изменить префикс DU на 4D, 4E или 4F.], за которыми следуют цифра (1−9, обозначающая область, в которой расположена станция) и группа не более чем из 3 букв – Класс A, B или C
+
DY, за которыми следуют цифра (1−9, обозначающая область, в которой расположена станция) и группа не более чем из 3 букв – Класс D
+
DX или DZ, за которыми следуют цифра (1−9, обозначающая область, в которой расположена станция) и группа не более чем из 3 букв – Станции клубов.


=== Польша (Республика)

Любительские станции:: HF, SN, SO, SP, SQ или 3Z, за которыми следуют цифра (1−9, обозначающая воеводство, в котором расположена станция) и группа не более чем из четырех знаков, последний из которых должен быть буквой.
+
SO, за которыми следуют цифра (1−9, обозначающая воеводство, в котором расположена станция) и группа не более чем из четырех знаков, последний из которых должен быть буквой – для иностранных радиолюбителей, посещающих Польшу.
+
SR, за которыми следуют цифра (1−9, обозначающая воеводство, в котором расположена станция) и группа не более чем из четырех знаков, последний из которых должен быть буквой – для необслуживаемых (автоматических) любительских станций (ретрансляторов, маяков и цифровых станций).
+
HF, SN, SO, SP, SQ или 3Z, за которыми следуют цифра (1−9, обозначающая воеводство, в котором расположена станция, или 0) и группа знаков (по запросу) – для станций, используемых для особых событий или работающих в ходе соревнований и состязаний любителей (до одного года).

Цифры, обозначающие воеводство:: 1 – Заподнопоморское воеводство 
+
2 – Поморское и Куявско-Поморское воеводства 
+
3 – Великопольское и Любушское воеводства 
+
4 – Варминско-Мазурское и Подляшское воеводства 
+
5 – Мазовецкое воеводство 
+
6 – Низнесилезское и Опольское воеводства 
+
7 – Лодзинское и Свентокшиское воеводства 
+
8 – Люблинское и Подкарпатское воеводства 
+
9 – Силезское и Малопольское воеводства.

=== Португалия

[%unnumbered]
|===
5+^.^| Любительские станции
^.^| Префикс ^.^| Суффикс ^.^| Класс ^.^| Географический район ^.^| Примечание
^.^| 1 ^.^| 2 ^.^| 3 ^.^| 4 ^.^| 5
^.^| CQ0 ^.^| 2–4 знака ^.^| – ^.^| Португалия ^.^| {blank}footnote:g2[Позывные сигналы, присваиваемые любительским станциям ассоциаций радиолюбителей (ретрансляторам).]
^.^| CQ1 ^.^| 2–4 знака ^.^| – ^.^| Азорские острова ^.^| {blank}footnote:g2[]
^.^| CQ2 ^.^| 2–4 знака ^.^| – ^.^| Мадейра ^.^| {blank}footnote:g2[]
^.^| CR0 ^.^| 1–4 знака ^.^| – ^.^| Португалия, Мадейра, Азорские острова ^.^| {blank}footnote:g1[Позывные сигналы, присваиваемые любительским станциям организаций по защите населения и оказанию помощи.]
^.^| CR7 ^.^| 3 буквы ^.^| 3 ^.^| Португалия ^.^| –
^.^| CR8 ^.^| 3 буквы ^.^| 3 ^.^| Азорские острова ^.^| –
^.^| CR9 ^.^| 3 буквы ^.^| 3 ^.^| Мадейра ^.^| –
^.^| CS0 ^.^| 3 буквы ^.^| – ^.^| Португалия ^.^| {blank}footnote:g3[Позывные сигналы, присваиваемые любительским станциям ассоциаций радиолюбителей (стациям, не являющимся ретрансляторами).]
^.^| CS1 ^.^| 3 буквы ^.^| – ^.^| Португалия ^.^| {blank}footnote:g3[]
^.^| CS3 ^.^| 1–4 знака ^.^| – ^.^| Мадейра ^.^| {blank}footnote:g3[]
^.^| CS4 ^.^| 1–4 знака ^.^| – ^.^| Азорские острова ^.^| {blank}footnote:g3[]
^.^| CS5 ^.^| 1–4 знака ^.^| – ^.^| Португалия ^.^| {blank}footnote:g3[]
^.^| CS6 ^.^| 3 буквы ^.^| – ^.^| Португалия ^.^| {blank}footnote:g3[]
^.^| CS7 ^.^| 3 буквы ^.^| 2 ^.^| Португалия ^.^| –
^.^| CS8 ^.^| 3 буквы ^.^| 2 ^.^| Азорские острова ^.^| –
^.^| CS9 ^.^| 3 буквы ^.^| 2 ^.^| Мадейра ^.^| –
^.^| CT1 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Португалия ^.^| {blank}footnote:g3[]
^.^| CT2 ^.^| 2 или 3 буквы ^.^| B ^.^| Португалия ^.^| –
^.^| CT3 ^.^| 2 или 3 буквы ^.^| A, B и C ^.^| Мадейра ^.^| –
^.^| CT4 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Португалия ^.^| –
^.^| CT5 ^.^| 3 буквы ^.^| C ^.^| Португалия ^.^| –
^.^| CT6 ^.^| 3 буквы ^.^| – ^.^| Португалия ^.^| {blank}footnote:g3[]
^.^| CT7 ^.^| 3 буквы ^.^| 1 ^.^| Португалия ^.^| –
^.^| CT8 ^.^| 3 буквы ^.^| 1 ^.^| Азорские острова ^.^| –
^.^| CT9 ^.^| 3 буквы ^.^| 1 ^.^| Мадейра ^.^| –
^.^| CU0 ^.^| 3 буквы ^.^| C ^.^| Азорские острова (все острова) ^.^| –
^.^| CU1 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Санта-Мария) ^.^| {blank}footnote:g3[]
^.^| CU2 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Сан-Мигел) ^.^| {blank}footnote:g3[]
^.^| CU3 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Терсейра) ^.^| {blank}footnote:g3[]
^.^| CU4 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Грасиоза) ^.^| {blank}footnote:g3[]
^.^| CU5 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Сан-Жоржи) ^.^| {blank}footnote:g3[]
^.^| CU6 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Пику) ^.^| {blank}footnote:g3[]
^.^| CU7 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Фаял) ^.^| {blank}footnote:g3[]
^.^| CU8 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Флориш) ^.^| {blank}footnote:g3[]
^.^| CU9 ^.^| 2 или 3 буквы ^.^| A и B ^.^| Азорские острова (Корву) ^.^| –

|===


[NOTE] 
====
Для нерегулярно используемых позывных сигналов (например, для соревнований) и экспериментальных станций используются следующие префиксы:

* Португалия: CQ7, CR5, CR6 и CS2; 

* Азорские острова: CQ8, CR1 и CR2; 

* Мадейра: CQ3, CQ9 и CR3.
====

=== Катар (Государство)

Любительские станции:: A71AA−A71ZZ.

Экспериментальные станции:: A73AA−A73ZZ.

=== Румыния

Любительские станции:: 
. станции индивидуального пользования
+
YO, за которыми следуют цифра и группа не более чем из 3 букв (первая из которых не является буквой K)

. станции клубов
+
YO, за которыми следуют цифра и группа не более чем из 3 букв (первая из которых является буквой K).

NOTE: YP, YQ и YR, за которыми следуют цифра и группа не более чем из 3 букв, присваиваются любительским станциям, эксплуатируемым в ходе соревнований или особых событий.

=== Российская Федерация

[%unnumbered]
|===
2+^.^| Любительские и экспериментальные станции
a| RA0AA–RZ9ZZ +
UA0AA–UI9ZZ +
R0AA–R9ZZ {blank}footnote:[При условии использования любительской станции не менее 25 календарных лет.] 

RA0A–RZ9Z {blank}footnote:[При условии участия в течение последних пяти лет не менее чем в десяти международных и всероссийских соревнованиях по беспроводной связи.] 

UA0A–UI9Z | Станции, эксплуатируемые операторами первой квалификационной категории, имеющими свидетельство HAREC
| R0AAA–R9ZZZ +
RA0AAA–RZ9ZZZ +
UA0AAA–UA9ZZZ | Станции, эксплуатируемые операторами второй квалификационной категории, имеющими свидетельство HAREC
| UB0AAA–UD9ZZZ +
UF0AAA–UG9ZZZ | Станции, эксплуатируемые операторами третьей квалификационной категории, имеющими свидетельство ARNEC (лицензия новичка)
| UE0AAA–UE9ZZZ +
UH0AAA–UI9ZZZ | Станции, эксплуатируемые операторами четвертой квалификационной категории (начальный уровень)
| RR0AA–RR9ZZ +
RR0AAA–RR9ZZZ | Ретрансляторы
| RB0AA–RB9ZZ | Радиомаяки
| RS0S–RS9S +
RS10S–RS99S | Станции любительской спутниковой службы
| R0AAAA–R9ZZZZ +
R00AAA–R99ZZZ +
R000A–R999Z +
R000AA–R999ZZ +
R0000A–R9999Z +
RA00A–RZ99Z +
RA00AA–RZ99ZZ +
RA00AAA–RZ99ZZZ +
RA000A–RZ999Z +
RA000AA–RZ999ZZ | Временное использование в особых обстоятельствах
| R0A–R9Z +
R00A–R99Z +
R00AA–R99ZZ {blank}footnote:[За исключением позывных сигналов серий R00SP−R99SP, распределенных исключительно любительским станциям полярных экспедиций, работающим на дрейфующих льдах в Северном Ледовитом океане.] | Станции, участвующие во внутренних этапах соревнований

|===


=== Руандийская Республика

Любительские станции:: 9X5AA−9X5ZZ.

=== Самоа (Независимое Государство)

Любительские станции:: 5W, за которыми следуют цифра и 2 буквы.

=== Сан-Марино (Республика)

Любительские станции:: T72AA−T72ZZ {blank}footnote:[ОВЧ и более высокие частоты.]
+
T77AA−T77ZZ {blank}footnote:h1[Все полосы.]
+
Радиоклуб: T70A {blank}footnote:h1[]
+
Радиоклуб, на временной основе: T71CE {blank}footnote:h1[].


=== Сан-Томе и Принсипи (Демократическая Республика)

Любительские станции:: S92AA−S92ZZ.

=== Саудовская Аравия (Королевство)

Любительские станции и экспериментальные станции:: 7Z, за которыми следуют цифра и 2 буквы.

=== Сенегал (Республика)

Любительские станции:: 6W1AA−6W1ZZ.

Экспериментальные станции:: 6V3AA−6V3ZZ.

=== Сейшельские Острова (Республика)

Любительские станции:: S79AAA−S79ZZZ.

Экспериментальные станции:: S78AA−S78AZ.

=== Сьерра-Леоне

Любительские станции:: 9L, за которыми следуют цифра (0−8, обозначающая район или провинцию, в котором(ой) расположена станция) и 2 буквы.

Цифры, обозначающие районы или провинции:: 0 – Малые суда и прибрежные острова 
+
1 – Западный район 
+
2 – Северная провинция 
+
3 – Южная провинция 
+
4 – Восточная провинция 
+
7 – Лицензия новичка 
+
8 – Лицензия класса B (ОВЧ/УВЧ).

NOTE: Иностранные радиолюбители с временной лицензией должны использовать 9L, за которыми следуют косая черта (/) и их собственный позывной сигнал.

=== Сингапур (Республика)

Любительские станции:: 9V1AA−9V1ZZ.

Экспериментальные станции:: 9V2A−9V2ZZ.

NOTE: 9V0, за которыми следуют 2 или 3 буквы, разрешено использовать любительским станциям в особых случаях.

=== Синт-Мартен (нидерландская часть)

Любительские станции:: PJ7AA−PJ7ZZZ.

=== Словацкая Республика

Любительские станции:: OM0AA−OM8ZZZ 
+
OM0A−OM9Z {blank}footnote:[Для международных соревнований радиолюбителей.]
+
OM9AA−OM9ZZ {blank}footnote:[Для непредвиденных задач и только на период существования этих задач.]
+
OM9AAA−OM9SZZ {blank}footnote:[Для иностранцев, осуществляющих передачу с территории Словацкой Республики.].

Экспериментальные станции:: OM9TAA−OM9ZZZ.

=== Словения (Республика)

Любительские станции:: S5, за которыми следуют цифра и 1, 2 или 3 буквы.

=== Соломоновы Острова

Любительские станции и экспериментальные станции:: H44AA−H44ZZ.

=== Южно-Африканская Республика

Любительские станции:: ZR {blank}footnote:[Полная лицензия, за исключением ОВЧ.], ZS {blank}footnote:[Полная лицензия.] или ZU {blank}footnote:[Лицензия новичка.], за которыми следуют цифра (обозначающая провинцию, в которой расположена станция) и 1, 2 или 3 буквы, характеризующие радиолюбителя.

Цифры, обозначающие провинции:: 1 – Западная Капская провинция 
+
2 – Восточная Капская провинция 
+
3 – Северная Капская провинция 
+
4 – Свободное государство 
+
5 – Квазулу-Натал 
+
6 – Гаутенг, Северо-Западная провинция, Мпумаланга, Северная провинция 
+
7 – Антарктическая программа SANAE 
+
8 – остров Марион 
+
9 – Намибия 
+
0 – цифровые ретрансляторы и электронные доски объявлений.

Экспериментальные станции:: ZT, за которыми следуют цифра и 1, 2 или 3 буквы.

=== Испания

Любительские станции:: Одна из групп EA, EB или EC, за которыми следуют цифра (обозначающая провинцию, в которой расположена фиксированная станция или в которой проживает владелец лицензии на подвижную станцию) и группа не более чем из 3 букв.
+
Вторая буква в группах EA, EB и EC обозначает, что станции являются станциями класса A, B или C, соответственно.

Временные позывные сигналы:: Группы ED, EE и EF используются вместо EA, EB и EC; при этом вторая буква D, E или F означает то же, что и буквы A, B и C (класс лицензии).

=== Шри-Ланка (Демократическая Социалистическая Республика)

Любительские станции:: 4S5, за которыми следуют 2 или 3 буквы – класс B новичка (только ОВЧ) 
+
4S6, за которыми следуют 2 или 3 буквы – класс A новичка 
+
4S7, за которыми следуют 2 или 3 буквы – общий/высокий класс.

Экспериментальные станции:: 4P3, за которыми следуют 2 буквы.

[NOTE]
====
. Местные радиолюбители, получившие лицензию путем представления лицензий, выданных иностранными администрациями, используют 4S7, за которыми следуют 3 буквы, при этом последней является буква R.

. Гостевые радиолюбители используют 4S7, за которыми следует национальный позывной сигнал.

. Иностранные радиолюбители из администраций, имеющих соглашение на основе взаимности, используют 4S7, за которыми следуют 3 буквы, при этом последней является буква G.
====

=== Суринам (Республика)

Любительские станции и экспериментальные станции:: PZ, за которыми следуют цифра (2−9) и группа не более чем из 3 букв.

=== Свазиленд (Королевство)

Любительские станции:: 3DA0, за которыми следуют 2 буквы  –  Полная лицензия 
+
3DA1, за которыми следуют 2 буквы  –  Ограниченная лицензия.

=== Швеция

Любительские станции:: SA, SI, SJ, SK, SL или SM (в исключительных случаях 7S или 8S), за которыми следуют цифра и 1, 2 или 3 буквы 
+
SH, за которыми следуют цифра и 3 буквы.

=== Швейцарская Конфедерация‎

Любительские станции:: HB9 или HB3 {blank}footnote:[Лицензия новичка.], за которыми следуют 4 знака, последний из которых должен быть буквой.

=== Сирийская Арабская Республика

Любительские станции и экспериментальные станции:: YK, за которыми следуют цифра (обозначающая зону, в которой расположена станция) и 1, 2 или 3 буквы.

Цифры, обозначающие зоны:: 1 – Южный регион
+
2 – Северный регион
+
3 – Восточный регион
+
4 – Западный регион
+
8 – Маяки
+
9 – Группы иностранных радиолюбителей
+
0 – Станции клубов.

[NOTE]
====
. Иностранные радиолюбители – частные лица используют YK, за которыми следуют косая черта (/) и их национальный позывной сигнал.

. Только для особых событий радиолюбители используют 6C, за которыми следуют цифра и группа не более чем из 3 букв.
====

=== Танзания (Объединенная Республика)

Любительские станции:: 5H3AA−5H3ZZ  –  Основная территория 
+
5H1AA−5H1ZZ  –  Занзибар.

=== Таиланд

Любительские станции:: E2 или HS, за которыми следуют цифра (обозначающая район, в котором расположена станция) и 2 или 3 буквы.

Цифры, обозначающие районы:: 0, 1 – Бангкок, Самутпракан, Патхумтхани, Нонтхабури, Пхранакхонсиаюттхая, Ангтхонг, Сарабури, Лопбури, Сингбури, Чайнат
+
2 – Чонбури, Районг, Чантхабури, Трат, Чаченгсао, Накхоннайок, Прачинбури, Сакэу
+
3 – Накхонратчасима, Чайяпхум, Бурирам, Сурин, Сисакет, Убонратчатхани, Ясотхон, Амнатчарен
+
4 – Кхонкэн, Лей, Нонгкхай, Удонтхани, Махасаракхам, Каласин, Саконнакхон, Мукдахан, Накхонпханом, Ройет, Нонгбуалампху
+
5 – Мэхонгсон, Чиангмай, Лампхун, Лампанг, Пхрэ, Уттарадит, Нан, Чианграй, Пхаяу
+
6 – Накхонсаван, Утхайтхани, Кампхэнгпхет, Так, Пхичит, Сукхотхай, Пхитсанулок, Пхетчабун
+
7 – Ратчабури, Самутсокхон, Самутсонгкхрам, Накхонпатхом, Супханбури, Канчанабури, Пхетчабури, Прачуапкхирикхан
+
8 – Накхонситхаммарат, Краби, Пхангнга, Ранонг, Сураттхани, Чумпхон, Пхукет
+
9 – Сонгкхла, Паттани, Яла, Наратхиват, Транг, Пхаттхалунг, Сатун.

Экспериментальные станции:: E22AAA−E22AZZ.

=== Тонга (Королевство)

Любительские станции:: A35, за которыми следуют 2 буквы.

Экспериментальные станции:: A35, за которыми следуют 3 буквы, первая из которых должна быть буквой X.

=== Тринидад и Тобаго

Любительские станции и экспериментальные станции:: 9Y4AA−9Y4ZZ.

=== Тунис

Любительские станции:: 3V8AA−3V8ZZ.

Экспериментальные станции:: TS8AA−TS8ZZ.

=== Турция

Любительские станции:: TA, за которыми следуют цифра и группа не более чем из 3 букв.

=== Тувалу

Любительские станции:: T20AA−T29ZZ.

Экспериментальные станции:: T22AA−T29ZZ.

=== Уганда (Республика)

Любительские станции:: 5X5AA−5X5ZZ.

=== Украина

Любительские станции и экспериментальные станции:: UR, US, UT, UU, UV, UW, UX, UY, UZ, EM, EN или EO, за которыми следуют цифра (0−9) и 2 или 3 буквы.

=== Объединенные Арабские Эмираты

Любительские станции:: A61, за которыми следует группа не более чем из 3 букв.

Экспериментальные станции:: A62, за которыми следует группа не более чем из 3 букв.

=== Соединенное Королевство Великобритании и Северной Ирландии

[%unnumbered]
|===
2+^.^| Любительские и экспериментальные станции
^.^| _Тип лицензии_ ^.^| _Форма позывных сигналов_
.2+| Полная лицензия/расширенная лицензия/лицензия клуба {blank}footnote:i1[В случае если адрес основной станции владельца лицензии или адрес специальной станции для соревнований относится к перечисленным ниже территориям, и эксплуатация осуществляется по этому адресу, то в позывной сигнал вносится поправка путем вставки буквы после первого знака позывных сигналов, указанных в таблице, выше, в соответствии с определенным ниже перечнем:

Отсутствует – Англия 

U – остров Гернси 

D – остров Мэн 

J – остров Джерси 

I – Северная Ирландия 

M – Шотландия 

W – Уэльс.], {blank}footnote:[В случае если позывной сигнал клуба присвоен на перечисленных ниже территориях, то в позывной сигнал вносится поправка путем вставки буквы после первого знака позывных сигналов, указанных в таблице, выше, в соответствии с определенным ниже перечнем:

X – Англия 

P – остров Гернси 

T – остров Мэн 

H – остров Джерси 

N – Северная Ирландия 

S – Шотландия 

C – Уэльс. ] | G, за которым следуют цифра (0−8) и 2 или 3 буквы
| M, за которым следуют цифра (0, 1, 5) и 3 буквы
| Промежуточная лицензия {blank}footnote:[В случае если адрес основной станции владельца лицензии относится к территориям, перечисленным в примечании 1), и эксплуатация осуществляется по этому адресу, то в позывной сигнал вносится поправка путем замены второго знака позывных сигналов, указанных в таблице, выше, в соответствии с определенным в примечании 1) перечнем, с учетом отсутствия замены в случае расположения в Англии.] | 2E, за которыми следуют цифра (0, 1) и 3 буквы
| Базовая лицензия {blank}footnote:i1[] | M3, за которыми следуют 3 буквы
| Ретрансляционные станции | GB3, за которыми следуют 2 буквы
| Станции маяков | GB3, за которыми следуют 3 буквы
| Узловые станции пакетной передачи данных | GB7, за которыми следуют 2 буквы
| Станции пакетной передачи данных электронной почты | GB7, за которыми следуют 3 буквы
| Шлюзовые станции автоматической системы сообщения о местонахождении | MB7U, за которыми следуют 2 буквы
| Симплексные (необслуживаемые) станции шлюзов доступа в интернет | MB7I, за которыми следуют 2 буквы
| Стации для особых событий (временная лицензия) | GB, за которыми следуют цифра (0−2, 4−6, 8) и 2 или 3 буквы
| Специальная – станции для особых событий (временная лицензия) | GB, за которыми следуют 2 или 3 цифры (0−9) и 2 или 3 буквы
| Специальные станции для соревнований (временная лицензия) a| G, за которым следуют цифра (0−9) и буква +
M, за которым следуют цифра (0−9) и буква
^.^| _Заморские территории_ ^.^| _Форма позывных сигналов_
| Остров Ангилья | VP2E, за которыми следуют 2 буквы
| Остров Монтсеррат | VP2M, за которыми следуют 2 буквы
| Британские Виргинские Острова | VP2V, за которыми следуют 2 буквы
| Острова Теркс и Кайкос | VP5, за которыми следуют 3 буквы
| Остров Питкэрн и зависимые территории (Острова Хенденрсон, Дюси и Оэно) | VP6, за которыми следуют 3 буквы
| Фолклендские (Мальвинские) острова и зависимые территории (Южная Георгия, Южные Сандвичевы острова) Антарктические территории
| VP8, за которыми следуют 3 буквы  –  Полная лицензия +
VP8, за которыми следуют 4 буквы  –  Специальная лицензия (144−146 МГц только для национального использования, без рассмотрения)
| Бермудские острова | VP9, за которыми следуют 3 буквы
| Острова Теркс и Кайкос | VQ5, за которыми следуют 3 буквы
| Каймановы острова | VQ6, за которыми следуют 3 буквы
| Британская территория в Индийском океане (BIOT) (Остров Диего-Гарсия и архипелаг Чагос) | VQ9, за которыми следуют 3 буквы
| Гибралтар | ZB0, ZB2 или ZB3, за которыми следуют 3 буквы
| Военные базы Соединенного Королевства на Кипре (Акротири и Декелия) | ZC4, за которыми следуют 3 буквы
| Остров Святой Елены | ZD7, за которыми следуют 1–3 буквы
| Остров Вознесения | ZD8, за которыми следуют 1–3 буквы
| Тристан-да-Кунья и остров Гоф | ZD9, за которыми следуют 1–3 буквы
| Каймановы острова – Большой Кайман | ZF1 или ZF2, за которыми следуют 3 буквы
| Каймановы острова – Малый Кайман | ZF8, за которыми следуют 3 буквы
| Каймановы острова – Кайман-Брак | ZF9, за которыми следуют 3 буквы

|===


=== Соединенные Штаты Америки

[%unnumbered]
|===
2+^.^| Любительские станции
| K0A−K9Z +
N0A−N9Z +
W0A−W9Z | За исключением буквы X после цифры
| K0AA−K9ZZZ +
N0AA−N9ZZZ +
W0AA−W9ZZZ .2+| 
| AA0A−AL9ZZ +
KA0A−KZ9ZZ +
NA0A−NZ9ZZ +
WA0A−WZ9ZZ
| KA0AAA−KZ9ZZZ +
WA0AAA−WZ9ZZZ | За исключением буквы X после цифры
2+^.^| Экспериментальные станции
| AA2XAA−AE9XZZ +
AL2XAA−AL9XZZ +
KA2XAA−KZ9XZZ +
WA2XAA−WZ9XZZ | 

|===

=== Уругвай (Восточная Республика)

Любительские станции:: CX, за которыми следуют цифра (1−9) и группа не более чем из 3 букв, первая из которых обозначает департамент, в котором расположена станция.

Экспериментальные станции:: CV, CW или CX, за которыми следуют цифра (1−9) и группа не более чем из 3 букв.

=== Вануату (Республика)

Любительские станции:: YJ8, за которыми следуют 2 буквы (как правило, инициалы лицензированного радиолюбителя) 
+
YJ8N {blank}footnote:[Для любительских станций, эксплуатируемых новичками.], за которыми следуют 2 буквы 
+
YJ8V {blank}footnote:[Для любительских станций владельцев ограниченных лицензий (ОВЧ).], за которыми следуют 2 буквы.


=== Государство-город Ватикан‎

Любительские станции:: HV, за которыми следуют цифра и 2 буквы.

=== Венесуэла (Боливарианская Республика)

Любительские станции:: YV, YX или 4M, за которыми следуют цифра и 3 буквы.

=== Вьетнам (Социалистическая Республика)

Любительские станции:: XV или 3W, за которыми следуют цифра (2−9, обозначающая район, в котором расположена станция) и 1–4 буквы.

=== Замбия (Республика)

Любительские станции:: 9J2, за которыми следуют 2 знака, последний из которых должен быть буквой.

=== Зимбабве (Республика)

Любительские станции:: Z21AA−Z29ZZ.

<<<

== ПОПРАВКИ

[%unnumbered]
|===
^.^h| Поправка № ^.^h| Оперативный бюллетень № ^.^h| Администрация
^.^| 1 | | 
^.^| 2 | | 
^.^| 3 | | 
^.^| 4 | | 
^.^| 5 | | 
^.^| 6 | | 
^.^| 7 | | 
^.^| 8 | | 
^.^| 9 | | 
^.^| 10 | | 
^.^| 11 | | 
^.^| 12 | | 
^.^| 13 | | 
^.^| 14 | | 
^.^| 15 | | 
^.^| 16 | | 
^.^| 17 | | 
^.^| 18 | | 
^.^| 19 | | 
^.^| 20 | | 
^.^| 21 | | 
^.^| 22 | | 
^.^| 23 | | 
^.^| 24 | | 
^.^| 25 | | 
^.^| 26 | | 
^.^| 27 | | 
^.^| 28 | | 
^.^| 29 | | 
^.^| 30 | | 

|===

