= FORM OF CALL SIGNS ASSIGNED BY EACH ADMINISTRATION TO ITS AMATEUR AND EXPERIMENTAL STATIONS
:bureau: T
:docnumber: 1154
:series: STATUS OF RADIOCOMMUNICATIONS BETWEEN AMATEUR STATIONS OF DIFFERENT COUNTRIES
:series1: (In accordance with optional provision No. 25.1 of the Radio Regulations)
:series2: AND
:published-date: 2018-08-15
:status: published
:doctype: service-publication
:keywords:
:imagesdir: images
:docfile: T-SP-RR.25.1-2018-MSW-E.adoc
:mn-document-class: itu
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:


[preface]
== Note from the BR

In the Circular Letter CR/430 of 14 May 2018, the Radiocommunication Bureau requested administrations to advise the Union on their current position with respect to provision No. 25.1 of the Radio Regulations, concerning radiocommunications between stations of their Amateur Service and Amateur-Satellite Service and those of different countries. The Circular Letter also stated that in cases where no information was received from an administration, it shall be assumed that the concerned administration has no objection to such radiocommunications.

In the same Circular Letter, administrations were requested further to advise the Bureau of the form of call signs they assigned their amateur and experimental stations.

This Annex to the Operational Bulletin No. 1154 dated 15 August 2018 cancels and supersedes the previous Annex to the Operational Bulletin No. 1055 dated 1 July 2014. The Annex takes into account information received from administrations with respect to provision No. 25.1 of the Radio Regulations. As it concerns the form of call signs assigned to amateur and experimental stations, where no new information has been received from an administration, information currently held in the relevant registries of the Bureau is reproduced.

This Annex will be updated by numbered series of amendments published in the ITU Operational Bulletin. Furthermore, the information contained in this Annex is also available on the ITU home page http://www.itu.int/pub/T-SP/e[http://www.itu.int/pub/T-SP/e] and can be consulted by subscribers by remote access.

Administrations are requested to check the accuracy of the information published herein and to inform the Union of any discrepancies. Changes to the information provided should be notified to the Bureau as soon as possible.

International Telecommunication Union

The Director of the Radiocommunication Bureau

Place des Nations

1211 GENEVA 20

Switzerland

Tel: + 41 22 730 5800

Fax: + 41 22 730 5785

E-mail: brmail@itu.int


NOTE: Nothing in the manner of presentation of information in this Annex or in the arrangement of data implies endorsement or acceptance by ITU in matters affecting the status and boundaries of States and territories.


== RADIOCOMMUNICATIONS BETWEEN AMATEUR STATIONS (RR 25.1)

[%unnumbered]
|===
.2+^.^| Administration of the country or geographical area 2+^.^| BETWEEN STATIONS OF DIFFERENT COUNTRIES .2+^.^| Remarks and restrictions imposed ^.^a| Form of call signs
^.^| Permitted ^.^| Forbidden ^.^| Pages

^.^| 1 ^.^| 2 ^.^| 3 ^.^| 4 ^.^| 5

| Afghanistan ^.^| x | | {blank}footnote:table1[This administration has not explicitly given its position. In terms of the consultation procedure, it is assumed that this administration has no objections to radiocommunications between amateur stations of its country and stations of other countries (see Circular Letter CR/430 of 14 May 2018).] |
| Alaska (State of) ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Albania (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Algeria (People's Democratic Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 11
| American Samoa ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Andorra (Principality of) ^.^| x | | {blank}footnote:table1[] |
| Angola (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Anguilla ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Antigua and Barbuda ^.^| x | | {blank}footnote:table1[] |
| Argentine Republic ^.^| x | | {blank}footnote:table1[] ^.^| 11
| Armenia (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Aruba ^.^| x | | {blank}footnote:table1[] ^.^| 11
| Ascension Island ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Australia ^.^| x | | ^.^| 11-12
| Austria ^.^| x | | {blank}footnote:table1[] ^.^| 12
| Azerbaijan (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Azores ^.^| x | | {blank}footnote:table1[] ^.^| 35-36
| Bahamas (Commonwealth of the) ^.^| x | | {blank}footnote:table1[] ^.^| 12
| Bahrain (Kingdom of) ^.^| x | | {blank}footnote:table1[] ^.^| 12
| Bangladesh (People's Republic of) ^.^| x | | {blank}footnote:table1[] |
| Barbados ^.^| x | | {blank}footnote:table1[] ^.^| 13
| Belarus (Republic of) ^.^| x | | ^.^| 13
| Belgium ^.^| x | | {blank}footnote:table1[] ^.^| 13-14
| Belize ^.^| x | | {blank}footnote:table1[] ^.^| 14
| Benin (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 14
| Bermuda ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Bhutan (Kingdom of) ^.^| x | | {blank}footnote:table1[] ^.^| 14
| Bolivia (Plurinational State of) ^.^| x | | {blank}footnote:table1[] ^.^| 14
| Bonaire, Sint Eustatius and Saba ^.^| x | | {blank}footnote:table1[] ^.^| 14
| Bosnia and Herzegovina ^.^| x | | {blank}footnote:table1[] |
| Botswana (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 14
| Bouvet Island ^.^| x | | {blank}footnote:table1[] ^.^| 33
| Brazil (Federative Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 15-16
| British Virgin Islands ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Brunei Darussalam ^.^| x | | {blank}footnote:table1[] ^.^| 16
| Bulgaria (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 16
| Burkina Faso ^.^| x | | {blank}footnote:table1[] ^.^| 16
| Burundi (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 16
| Cabo Verde (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 16
| Cambodia (Kingdom of)) ^.^| x | | {blank}footnote:table1[] |
| Cameroon (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 16
| Canada ^.^| x | | {blank}footnote:table1[] ^.^| 16-17
| Canary Islands ^.^| x | | {blank}footnote:table1[] ^.^| 39
| Cayman Islands ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Central African Republic ^.^| x | | {blank}footnote:table1[] ^.^| 17
| Chad (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 17
| Chagos Islands (Indian Ocean) ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Chile ^.^| x | | {blank}footnote:table1[] ^.^| 17
| China (People's Republic of) ^.^| x | | {blank}footnote:table1[] |
| Christmas Island (Indian Ocean) ^.^| x | | ^.^| 11-12
| Clipperton Island ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Cocos (Keeling) Islands ^.^| x | | ^.^| 11-12
| Colombia (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 17
| Comoros (Union of the) ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Congo (Republic of the) ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Cook Islands ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Costa Rica ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Côte d'Ivoire (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Croatia (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Crozet Archipelago ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Cuba ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Curaçao ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Cyprus (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 18
| Czech Republic ^.^| x | | {blank}footnote:table1[] ^.^| 19
| Democratic People's Republic of Korea | ^.^| x | {blank}footnote:table1[] |
| Democratic Republic of the Congo ^.^| x | | {blank}footnote:table1[] |
| Denmark ^.^| x | | {blank}footnote:table1[] ^.^| 19
| Diego Garcia ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Djibouti (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 19
| Dominica (Commonwealth of) ^.^| x | | {blank}footnote:table1[] ^.^| 19
| Dominican Republic ^.^| x | | {blank}footnote:table1[] ^.^| 19
| Easter Island ^.^| x | | {blank}footnote:table1[] ^.^| 17
| Ecuador ^.^| x | | {blank}footnote:table1[] ^.^| 19-20
| Egypt (Arab Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 20
| El Salvador (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 20
| Equatorial Guinea (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Eritrea | ^.^| x | {blank}footnote:table1[] |
| Estonia (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 20
| Ethiopia (Federal Democratic Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Falkland Islands (Malvinas) ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Faroe Islands ^.^| x | | {blank}footnote:table1[] ^.^| 19
| Fiji (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Finland ^.^| x | | {blank}footnote:table1[] ^.^| 21
| France ^.^| x | | {blank}footnote:table1[] ^.^| 21
| French Polynesia ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Gabonese Republic ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Gambia (Republic of the) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Georgia ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Germany (Federal Republic of) ^.^| x | | ^.^| 22
| Ghana ^.^| x | | {blank}footnote:table1[] ^.^| 23
| Gibraltar ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Greece ^.^| x | | {blank}footnote:table1[] ^.^| 23
| Greenland ^.^| x | | {blank}footnote:table1[] ^.^| 19
| Grenada ^.^| x | | {blank}footnote:table1[] |
| Guadeloupe (French Department of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Guam ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Guatemala (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 23
| Guiana (French Department of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Guinea (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 23
| Guinea-Bissau (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 23
| Guyana ^.^| x | | {blank}footnote:table1[] ^.^| 24
| Haiti (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 24
| Hawaii (State of) ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Heard and McDonald Islands ^.^| x | | ^.^| 11-12
| Honduras (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 24
| Hong Kong (Special Administrative Region of China) ^.^| x | | {blank}footnote:table1[] |
| Howland Island ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Hungary ^.^| x | | {blank}footnote:table1[] ^.^| 24
| Iceland ^.^| x | | {blank}footnote:table1[] ^.^| 24
| India (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 24
| Indonesia (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 24
| Iran (Islamic Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 25
| Iraq (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 25
| Ireland ^.^| x | | {blank}footnote:table1[] ^.^| 25
| Israel (State of) ^.^| x | | {blank}footnote:table1[] ^.^| 25
| Italy ^.^| x | | {blank}footnote:table1[] ^.^| 25-26
| Jamaica ^.^| x | | {blank}footnote:table1[] ^.^| 26
| Japan ^.^| x | | {blank}footnote:table1[] ^.^| 26
| Jarvis Island ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Johnston Island ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Jordan (Hashemite Kingdom of) ^.^| x | | {blank}footnote:table1[] ^.^| 26
| Kazakhstan (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Kenya (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 26
| Kerguelen Islands ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Kiribati (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 27
| Korea (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 27
| Kuwait (State of) ^.^| x | | {blank}footnote:table1[] ^.^| 27
| Kyrgyz Republic ^.^| x | | {blank}footnote:table1[] ^.^| 27
| Lao People's Democratic Republic ^.^| x | | {blank}footnote:table1[] ^.^| 27
| Latvia (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 27
| Lebanon ^.^| x | | Except Israel ^.^| 27
| Lesotho (Kingdom of) ^.^| x | | {blank}footnote:table1[] ^.^| 27
| Liberia (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Libya ^.^| x | | {blank}footnote:table1[] ^.^| 28
| Liechtenstein (Principality of) ^.^| x | | {blank}footnote:table1[] ^.^| 28
| Lithuania (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 28
| Luxembourg ^.^| x | | {blank}footnote:table1[] ^.^| 28
| Macao (Special Administrative Region of China) ^.^| x | | {blank}footnote:table1[] |
| Madagascar (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 28
| Madeira ^.^| x | | {blank}footnote:table1[] ^.^| 35
| Malawi ^.^| x | | {blank}footnote:table1[] ^.^| 28
| Malaysia ^.^| x | | {blank}footnote:table1[] ^.^| 29
| Maldives (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 29
| Mali (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Malta ^.^| x | | {blank}footnote:table1[] ^.^| 29
| Marion Island ^.^| x | | {blank}footnote:table1[] ^.^| 39
| Marshall Islands (Republic of the) ^.^| x | | {blank}footnote:table1[] |
| Martinique (French Department of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Mauritania (Islamic Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 29
| Mauritius (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 29
| Mayotte (Territorial Collectivity of). ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Mexico ^.^| x | | {blank}footnote:table1[] ^.^| 30
| Micronesia (Federated States of) ^.^| x | | {blank}footnote:table1[] ^.^| 30
| Midway Islands ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Moldova (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 30-31
| Monaco (Principality of) ^.^| x | | {blank}footnote:table1[] ^.^| 31
| Mongolia ^.^| x | | {blank}footnote:table1[] |
| Montenegro ^.^| x | | {blank}footnote:table1[] |
| Montserrat ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Morocco (Kingdom of) ^.^| x | | {blank}footnote:table1[] ^.^| 31
| Mozambique (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 31
| Myanmar (Union of) ^.^| x | | {blank}footnote:table1[] ^.^| 31
| Namibia (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 31
| Nauru (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 31
| Nepal (Federal Democratic Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 31
| Netherlands (Kingdom of the) ^.^| x | | {blank}footnote:table1[] ^.^| 31
| New Caledonia ^.^| x | | {blank}footnote:table1[] ^.^| 21
| New Zealand ^.^| x | | {blank}footnote:table1[] ^.^| 32
| Nicaragua ^.^| x | | {blank}footnote:table1[] ^.^| 32
| Niger (Republic of the) ^.^| x | | {blank}footnote:table1[] ^.^| 33
| Nigeria (Federal Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 33
| Niue ^.^| x | | {blank}footnote:table1[] ^.^| 33
| Norfolk Island ^.^| x | | ^.^| 11-12
| Northern Mariana Island (Commonwealth of the) ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Norway ^.^| x | | {blank}footnote:table1[] ^.^| 33
| Oman (Sultanate of) ^.^| x | | {blank}footnote:table1[] ^.^| 33
| Pakistan (Islamic Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 33
| Palau (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Palmyra Island ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Panama (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Papua New Guinea ^.^| x | | {blank}footnote:table1[] ^.^| 34
| Paraguay (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 34
| Peru ^.^| x | | {blank}footnote:table1[] ^.^| 34
| Philippines (Republic of the) ^.^| x | | {blank}footnote:table1[] ^.^| 34
| Phoenix Islands ^.^| x | | {blank}footnote:table1[] ^.^| 27
| Pitcairn Island ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Poland (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 34-35
| Portugal ^.^| x | | {blank}footnote:table1[] ^.^| 35-36
| Puerto Rico ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Qatar (State of) ^.^| x | | {blank}footnote:table1[] ^.^| 36
| Reunion (French Department of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Rodrigues ^.^| x | | {blank}footnote:table1[] ^.^| 29
| Romania ^.^| x | | {blank}footnote:table1[] ^.^| 36
| Russian Federation ^.^| x | | {blank}footnote:table1[] ^.^| 36-37
| Rwanda (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 37
| Saint Barthélemy (French Department of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Saint Helena ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Saint Kitts and Nevis (Federation of ) ^.^| x | | {blank}footnote:table1[] |
| Saint Lucia ^.^| x | | {blank}footnote:table1[] |
| Saint Martin (French Department of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Saint Paul and Amsterdam Islands ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Saint Pierre and Miquelon (Territorial Collectivity of) ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Saint Vincent and the Grenadines ^.^| x | | {blank}footnote:table1[] |
| Samoa (Independent State of) ^.^| x | | {blank}footnote:table1[] ^.^| 37
| San Marino (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 37
| Sao Tome and Principe (Democratic Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 37
| Saudi Arabia (Kingdom of) ^.^| x | | {blank}footnote:table1[] ^.^| 37
| Senegal (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 38
| Serbia (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Seychelles (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 38
| Sierra Leone ^.^| x | | {blank}footnote:table1[] ^.^| 38
| Singapore (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 38
| Sint Maarten (Dutch part) ^.^| x | | {blank}footnote:table1[] ^.^| 38
| Slovak Republic ^.^| x | | {blank}footnote:table1[] ^.^| 38
| Slovenia (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 38
| Solomon Islands ^.^| x | | {blank}footnote:table1[] ^.^| 38
| Somalia (Federal Republic of) ^.^| x | | {blank}footnote:table1[] |
| South Africa (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 39
| South Soudan (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Spain ^.^| x | | {blank}footnote:table1[] ^.^| 39
| Sri Lanka (Democratic Socialist Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 39
| Sudan (Republic of the) ^.^| x | | {blank}footnote:table1[] |
| Suriname (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 39
| Swan Islands ^.^| x | | {blank}footnote:table1[] ^.^| 24
| Swaziland (Kingdom of) ^.^| x | | {blank}footnote:table1[] ^.^| 39
| Sweden ^.^| x | | {blank}footnote:table1[] ^.^| 39
| Switzerland (Confederation of) ^.^| x | | {blank}footnote:table1[] ^.^| 40
| Syrian Arab Republic ^.^| x | | Except Israel ^.^| 40
| Tajikistan (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Tanzania (United Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 40
| Thailand ^.^| x | | {blank}footnote:table1[] ^.^| 40
| The Former Yugoslav Republic of Macedonia ^.^| x | | {blank}footnote:table1[] |
| Timor-Leste (Democratic Republic of) ^.^| x | | {blank}footnote:table1[] |
| Togolese Republic ^.^| x | | {blank}footnote:table1[] |
| Tokelau ^.^| x | | {blank}footnote:table1[] ^.^| 32
| Tonga (Kingdom of) ^.^| x | | {blank}footnote:table1[] ^.^| 40
| Trinidad and Tobago ^.^| x | | {blank}footnote:table1[] ^.^| 40
| Tristan da Cunha ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Tunisia ^.^| x | | {blank}footnote:table1[] ^.^| 41
| Turkey ^.^| x | | {blank}footnote:table1[] ^.^| 41
| Turkmenistan ^.^| x | | {blank}footnote:table1[] |
| Turks and Caicos Islands ^.^| x | | {blank}footnote:table1[] ^.^| 42
| Tuvalu ^.^| x | | {blank}footnote:table1[] ^.^| 41
| Uganda (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 41
| Ukraine ^.^| x | | {blank}footnote:table1[] ^.^| 41
| United Arab Emirates ^.^| x | | {blank}footnote:table1[] ^.^| 41
| United Kingdom of Great Britain and Northern Ireland ^.^| x | | {blank}footnote:table1[] ^.^| 41-42
| United States of America ^.^| x | | {blank}footnote:table1[] ^.^| 43
| United States Virgin Islands ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Uruguay (Eastern Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Uzbekistan (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Vanuatu (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Vatican City State ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Venezuela (Bolivarian Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Viet Nam (Socialist Republic of) ^.^| x |
| Except between amateur-satellite service stations ^.^| 43
| Wake Island ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Wallis and Futuna Islands ^.^| x | | {blank}footnote:table1[] ^.^| 21
| Yemen (Republic of) ^.^| x | | {blank}footnote:table1[] |
| Zambia (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 43
| Zimbabwe (Republic of) ^.^| x | | {blank}footnote:table1[] ^.^| 43

|===



== FORM OF CALL SIGNS ASSIGNED BY EACH ADMINISTRATION TO ITS AMATEUR AND EXPERIMENTAL STATIONS


=== Algeria (People's Democratic Republic of)

Amateur stations:: 7X0, 7X2, 7X3, 7X4 and 7X5 followed by 2 or 3 letters

Experimental stations:: 7X6 and 7X7 followed by 2 or 3 letters

=== Argentine Republic

Amateur stations:: AY, AZ, LU, LW followed by a digit (0-9) and by 2 or 3 letters, the first indicating the province in which the station is situated

Letters indicating the provinces:: A-B and C - Federal Capital
+
D-E - Province of Buenos Aires
+
F - Province of Santa Fé
+
GA–GOZ - Province of Chaco
+
GP–GZZ - Province of Formosa
+
H - Province of Córdoba
+
I - Province of Misiones
+
J - Province of Entre Ríos
+
K - Province of Tucumán
+
L - Province of Corrientes
+
M - Province of Mendoza
+
N - Province of Santiago del Estero
+
O - Province of Salta
+
P - Province of San Juan
+
Q - Province of San Luis
+
R - Province of Catamarca
+
S - Province of La Rioja
+
T - Province of Jujuy
+
U - Province of La Pampa
+
V - Province of Rio Negro
+
W - Province of Chubut
+
XA–XOZ - Province of Santa Cruz
+
XP–XZZ - Province of Tierra del Fuego, Antarctic and Islands of South Atlantic
+
Y - Neuquén
+
Z - Antarctic

NOTE: The beginners have to use the prefix AZ.

=== Aruba

Amateur stations:: P43 or P49 followed by a group of not more than 3 letters

[NOTE]
====
. Foreign amateurs will use the call sign assigned to them by their administration followed by a stroke (/) and then P4 for a duration of one year.

. The prefix P40 or P41 followed by a group of not more than 3 letters is assigned during special events for not more than one month.
====

=== Australia

Amateur stations:: VK, AX {blank}footnote:australia[For occasions of special national or state/local significance.] or VI {blank}footnote:australia[]
followed by a digit (indicating the state or territory in which the station is situated) and by 2, 3 or 4 letters.
+
For call signs with suffixes of 3 or 4 letters, the first letter indicates the licence category.
+
"Advanced" amateur stations are indicated by call signs with suffixes of 2 letters and suffixes of 3 letters where the first letter is A, B, C, D, E, F, G, I, J, K, S, T, U, W, X, Y or Z.
+
"Standard" amateur stations are indicated by call signs with suffixes of 3 letters where the first letter is H, L, M, N, P or V.
+
"Foundation" amateur stations are indicated by call signs with suffixes of 4 letters where the first letter is F.

Experimental stations:: AX followed by a digit (2-9) and by 3 letters, the first one indicating the state or territory in which the station is situated.

[%unnumbered]
|===
.2+^.^a| Station 10+^.^a| State or territory

^.^a| Australian Capital Territory ^.^a| New South Wales ^.^a| Victoria ^.^a| Queensland ^.^a| South Australia ^.^a| Western Australia ^.^a| Tasmania ^.^a| Northern Territory ^.^a| Australian External Territories ^.^a| Antarctic

| Amateur ^.^| 1 ^.^| 2 ^.^| 3 ^.^| 4 ^.^| 5 ^.^| 6 ^.^| 7 ^.^| 8 ^.^| 9 ^.^| –

| Experimental ^.^| A ^.^| N ^.^| V ^.^| Q ^.^| S ^.^| W ^.^| T ^.^| D ^.^| – ^.^| –
|===

=== Austria

Amateur stations:: OE followed by a digit (0-9, indicating the province or the area in which the station is situated) and by 2 or 3 letters

Experimental stations:: OE followed by a digit (2-9, indicating the province in which the station is situated) and by 2 letters (QA-QZ)

Digits indicating the provinces or areas:: 1 - Vienna (amateur stations only)
+
2 - Salzburg
+
3 - Vienna (experimental stations only) and Lower Austria
+
4 - Burgenland
+
5 - Upper Austria
+
6 - Styria
+
7 - Tyrol
+
8 - Carinthia
+
9 - Vorarlberg
+
0 - extraterritorial
+
» - on board ships or on board aircraft


=== Bahamas (Commonwealth of the)

Amateur stations and experimental stations:: C62AA-C69ZZ

=== Bahrain (Kingdom of)

Amateur stations:: A9 followed by a digit (0 to 9) followed by 2, 3 or 4 characters, the last of which shall be a letter.

[%unnumbered]
|===
^.^h| Prefix ^.^h| Digit ^.^h| Suffix
^.^| A9 ^.^| 0-9 ^.^| Up to 4 characters, the last of which shall be a letter
|===


=== Barbados

Amateur stations:: 8P6AA-8P6ZZ {blank}footnote:[For national radio amateurs.]
+
8P9AA-8P9ZZ {blank}footnote:[For foreign radio amateurs, visitors and short-term licence holders.]

=== Belarus (Republic of)

Amateur stations:: EU, EV, or EW, followed by a digit (1-4, 6-8 indicating the city or region (oblast) where the station is located) and one, two or three letters.

Numbers indicating city or region:: 1) City of Minsk
+
2) Minsk Region
+
3) Brest Region
+
4) Grodno Region
+
5) Vitebsk Region
+
6) Mogilev Region
+
7) Gomel Region

Call sign containing:: 4 characters – class A (operator with CEPT licence, HAREC certificate)
+
5 characters – class A and class B (operator with CEPT licence, HAREC certificate)
+
6 characters – class C (operator with novice licence, ARNEC certificate)
+
5 characters – the fourth symbol is W, X, Z for club stations

Experimental stations:: EU1A00R-EU8Z99R (except EU5A00R–EU5Z99R) –  repeaters
+
EU1A00B-EU8Z99B (except EU5A00B–EU5Z99B) –  radiobeacons
+
EU10S-EU89S –  satellites
+
EV0AA-EV9ZZ –  for stations operating in radio contests
+
EV10ISS-EV89ISS –  for expeditions to space-based facilities
+
EV0ANA-EV0ANZ –  for stations operating in the Antartic
+
EV0A-EV9999Z –  for stations operating on days of special national and international events

EU5, EV5, EW5 followed by one letter – only for participants in international SW and USW radio communication competitions (up to one year).

NOTE: Foreign radio amateurs with a licence must use EW followed by slash (/) and their own call sign.


=== Belgium

[%unnumbered]
|===
2+^.^h| Amateur stations
a| ON0AA-ON0ZZ +
 ON0AAA-ON0ZZZ
| Automatic stations
a| ON1AA-ON1ZZ +
 ON1AAA-ON1ZZZ
| Class 2 stations
a| ON2AA-ON2ZZ +
 ON2AAA-ON2ZZZ
| Currently not in use
a| ON3AA-ON3ZZ +
 ON3AAA-ON3ZZZ
| Class 3 stations
a| ON4AA-ON4ZZ +
 ON4AAA-ON4ZZZ +
 ON5AA-ON5ZZ +
 ON5AAA-ON5ZZZ +
 ON6AA-ON6ZZ +
 ON6AAA-ON6ZZZ +
 ON7AA-ON7ZZ +
 ON7AAA-ON7ZZZ +
 ON8AA-ON8ZZ +
 ON8AAA-ON8ZZZ
| Class 1 stations
| ON9AAA-ON9AZZ | Class 3 stations for foreigners
| ON9BAA-ON9BZZ | Class 2 stations for foreigners
| ON9CAA-ON9CZZ | Class 1 stations for foreigners
| OP0LE and OP0OL | Club stations in Antarctica
a| OR3AA-OR3ZZ +
 OR3AAA-OR3ZZZ
a| Temporary class 3 stations in Antarctica
a| OR4AA-OR4ZZ +
 OR4AAA-OR4ZZZ
| Temporary class 1 stations in Antarctica
| OR4ISS | On board ISS
a| OO0A-OO9Z +
 OP0A-OP9Z +
 OQ0A-OQ9Z +
 OR0A-OR4Z +
 OR6A-OR9Z +
 OS0A-OS9Z +
 OT0A-OT4Z +
 OT6A-OT9Z
| Supplementary call signs for class 1 stations
a| OR5A-OR5Z +
 OT5A-OT5Z
| Stations for high power contests
|===


=== Belize

Amateur stations:: V31AA-V31ZZ  –  Class 1 licence
+
V32AA-V32ZZ  –  Class 2 licence


=== Benin (Republic of)

Amateur stations:: TY followed by a digit (1-9) and by 2 letters

=== Bhutan (Kingdom of)

Amateur stations:: A50AA-A50ZZ {blank}footnote:[For amateur clubs and stations.]
+
A51AA-A51ZZ {blank}footnote:[For national radio amateurs. ]
+
A52AA-A52ZZ {blank}footnote:[For visiting radio amateurs.]


=== Bolivia (Plurinational State of)

Amateur stations:: CP1AA-CP9ZZ

Digits indicating the departments:: 1 - La Paz
+
2 - Chuquisaca
+
3 - Oruro
+
4 - Potosí
+
5 - Cochabamba
+
6 - Santa Cruz
+
7 - Tarija
+
8 - Beni
+
9 - Pando

The call sign may be followed by the letters "M", "MA", "MF", "MM", "S" or "C" in the following cases:

M:: for mobile earth stations,

MA:: for mobile aeronautical stations,

MF:: for mobile river stations,

MM:: for mobile maritime stations,

S:: for second category stations,

C:: for stations operating on a temporary basis.


=== Bonaire, Sint Eustatius and Saba

Amateur stations:: PJ4AA-PJ4ZZZ –  Bonaire
+
PJ5AA-PJ5ZZZ –  S. Eustatius
+
PJ6AA-PJ6ZZZ –  Saba


=== Botswana (Republic of)

Amateur stations:: A22AA-A22ZZ


=== Brazil (Federative Republic of)

[%unnumbered]
|===
6+^.^| Amateur Stations
^.^| State 4+^.^| Classes A and B ^.^| Class C
.2+| Acre | PT8AA-PT8ZZ 2+| PT8AAA-PT8ZZZ 2+| PU8JAA-PU8LZZ
2+| {blank}footnote:amateur-stations[Special call signs: on national and international contest and expedition.] ZZ8HA-ZZ8MZ 3+| ZZ8HAA-ZZ8MZZ
.2+| Alagoas | PP7AA-PP7ZZ 2+| PP7AAA-PP7ZZZ 2+| PU7AAA-PU7DZZ
2+| {blank}footnote:amateur-stations[] ZZ7AA-ZZ7ZZ 3+| ZZ7AAA-ZZ7ZZZ
.2+| Amapá | PQ8AA-PQ8ZZ 2+| PQ8AAA-PQ8YZZ 2+| PU8GAA-PU8IZZ
2+| {blank}footnote:amateur-stations[] ZV8AA-ZV8ZZ 3+| ZV8AAA-ZV8YZZ
.2+| Amazonas | PP8AA-PP8ZZ 2+| PP8AAA-PP8YZZ 2+| PU8AAA-PU8CZZ
2+| {blank}footnote:amateur-stations[] ZZ8AA-ZZ8GZ 3+| ZZ8AAA-ZZ8GZZ
.2+| Bahia | PY6AA-PY6ZZ 2+| PY6AAA-PY6YZZ 2+| PU6JAA-PU6YZZ
2+| {blank}footnote:amateur-stations[] ZY6AA-ZY6ZZ 3+| ZY6AAA-ZY6YZZ
.2+| Ceará | PT7AA-PT7ZZ 2+| PT7AAA-PT7YZZ 2+| PU7MAA-PU7PZZ
2+| {blank}footnote:amateur-stations[] ZV7AA-ZV7ZZ 3+| ZV7AAA-ZV7YZZ
.2+| Distrito Federal | PT2AA-PT2ZZ 2+| PT2AAA-PT2YZZ 2+| PU2AAA-PU2EZZ
2+| {blank}footnote:amateur-stations[] ZV2AA-ZV2ZZ 3+| ZV2AAA-ZV2YZZ
.2+| Espírito Santo | PPlAA-PPlZZ 2+| PP1AAA-PP1YZZ 2+| PU1AAA-PU1IZZ
2+| {blank}footnote:amateur-stations[] ZZ1AA-ZZlZZ 3+| ZZlAAA-ZZlYZZ
.2+| Goiás | PP2AA-PP2ZZ 2+| PP2AAA-PP2YZZ 2+| PU2FAA-PU2HZZ
2+| {blank}footnote:amateur-stations[] ZZ2AA-ZZ2ZZ 3+| ZZ2AAA-ZZ2YZZ
.2+| Maranhão | PR8AA-PR8ZZ 2+| PR8AAA-PR8YZZ 2+| PU8MAA-PU8OZZ
2+| {blank}footnote:amateur-stations[] ZX8AA-ZX8ZZ 3+| ZX8AAA-ZX8YZZ
.2+| Mato Grosso | PY9AA-PY9ZZ 2+| PY9AAA-PY9YZZ 2+| PU9OAA-PU9YZZ
2+| {blank}footnote:amateur-stations[] ZY9AA-ZY9ZZ 3+| ZY9AAA-ZY9YZZ
.2+| Mato Grosso do Sul | PT9AA-PT9ZZ 2+| PT9AAA-PT9YZZ 2+| PU9AAA-PU9NZZ
2+| {blank}footnote:amateur-stations[] ZV9AA-ZV9ZZ 3+| ZV9AAA-ZV9YZZ
.2+| Minas Gerais | PY4AA-PY4ZZ 2+| PY4AAA-PY4YZZ 2+| PU4AAA-PU4YZZ
2+| {blank}footnote:amateur-stations[] ZY4AA-ZY4ZZ 3+| ZY4AAA-ZY4YZZ
.2+| Pará | PY8AA-PY8ZZ 2+| PY8AAA-PY8YZZ 2+| PU8WAA-PU8YZZ
2+| {blank}footnote:amateur-stations[] ZY8AA-ZY8ZZ 3+| ZY8AAA-ZY8YZZ
.2+| Paraíba | PR7AA-PR7ZZ 2+| PR7AAA-PR7YZZ 2+| PU7EAA-PU7HZZ
2+| {blank}footnote:amateur-stations[] ZX7AA-ZX7ZZ 3+| ZX7AAA-ZX7YZZ
.2+| Paraná | PY5AA-PY5ZZ 2+| PY5AAA-PY5YZZ 2+| PU5MAA-PU5YZZ
2+| {blank}footnote:amateur-stations[] ZY5AA-ZY5ZZ 3+| ZY5AAA-ZY5YZZ
.2+| Pernambuco | PY7AA-PY7ZZ 2+| PY7AAA-PY7YZZ 2+| PU7RAA-PU7YZZ
2+| {blank}footnote:amateur-stations[] ZY7AA-ZY7ZZ 3+| ZY7AAA-ZY7YZZ
.2+| Piauí | PS8AA-PS8ZZ 2+| PS8AAA-PS8YZZ 2+| PU8PAA-PU8SZZ
2+| {blank}footnote:amateur-stations[] ZW8AA-ZW8ZZ 3+| ZW8AAA-ZW8YZZ
.2+| Rio de Janeiro | PYlAA-PYlZZ 2+| PYlAAA-PYlYZZ 2+| PUlJAA-PUlYZZ
2+| {blank}footnote:amateur-stations[] ZYlAA-ZYlZZ 3+| ZYlAAA-ZYlYZZ
.2+| Rio Grande do Norte | PS7AA-PS7ZZ 2+| PS7AAA-PS7YZZ 2+| PU7IAA-PU7LZZ
2+| {blank}footnote:amateur-stations[] ZW7AA-ZW7ZZ 3+| ZW7AAA-ZW7YZZ
.2+| Rio Grande do Sul | PY3AA-PY3ZZ 2+| PY3AAA-PY3YZZ 2+| PU3AAA-PU3YZZ
2+| {blank}footnote:amateur-stations[] ZY3AA-ZY3ZZ 3+| ZY3AAA-ZY3YZZ
.2+h| Rondônia h| PW8AA-PW8ZZ 2+h| PW8AAA-PW8YZZ h| PU8DAA-PU8FZZ
2+| {blank}footnote:amateur-stations[] ZZ8NA-ZZ8SZ 2+| ZZ8NAA-ZZ8SZZ
.2+| Roraima | PV8AA-PV8ZZ 2+| PV8AAA-PV8YZZ | PU8TAA-PU8VZZ
2+| {blank}footnote:amateur-stations[] ZZ8TA-ZZ8ZZ 2+| ZZ8AAA-ZZ8YZZ
.2+| Santa Catarina | PP5AA-PP5ZZ 2+| PP5AAA-PP5YZZ | PU5AAA-PU5LZZ
2+| {blank}footnote:amateur-stations[] ZZ5AA-ZZ5ZZ 2+| ZZ5AAA-ZZ5YZZ
.2+| São Paulo | PY2AA-PY2ZZ 2+| PY2AAA-PY2YZZ | PU2KAA-PU2YZZ
2+| {blank}footnote:amateur-stations[] ZY2AA-ZY2ZZ 2+| ZY2AAA-ZY2YZZ
.2+| Sergipe | PP6AA-PP6ZZ 2+| PP6AAA-PP6YZZ | PU6AAA-PU6IZZ
2+| {blank}footnote:amateur-stations[] ZZ6AA-ZZ6ZZ 2+| ZZ6AAA-ZZ6YZZ
.2+| Tocantins | PQ2AA-PQ2ZZ 2+| PQ2AAA-PQ2YZZ | PU2IAA-PU2JZZ
2+| {blank}footnote:amateur-stations[] ZX2AA-ZX2ZZ 2+| ZX2AAA-ZX2YZZ
.2+| Islas Marítimas | PY0AA-PY0ZZ 2+| PY0AAA-PY0ZZZ | PU0AAA-PU0ZZZ
2+| {blank}footnote:amateur-stations[] ZY0AA-ZY0ZZ 2+| ZY0AAA-ZY0ZZZ

|===



=== Brunei Darussalam

Amateur stations:: V85 followed by 2 or 3 letters for the communications HF and VHF
+
V85 followed by 1 letter for the communications VHF only

=== Bulgaria (Republic of)

Amateur stations:: LZ1-LZ9 followed by a group of not more than 3 letters

=== Burkina Faso

Amateur stations and experimental stations:: XT2 or XT3 followed by 2 letters

=== Burundi (Republic of)

Amateur stations:: 9U5 followed by 2 letters

=== Cabo Verde (Republic of)

Amateur stations:: D44AA-D44ZZ

=== Cameroon (Republic of)

Amateur stations:: TJ1 followed by 2 letters

=== Canada

Amateur stations:: VE1, VA1 followed by 1, 2 or 3 letters – Provinces of Nova Scotia and New Brunswick
+
VE2, VA2 followed by 1, 2 or 3 letters – Province of Quebec
+
VE3, VA3 followed by 1, 2 or 3 letters – Province of Ontario
+
VE4, VA4 followed by 1, 2 or 3 letters – Province of Manitoba
+
VE5, VA5 followed by 1, 2 or 3 letters – Province of Saskatchewan
+
VE6, VA6 followed by 1, 2 or 3 letters – Province of Alberta
+
VE7, VA7 followed by 1, 2 or 3 letters – Province of British Columbia
+
VE8 followed by 1, 2 or 3 letters – Northwest Territories (excluding Nunavut)
+
VE9 followed by 1, 2 or 3 letters – Province of New Brunswick
+
VE0 {blank}footnote:[VE0 is intended for use when the amateur radio station is operated from a vessel that makes international voyages.] followed by 1, 2 or 3 letters – Amateur station on board a ship
+
VO1 followed by 1, 2 or 3 letters – Province of Newfoundland (excluding Labrador)
+
VO2 followed by 1, 2 or 3 letters – Labrador
+
VY0 followed by 1, 2 or 3 letters – Nunavut Territory
+
VY1 followed by 1, 2 or 3 letters – Yukon Territory
+
VY2 followed by 1, 2 or 3 letters – Province of Prince Edward Island

Experimental stations:: VX9 followed by 2 or 3 letters  –  Canada (all provinces and territories)


=== Central African Republic

Amateur stations and experimental stations:: TL8 followed by 2 or 3 letters

=== Chad (Republic of)

Amateur stations and experimental stations:: TT8 followed by 2 letters, the first of which is letter A

=== Chile

Amateur stations:: CE or XQ followed by a digit (indicating the zone in which the station is situated) and by 2 or 3 letters
+
CE1-CE8 followed by 2 or 3 letters –  Mainland Chile
+
CE9 followed by 2 or 3 letters –  Antarctic
+
CE0Y followed by 2 or 3 letters –  Easter Island
+
CE0Z followed by 2 letters –  Juan Fernández and San Félix Islands


=== Colombia (Republic of)

Amateur stations:: HJ or HK followed by a digit (0-9, indicating the zone to which belongs the radio amateur) and by 1, 2 or 3 letters

Digits indicating the zones:: 0 – Insular Colombian Territory and mobile maritime service
+
1 – Departments of Atlántico, Bolívar, Córdoba and Sucre
+
2 – Departments of Guajira, Magdalena, Cesar and North of Santander
+
3 – Departments of Cundinamarca, Meta and Vichada
+
4 – Departments of Antioquia and Chocó
+
5 – Departments of Cauca and Valle del Cauca
+
6 – Departments of Caldas, Tolima, Risaralda, Quindío and Huila
+
7 – Departments of Santander, Boyacá, Arauca and Casanare
+
8 – Departments of Nariño, Caquetá and Putumayo
+
9 – Departments of Amazonas, Vaupés, Guainía and Guaviare


NOTE: 5J or 5K followed by a digit (0-9) and by 1, 2 or 3 letters is authorised on a temporary basis to amateur stations operating during contests or special events.


=== Comoros (Union of the)

Amateur stations:: D68 followed by 2 letters {blank}footnote:[The 2 letters are the operator identity.]


=== Congo (Republic of the)

Amateur stations and experimental stations:: TN8AA-TN8ZZ

=== Cook Islands

Amateur stations:: ZK1 followed by 2 letters

=== Costa Rica

Amateur stations:: TE or TI followed by a digit and by a group of not more than 3 letters

=== Côte d'Ivoire (Republic of)

Amateur stations:: TU2AA-TU2ZZ

Experimental stations:: TU3AA-TU3ZZ

=== Croatia (Republic of)

Amateur stations:: 9A followed by a digit and by 1, 2 or 3 letters

=== Cuba

Amateur stations:: T4, CL, CM or CO followed by a digit (indicating the province or zone in which the station is situated) and by 1, 2 or 3 letters

Digits indicating the provinces or zones:: 1 – Province of Pinar del Río
+
2 – Province of Havana City
+
3 – Province of Havana
+
4 – Municipality of Isla de la Juventud
+
5 – Province of Matanzas
+
6 – Provinces of Villa Clara, Cienfuegos and Sancti Spíritus
+
7 – Provinces of Ciego de Ávila and Camagüey
+
8 – Provinces of Santiago de Cuba, Granma, Holguín, Las Tunas and Guantánamo

=== Curaçao

Amateur stations:: PJ2AA-PJ2ZZZ

=== Cyprus (Republic of)

Amateur stations:: 5B4AAA-5B4ZZZ

NOTE: Foreign amateurs will use the call sign assigned to them by their administration followed by a stroke (/) and then 5B4 on a temporary basis.

=== Czech Republic

Amateur stations:: OK0-OK8 followed by 1, 2 or 3 letters OL0-OL9 followed by 1, 2 or 3 letters
+
OK8 followed by 2 or 3 letters for foreigners transmitting from territory of the Czech Republic
+
OK0 followed by 2 or 3 letters exceptionally for extraordinary purposes
+
OL0-OL9 followed by 1 letter for purposes of international amateur contests only
+
OL0-OL9 followed by 2 or 3 letters for extraordinary purposes and for period of persistence of such purposes only

Experimental stations:: OK9 followed by 2 or 3 letters

=== Denmark

[%unnumbered]
|===
4+^.^| Amateur stations
^.^| Area ^.^| Prefix ^.^| Digit ^.^| Suffix
| Denmark ^.^| OU, OV, OZ, 5P, 5Q ^.^| 0-9 | Up to 4 characters, the last of which shall be a letter
| Faroe Islands ^.^| OY ^.^| 1-9 | 1, 2 or 3 letters
| Greenland ^.^| OX ^.^| 1-9 | 2 or 3 letters

|===

=== Djibouti (Republic of)

Amateur stations:: J28AA-J28ZZ {blank}footnote:[For amateur stations operating on a permanent basis.]
+
J20AA-J20ZZ {blank}footnote:[For amateur stations operating on a temporary basis.]

NOTE: For special events the radio amateurs will use J20 followed by a group of 3 letters.

=== Dominica (Commonwealth of)

Amateur stations and experimental stations:: J73AA-J73ZZ

=== Dominican Republic

Amateur stations:: HI followed by a digit (indicating the zone in which the station is situated) and a group of not more than 3 letters

Digits indicating the zones:: 1 – Beata Island
+
2 – Saona Island
+
3 – Central Cibao Region
+
4 – Northwest Line Region
+
5 – Southwest Region
+
6 – South Central Region
+
7 – East Region
+
8 – South Region
+
9 – Northwest Region


=== Ecuador

Amateur stations:: HC or HD followed by a digit (1-8, indicating the province in which the station is situated) and by 1, 2 or 3 letters
+
The beginners have to use the letter N after the digit indicating the province

Digits indicating the provinces:: 1 – Provinces of Carchi, Imbabura and Pichincha
+
2 – Provinces of Guayas (Coast) and Los Ríos
+
3 – Provinces of El Oro (Coast) and Loja
+
4 – Provinces of Manabí (Coast) and Esmeraldas (Coast)
+
5 – Provinces of Chimborazo, Cañar and Azuay
+
6 – Provinces of Cotopaxi, Tungurahua and Bolívar
+
7 – Provinces of Napo, Pastaza, Morona Santiago, Zamora and Sucumbios
+
8 – Province of the Galápagos (Islands)

Experimental stations:: HD9 followed by 3 letters


NOTE: The radio amateurs operating during competitions have to use HD9 followed by 1 letter on a temporary basis.


=== Egypt (Arab Republic of)

Amateur stations:: SU followed by a digit and 2 letters

=== El Salvador (Republic of)

Amateur stations:: YS followed by a digit (1-9, indicating the zone in which the station is situated) and by a group of not more than 3 letters

Digits indicating the zones:: 1 – Department of San Salvador
+
2 – Department of Santa Ana
+
3 – Department of San Miguel
+
4 – Department of La Libertad
+
5 – Departments of La Paz, Cuscatlán and Chalatenango
+
6 – Departments of Usulután, San Vicente and Cabañas
+
7 – Department of Sonsonate
+
8 – Department of Ahuachapán
+
9 – Departments of Morazán and La Unión

Experimental stations:: HU9 followed by 2 letters

NOTE: Foreign radio amateurs must use YS followed by a digit (1-9, indicating the operational zone), by a stroke (/) and by their own call sign.

=== Estonia (Republic of)

Amateur stations:: ES followed by a digit (0-9, indicating the district in which the station is situated) and by 1, 2 or 3 letters

Digits indicating the districts:: 0 – Administrative districts of Hiiumaa, Saaremaa and all small islands of Väinamere
+
1 – Tallinn
+
2 – Administrative district of Harjumaa
+
3 – Administrative districts of Lääne, Rapla and Järvamaa
+
4 – Administrative districts of Lääne-Virumaa and Ida-Virumaa
+
5 – Administrative districts of Jõgeva and Tartumaa
+
6 – Administrative districts of Põlva, Valga and Võrumaa
+
7 – Administrative district of Viljandimaa
+
8 – Administrative district of Pärnumaa
+
9 – Extraterritorial (for official using by Estonian Amateur Radio Union)

When amateur stations operate as portable or mobile stations, their call signs are followed by a stroke (/) and the letters "MM", "AM", "M" or "P" in the following cases:

* "MM" if the station is operated on board an Estonian vessel on international waters,

* "AM" if the station is operated on board an Estonian aircraft,

* "M" if the station is operated on board of some other vehicle including on board of a vessel on national waters,

* "P" if the station is hand-carried.

Foreign radio amateurs during their visit in Estonia must use ES followed by a digit (0-8) indicating the district in which the station is located, by a stroke (/) and by their own call sign.


=== Ethiopia (Federal Democratic Republic of)

Amateur stations:: ET3AA-ET3ZZ
+
9E3AA-9F3ZZ

=== Fiji (Republic of)

Amateur stations:: 3D2 followed by 2 letters

Experimental stations:: 3D3 followed by 2 letters

=== Finland

Amateur stations and experimental stations:: OF, OG, OH, OI or OJ followed by a digit and a group of not more than 4 characters, the last of which shall be a letter

=== France

[%unnumbered]
|===
4+^.^| Amateur stations
^.^| F {blank}footnote:france1[F followed by a letter (A, B, C, D or E) indicating the group to which the radio amateur belongs, followed by an F indicating a radio club station.] ^.^| 0-9 {blank}footnote:france2[A digit 0 to 9 (except the digit 7).] ^.^| AA-ZZZ{blank}footnote:france3[2 or 3 letters characterizing the radio amateur.] ^.^| France (Continental)
| | | ^.^| Corsica, Overseas Departments and Territories (except New Caledonia):
^.^| FG ^.^| 1-5 {blank}footnote:france4[A digit indicating the group to which the radio amateur belongs (1: group A, 2: group B, 3: group C, 4: group D and 5: group E), the digit 0 indicating a radio club station.] ^.^| AA-ZZZ {blank}footnote:france3[] | Guadeloupe
^.^| FH ^.^| » ^.^| » | Mayotte
^.^| FJ ^.^| » ^.^| » | Saint Bartholomew
^.^| FM ^.^| » ^.^| » | Martinique
^.^| FO ^.^| » ^.^| » | French Polynesia
^.^| FP ^.^| » ^.^| » | Saint Pierre and Miquelon
^.^| FR ^.^| » ^.^| » | Reunion
^.^| FT ^.^| » ^.^| » | Southern and Antarctic Lands
^.^| FW ^.^| » ^.^| » | Wallis and Futuna
^.^| FY ^.^| » ^.^| » | Guiana
^.^| TK ^.^| » ^.^| » | Corsica
^.^| FK ^.^| 8 ^.^| AA-ZZZ {blank}footnote:france5[2 or 3 letters characterizing the radio amateur, K as first letter indicating a radio club station.] | New Caledonia
|===


=== Gabonese Republic

Amateur stations:: TR8AA-TR8ZZ


=== Gambia (Republic of the)

Amateur stations:: C53AA-C53ZZ


=== Georgia

Amateur stations:: 4L followed by a digit and by 1, 2 or 3 letters


=== Germany (Federal Republic of)

[%unnumbered]
|===
3+^.^| Amateur stations
^.^| Call signs ^.^| Purpose of use ^.^| Class
^.^| 1 ^.^| 2 ^.^| 3
| DA0A-DA0ZZZ | Club stations ^.^| A
| DA1A-DA1Z {blank}footnote:germany1[Only for personnel under SOFA (Status of Forces Agreement).] | Club stations ^.^| A
| DA1AA-DA1ZZZ {blank}footnote:germany1[] | Individual stations, club stations, repeaters, beacons ^.^| A
| DA2A-DA3Z | Club stations ^.^| A
| DA2AA-DA2ZZZ | Individual stations, club stations, repeaters, beacons ^.^| A
| DA4A-DA4Z | Special experimental studies as club stations ^.^| E
| DA4AA-DA4ZZZ {blank}footnote:germany2[Also for personnel under SOFA (Status of Forces Agreement).] | Special experimental studies as individual stations ^.^| E
| DA5A-DA5Z | Special experimental studies as club stations ^.^| A
| DA5AA-DA5ZZZ {blank}footnote:germany2[] | Special experimental studies^^as individual stations ^.^| A
| DA6A-DA6Z {blank}footnote:germany1[] | Club stations ^.^| E
| DA6AA-DA6ZZZ {blank}footnote:germany1[] | Individual stations, club stations, repeaters, beacons ^.^| E
| DA7A-DA9Z | Club stations ^.^| E
| DB0A-DD9Z | Club stations ^.^| A
| DB0AA-DB0ZZZ | Repeaters, beacons ^.^| A
| DB1AA- DD9ZZZ | Individual stations ^.^| A
| DF0A-DH9Z | Club stations ^.^| A
| DF0AA-DF0ZZZ | Club stations ^.^| A
| DF1AA- DH9ZZZ | Individual stations ^.^| A
| DJ0A-DM9Z | Club stations ^.^| A
| DJ0AA-DJ9ZZZ | Individual stations ^.^| A
| DK0AA-DK0ZZZ | Club stations ^.^| A
| DK1AA-DK9ZZZ | Individual stations ^.^| A
| DL0AA-DL0ZZZ | Club stations ^.^| A
| DL1AA-DL9ZZZ | Individual stations ^.^| A
| DM0AA-DM0ZZZ | Repeaters, beacons (DM0ZA-DM0ZZZ: repeaters with new technology) ^.^| A
| DM1AA-DM9ZZZ | Individual stations ^.^| A
| DN0A-DN0ZZZ | Club stations ^.^| E
| DN1AA-DN6ZZZ {blank}footnote:germany2[] | Stations used for radio operation instruction ^.^| A
| DN7AA-DN8ZZZ {blank}footnote:germany2[] | Stations used for radio operation instruction ^.^| E
| DO0A-DO9Z | Club stations ^.^| E
| DO0AA-DO0ZZZ | Repeaters, beacons (DO0ZA-DO0ZZZ: repeaters with new technology) ^.^| E
| DO1AA-DO9ZZZ | Individual stations ^.^| E
| DP0A-DP1Z | Club stations (exterritorial locations) ^.^| A
| DP0AA-DP1ZZZ | Club stations, repeaters, beacons, special experimental studies (exterritorial locations) ^.^| A
| DP2A-DP2Z | Club stations (exterritorial locations) ^.^| E
| DP2AA-DP2ZZZ | Club stations, repeaters, beacons, special experimental studies (exterritorial locations) ^.^| E
| DP3A- DR9Z | Club stations ^.^| A

|===


NOTE: Foreign radio amateurs without permanent residence in Germany will use DL followed by a stroke (/) and their national call sign for class A, or DO followed by a stroke (/) and their national call sign for class E, or a personal regulatory call sign.

Experimental stations:: DI2AA-DI2ZZ


=== Ghana

Amateur stations:: 9G1 followed by 2 or more letters {blank}footnote:[For national radio amateurs.]
+
9G5 followed by 2 or more letters {blank}footnote:[For foreign radio amateurs.]

Experimental stations:: 9G2 followed by 2 letters


=== Greece

Amateur stations and experimental stations:: SV {blank}footnote:[Class 1.] or SW {blank}footnote:[Class 2.] followed by a digit (indicating the region in which the station is situated) and by 2 or 3 letters

Digits indicating the regions:: 1 – Sterea Hellas
+
2 – Central and Western Macedonia
+
3 – Peloponnese
+
4 – Thessaly
+
5 – Dodecanese Prefecture
+
6 – Epirus
+
7 – Eastern Macedonia and Thrace
+
8 – All the islands (except those belonging to Cretian Prefectures and to Dodecanese Prefecture)
+
9 – Cretian Prefectures and their islands

[NOTE]
====
. SV0 or SW0 followed by 2 or 3 letters is assigned to Greek radio amateurs with a foreign licence and to foreign radio amateurs with permanent residence.

. The prefix J4, SX or SY is assigned as a special call sign to Greek unions of radio amateurs, Greek teams of radio amateurs, Greek radio amateurs and foreign radio amateurs.

. The prefix SZ is assigned to the Greek Radio Amateur Union and Greek university laboratories in the area of wireless telecommunications.
====

=== Guatemala (Republic of)

Amateur stations:: TG followed by a digit (4-9, indicating the department in which the station is situated) and by 2 letters

Digits indicating the departments:: 4 – Sololá, Chimaltenango, Suchitepéquez, Escuintla and Santa Rosa
+
5 – Huehuetenango, Quiché and Totonicapán
+
6 – Zacapa, Chiquimula and Jutiapa
+
7 – Petén, Alta Verapaz and Izabal
+
8 – San Marcos, Quetzaltenango and Retalhuleu
+
9 – Guatemala, Jalapa, El Progreso, Baja Verapaz and Sacatepéquez

Experimental stations:: TD9A-TD9Z


=== Guinea (Republic of)

Amateur stations:: 3X0AA-3X9ZZ

Experimental stations:: 3X2AAA-3X9ZZZ


=== Guinea-Bissau (Republic of)

Amateur stations:: J52UAB-J52UAI


=== Guyana

Amateur stations and experimental stations:: 8R1AAA-8R1ZZZ –  Demerara
+
8R2AAA-8R2ZZZ –  Berbice
+
8R3AAA-8R3ZZZ –  Essequibo


=== Haiti (Republic of)

Amateur stations:: HH followed by a digit (indicating the zone in which the station is situated) and by 2 letters

=== Honduras (Republic of)

Amateur stations::
HR followed by a digit (1-9, indicating the zone in which the station is situated) and by:

* 1 letter for the superior class with 20 years or more of good service,

* 2 letters for the superior class with less than 20 years of service,

* 3 letters for the advanced and general class.

+

HQ followed by a digit (1-9, indicating the zone in which the station is situated) and by:

* 1 letter for national and international special events in which participate, local and foreign radio amateurs from the administrations having reciprocal agreement,

* 3 letters for the novice class.


=== Hungary

Amateur stations:: HA or HG followed by a digit (0-9) and a group of not more than four characters, the last of which shall be a letter

=== Iceland

Amateur stations:: TF followed by a digit (indicating the area in which the station is situated) and by 1, 2 or 3 letters
+
For novice licence holders the last letter has to be N.

Call signs followed by a stroke (/) and the letters "M" or "P" are used in the following cases:

* letter "M" to denote a mobile station,

* letter "P" to denote a portable station.


=== India (Republic of)

Amateur stations:: VU2 or VU3 followed by 2 or 3 letters  –  Mainland India
+
VU4 or VU7 followed by 2 or 3 letters  –  National Islands

Experimental stations:: VU4 followed by 2 letters

=== Indonesia (Republic of)

Amateur stations:: YB or YE followed by a digit (0-9) and by 1 {blank}footnote:indonesia1[The 1 letter suffix is not for personal call sign use, but only for organizational stations with special event activities.], 2 or 3 letters  –  Advanced licence
+
YC or YF followed by a digit (0-9) and by 1 {blank}footnote:indonesia1[], 2 or 3 letters  –  General licence
+
YD, YG or YH followed by a digit (0-9) and by 1 {blank}footnote:indonesia1[], 2 or 3 letters  –  Novice licence


=== Iran (Islamic Republic of)

Amateur stations:: EP1AA-EP9ZZ

=== Iraq (Republic of)

Amateur stations:: YI1 followed by 3 letters

=== Ireland

Amateur stations:: EI followed by a digit (2-9) and a group of not more than 3 letters

=== Israel (State of)

Amateur stations:: 4X1 followed by 2 or 3 letters
+
4X4 followed by 2 or 3 letters
+
4X6 followed by 2 or 3 letters
+
4X8 followed by 2 or 3 letters
+
4Z1 followed by 2 or 3 letters
+
4Z4 followed by 2 or 3 letters
+
4Z5 followed by 2 or 3 letters
+
4Z7 followed by 2 or 3 letters
+
4Z9 followed by 2 or 3 letters


=== Italy

Amateur stations:: I0 or IK0 followed by 2 or 3 letters – Lazio and Umbria
+
I1 or IK1 followed by 2 or 3 letters – Liguria, Piemonte and the Province of Novara
+
I2 or IK2 followed by 2 or 3 letters – Lombardia and the Province of Mantova
+
I3 or IK3 followed by 2 or 3 letters – Veneto and the Province of Rovigo
+
I4 or IK4 followed by 2 or 3 letters – Emilia-Romagna and the Province of Piacenza
+
I5 or IK5 followed by 2 or 3 letters – Toscana
+
I6 or IK6 followed by 2 or 3 letters – Marche and Abruzzi
+
I7 or IK7 followed by 2 or 3 letters – Puglie and the Province of Matera
+
I8 or IK8 followed by 2 or 3 letters – Campania, Molise, Calabria and the Province of Potenza
+
IA5 followed by 2 or 3 letters – "Toscane" Islands (Capraia, Cerboli, Elba, Formica di Burano, Formiche di Grosseto, Giannutri, Giglio, Gorgona, Montecristo, Pianosa, Scoglio d'Affrica)
+
IB0 followed by 2 or 3 letters – "Ponziane" Islands (Palmarola, Ponza, Scoglio della Botte, Santo Stefano, Ventotene, Zanone)
+
IC8 followed by 2 or 3 letters – "Napoletane" Islands (Capri, Ischia, Li Galli, Procida, Vivara)
+
ID9 followed by 2 or 3 letters – "Eolie" Islands (Alicudi, Basiluzzo, Dino, Filicudi, Formiche, Lipari, Lisca Bianca, Panarea, Salina, San Pietro a Canna, Stromboli, Strombolicchio, Vulcano)
+
IE9 followed by 2 or 3 letters – Island of Ustica
+
IF9 followed by 2 or 3 letters – "Egadi" Islands (Asinelli, Favignana, La Formica, Levanzo, Maraone, Marettimo, Stagnone)
+
IG9 followed by 2 or 3 letters – "Pelagie" Islands (Lampedusa, Lampione, Linosa)
+
IH9 followed by 2 or 3 letters – Island of Pantelleria
+
IJ7 followed by 2 or 3 letters – Archipelago of "Cheradi"
+
IL7 followed by 2 or 3 letters – "Tremiti" Islands (Caprara, Pianosa, San Domino, San Nicola)
+
IM0 followed by 2 or 3 letters – "Sardegna" Islands (Asinara, Bisce, Budelli, Carbonara, Caprera, Cavoli, Corcelli, Cretaccio, Foradada, Il Catalano, Il Toro, Il Vitello, La Maddalena, La Vacca, Mal di Ventre, Molara, Mortorio, Nibani, Ogliastra, Pan di Zucchero, Piana, Quirra, Razzoli, Rossa, Ruglia, S. Antioco, S. Pietro, S. Macario, S. Maria, Serpentara, Soffi, Spargi, Su Giudeu, Tavolara)
+
IN3 followed by 2 or 3 letters – Trentino-Alto Adige
+
IP1 followed by 2 or 3 letters – "Liguria" Islands
+
IS0 followed by 2 or 3 letters – Sardegna
+
IT9 followed by 2 or 3 letters – Sicilia
+
IV3 followed by 2 or 3 letters – Friuli and Venezia Giulia
+
IW0 followed by 2 or 3 letters – Special licences
+
IX1 followed by 2 or 3 letters – Aosta Valley


=== Jamaica

Amateur stations and experimental stations:: 6Y5AA-6Y5ZZ

NOTE: Foreign amateurs will use the call sign assigned to them by their administration followed by a stroke (/) and then 6Y5.


=== Japan

Amateur stations:: JA _n_ AA-JA _n_ ZZ (_n_ = 0-9)
+
JR6AA-JR6NZ
+
JR _n_ VA-JR _n_ WZ (_n_ = 0-9)
+
JR6YA-JR6YZ
+
J _xn_ AAA-J _xn_ QQZ (_x_ = A, E-S) (_n_ = 0-9)
+
J _xn_ QUA-J _xn_ ZZZ (_x_ = A, E-S) (_n_ = 0-9)
+
JD1AAA-JD1QQZ
+
JD1QUA-JD1ZZZ
+
7J _n_ AAA-7J _n_ BZZ (_n_ = 0, 4, 5, 7-9)
+
7J _n_ AAA-7J _n_ CZZ (_n_ = 2, 3, 6)
+
7J1AAA-7J1DZZ
+
7J _n_ YAA-7J _n_ YMZ (_n_ = 0-5, 7-9)
+
7J6YAA-7J6YQZ
+
7 _xn_ AAA-7 _xn_ QQZ (_x_ = K-N) (_n_ = 1-4)
+
7 _xn_ QUA-7 _xn_ ZZZ (_x_ = K-N) (_n_ = 1-4)
+
8 _xn_ AAA-8 _xn_ QZZ (_x_ = J, N) (_n_ = 0-9)
+
8 _xn_ QUA-8 _xn_ ZZZ (_x_ = J, N) (_n_ = 0-9)


Experimental stations:: J _xn_ A-J _xn_ Z (_x_ = B, G, J, O, S) (_n_ = 2-9)
+
J _xn_ AA-J _xn_ ZZ (_x_ = B, G, J, O, S) (_n_ = 2-9)

=== Jordan (Hashemite Kingdom of)

Amateur stations:: JY1AA-JY9ZZ

=== Kenya (Republic of)

Amateur stations:: 5Z4AA-5Z4ZZ

Experimental stations:: 5Z5AA-5Z5ZZ

=== Kiribati (Republic of)

Amateur stations:: T3 followed by a digit (0-9) and by a group of not more than 3 letters

Experimental stations:: T3 followed by a digit (other than 0 or 1) and by a group of not more than 3 letters

=== Korea (Republic of)

Amateur stations:: 1) HL1AA-HL9ZZ
+
HL1AAA-HL9ZZZ
+
2) HL0 followed by 2 or 3 letters (amateur group)

Experimental stations:: 6M2AA-6M2ZZ
+
6N2AA-6N2ZZ

NOTE: DS, DT, D7, D8, D9, 6K, 6L, 6M, 6N followed by a digit and by 2 or 3 letters are assigned on a temporary basis on special occasions.

=== Kuwait (State of)

Amateur stations:: 9K2 followed by 1 or 2 letters
+
9K9 followed by 1 letter

=== Kyrgyz Republic

Amateur stations:: EX followed by a digit (0-9) and 1 or 2 letters

NOTE: Foreign radio amateurs will use EX followed by a stroke (/) and their home call sign.

=== Lao People's Democratic Republic

Amateur stations:: XW8AA-XW8DZ

Experimental stations:: XW8EA-XW8EZ

=== Latvia (Republic of)

Amateur stations and experimental stations:: YL followed by a digit and by 1, 2 or 3 letters

=== Lebanon

Amateur stations:: OD5 followed by 2 letters

Experimental stations:: OD9 followed by 2 letters

=== Lesotho (Kingdom of)

Amateur stations and experimental stations:: 7P8 followed by a group of not more than 3 letters

=== Libya

Amateur stations:: 5A followed by a digit (0-9) and by a group of not more than 3 letters

Experimental stations:: 5A followed by a digit (other than 0 or 1) and by a group of not more than 3 letters

=== Liechtenstein (Principality of)

Amateur stations:: HB0AAA-HB0XXX
+
HB0YAA-HB0YZZ  –  Novice licence
+
HB0ZAA-HB0ZZZ

=== Lithuania (Republic of)

Amateur stations and experimental stations:: LY followed by a digit (1-4) and by 1 to 4 letters

NOTE: LY followed by 2 to 4 digits and by 1 letter is authorized only for the formation of occasional radio call signs.

=== Luxembourg

[%unnumbered]
|===
| LX0A-LX0ZZZZ | Repeaters, beacons, group stations

| LX1A-LX1ZZZZ .3+| Individual stations operating with a HAREC certificate

| LX2A-LX2ZZZZ
| LX3A-LX3ZZZZ
| LX4A-LX4ZZZZ | Group stations

| LX5A-LX5ZZZZ | Group stations, experimental stations

| LX6A-LX6ZZZZ | Individual stations operated by beginners

| LX7A-LX7ZZZZ | Individual stations operated during competitions

| LX8A-LX8ZZZZ .2+| Group stations

| LX9A-LX9ZZZZ

|===


NOTE: Foreign radio amateurs with temporary licence must use LX followed by a stroke (/) and their own call sign.

=== Madagascar (Republic of)

Amateur stations:: 5R8 followed by a group of not more than 3 letters

Experimental stations:: 5S6 followed by a group of not more than 3 letters

=== Malawi

Amateur stations:: 7Q7 followed by 2 letters


=== Malaysia

[%unnumbered]
|===
3+^.^| Amateur stations
^.^| Call signs ^.^| Class ^.^| Territory
| 9M2AAA-9M2ZZZ ^.^| A .2+^.^| Peninsular Malaysia
| 9W2AAA-9W2ZZZ ^.^| B
| 9M6AAA-9M6ZZZ ^.^| A .2+^.^| Sabah
| 9W6AAA-9W6ZZZ ^.^| B
| 9M8AAA-9M8ZZZ ^.^| A .2+^.^| Sarawak
| 9W8AAA-9W8ZZZ ^.^| B
3+^.^| Experimental stations
3+| 9M4EAA-9M4EZZ

|===

=== Maldives (Republic of)

Amateur stations:: 8Q7AA-8Q7ZZ

=== Malta

[%unnumbered]
|===
3+^.^| Amateur stations
^.^| Call signs ^.^| Class ^.^| Area
| 9H1A-9H1ZZ ^.^| A | Malta
| 9H4A-9H4ZZ ^.^| A | Gozo Island
| 9H5A-9H5ZZ ^.^| B | Malta and Gozo Island
3+^.^| Experimental stations
3+| 9H3A-9H3ZZ {blank}footnote:[Also for temporary stations.]

|===


=== Mauritania (Islamic Republic of)

Amateur stations:: 5T5 followed by 2 letters

Experimental stations:: 5T2 followed by 2 letters

=== Mauritius (Republic of)

Amateur stations:: 3B6 followed by 2 letters –  Agalega
+
3B7 followed by 2 letters –  S. Brandon
+
3B8 followed by 2 letters –  Mauritius
+
3B9 followed by 2 letters –  Rodrigues

NOTE: Foreign radio amateurs with visitor licence must use 3B8 followed by a stroke (/) and their own call sign.


=== Mexico

[%unnumbered]
|===
2+^.^| Amateur stations
2+| _Continental Part_
2+| XE0A-XE0ZZZ
| XE1A-XE1ZZZ | _Zone 1:_ Distrito Federal, Colima, Guanajuato, Hidalgo, Jalisco, Estado de México, Michoacán, Morélos, Nayarit, Puebla, Querétaro, Tlaxcala and Veracruz
| XE2A-XE2ZZZ | _Zone 2:_ Aguascalientes, Baja California Norte, Baja California Sur, Coahuila, Chihuahua, Durango, Nuevo León, San Luis Potosí, Sinaloa, Sonora, Tamaulipas and Zacatecas
| XE3A-XE3ZZZ | _Zone 3:_ Campeche, Chiapas, Guerrero, Oaxaca, Quintana Roo, Tabasco and Yucatán
2+| _Insular Part_
2+| XF0A-XF0ZZZ
| XF1A-XF1ZZZ | _Zone 1:_ Baja California Norte, Baja California Sur, Sonora, Sinaloa and Nayarit
| XF2A-XF2ZZZ | _Zone 2:_ Tamaulipas, Veracruz, Tabasco and Campeche
| XF3A-XF3ZZZ | _Zone 3:_ Yucatán and Quintana Roo
| XF4A-XF4ZZZ | _Zone 4:_ Jalisco, Colima, Michoacán, Guerrero, Oaxaca and Chiapas

|===

[NOTE]
====
. Foreign radio amateurs operating in the Continental Part will use XE1, XE2 or XE3 followed by a stroke (/) and by their home call sign.

. Only for special events the radio amateurs will use XA, XB, XC, XD, XE, XF, XG, XH, XI, 4A, 4B, 4C, 6D, 6E, 6F or 6J followed by a digit and by a group of not more than 3 letters.
====

=== Micronesia (Federated States of)

Amateur stations:: V63 followed by 2 letters

Experimental stations:: V62 followed by the letter X and by 2 letters

=== Moldova (Republic of)

Amateur stations:: ER1 – ER5 followed by one, two or three letters

Suffix can be composed of::
* two or three letters for individual stations (letter K is forbidden for the first letter)
+
* three letters for club stations (the first of which is letter K)
+
* one, two, three or more digits and/or letters for special call signs, beacons and repeaters.


Call sign containing:: 4 characters  class A;
+
5 characters  class A and class B;
+
6 characters  class C.
+
ER6 – ER0 followed by two or more digits are used for special call signs allocated for special events
+
ER1 – ER0 followed by two or more digits can be allocated to:
+

* a physical resident – citizen of the Republic of Moldova;

* a foreign citizen or eupatrid who has permanent residence in the Republic of Moldova (confirmed by respective documents);

* legal residents of the Republic of Moldova.

Call signs followed by a stroke (/) and letters "MM", "AM", "M" and "P" are used in the following cases:

MM:: for mobile maritime or river stations,

AM:: for mobile aeronautical stations,

M:: for mobile terrestrial stations,

P:: for portable terrestrial stations.


NOTE: Authorized foreign radio amateurs will use ER followed by a stroke (/) and their home call sign.


=== Monaco (Principality of)

Amateur stations:: 3A2AA-3A2ZZ  –  Class 1  – General licence
+
3A1AA-3A1ZZ  –  Class 2  – Licence restricted to bands 144-146 MHz and 430-440 MHz
+
3A2AAA-3A2ZZZ  –  Radio Club

Experimental stations:: 3A9A-3A9Z


=== Morocco (Kingdom of)

Amateur stations:: CN2AA-CN2ZZ
+
CN8AA-CN8ZZ

Experimental stations:: CN4AA-CN4ZZ

=== Mozambique (Republic of)

Amateur stations:: C9 followed by a digit (indicating the province in which the station is situated) and by a group of not more than 3 letters

Digits indicating the provinces:: 1 – Maputo
+
2 – Gaza-Inhambane
+
3 – Sofala-Manica
+
4 – Zambezia-Nampula
+
5 – Tete-Niassa
+
6 – C. Delgado


=== Myanmar (Union of)

Amateur stations and experimental stations:: XZ2AA-XZ2ZZ

=== Namibia (Republic of)

Amateur stations:: V50A-V50ZZZ – Restricted licence station
+
V51A-V51ZZZ – Full licence station
+
V5 followed with existing call sign – Guest station

Experimental stations:: V59A-V59ZZZ

=== Nauru (Republic of)

Amateur stations:: C2 followed by a digit identifying the category and by 2 letters

=== Nepal (Federal Democratic Republic of)

Amateur stations:: 9N1AA-9N1ZZZ

=== Netherlands (Kingdom of the)

Amateur stations:: PA0, PA1, PA6, PI4, PI6, PI7 or PI8 followed by 2 or 3 letters PA2, PA3, PB0, PD0, PE0, PE1, PI1, PI2 or PI3 followed by 3 letters

Experimental stations:: PI5 or PI9 followed by 2 or 3 letters


=== New Zealand

[%unnumbered]
|===
2+^.^| Amateur stations and experimental stations
^.^| Call signs ^.^| Areas
^.^| 1 ^.^| 2
a| ZL1AA-ZL4WZ +
 ZL1AAA-ZL4WZZ +
 ZL1AAAA-ZL4WZZZ
| New Zealand
a| ZK0A-ZK9ZZZZ +
 ZL0A-ZL0ZZZZ +
 ZL1A-ZL4W +
 ZM0A-ZM0ZZZZ +
 ZM1A-ZM9ZZZZ {blank}footnote:newZealand2[Amateurs will use the prefix ZM instead of ZL for contests and other special events.]
| New Zealand special events
a| ZL5AA-ZL5WZ +
 ZL5AAA-ZL5WZZ +
 ZL5AAAA-ZL5WZZZ
| Antarctic
| ZL5A-ZL5W | Antarctic special events
a| ZL6AA-ZL6WZ +
 ZL6AAA-ZL6WZZ +
 ZL6AAAA-ZL6WZZZ
| NZART {blank}footnote:newZealand1[New Zealand Association of Radio Transmitters (NZART).]
| ZL6A-ZL6W | NZART{blank}footnote:newZealand1[] special events
a| ZL7AA-ZL7WZ +
 ZL7AAA-ZL7WZZ +
 ZL7AAAA-ZL7WZZZ
| Chatham Islands
| ZL7A-ZL7W | Chatham Islands special events
a| ZL8AA-ZL8WZ +
 ZL8AAA-ZL8WZZ +
 ZL8AAAA-ZL8WZZZ
| Kermadec Islands
| ZL8A-ZL8W | Kermadec Islands special events
a| ZL9AA-ZL9WZ +
 ZL9AAA-ZL9WZZ +
 ZL9AAAA-ZL9WZZZ
| Auckland/Campbell Islands
| ZL9A-ZL9W | Auckland/Campbell Islands special events

|===


=== Nicaragua

Amateur stations:: YN followed by a digit (indicating the zone in which the station is situated) and by 2 or 3 letters

Digits indicating the zones:: 1 – Managua
+
2 – Granada
+
3 – León
+
4 – Zelaya
+
5 – Carazo and Rivas
+
6 – Chinandega
+
7 – Masaya
+
8 – Estelí, Madriz and Nueva Segovia
+
9 – Matagalpa, Jinotega, Boaco, Chontales and Río San Juan


=== Niger (Republic of the)

Amateur stations and experimental stations:: 5U2-5U9 followed by the letter V and by 1 or 2 letters

When stations operate as fixed stations, their call signs are followed by the letter "F".

When stations operate as mobile stations, their call signs are followed by the letters "MOB".

=== Nigeria (Federal Republic of)

Amateur stations:: 5N followed by a digit (indicating the zone in which the station is situated) and by 3 letters

Digits indicating the zones:: 0 – Lagos State and Federal Capital Territory
+
1 – Ogun, Oyo, Ondo and Ekiti States
+
2 – Osun, Kwara, Kogi and Niger States
+
3 – Edo, Delta, Bayelsa and Anambra States
+
4 – Enugu, Abia, Ebonyi and Rivers States
+
5 – Imo, Akwa lbom and Cross River States
+
6 – Benue, Plateau, Nassarawa and Taraba States
+
7 – Bauchi, Gombe, Adamawa and Borno States
+
8 – Jigawa, Kano, Yobe and Katsina States
+
9 – Zamfara, Sokoto, Kaduna and Kebbi States

Experimental stations:: 5N2XA-5N2ZZ
+
5N3EA-5N3EZ
+
5N4XA-5N4ZZ
+
5N5EA-5N5EZ
+
5N6XA-5N6ZZ
+
5N7EA-5N7EZ
+
5N8XA-5N8ZZ
+
5N9EA-5N9EZ


=== Niue

Amateur stations:: ZK2 followed by 2 letters

=== Norway

Amateur stations:: JW0AAA-JW9ZZZ
+
JX0AAA-JX0ZZZ
+
LA0AAA-LA9ZZZ
+
LB0AAA-LB9ZZZ
+
LC0AAA-LC9ZZZ
+
LD0AAA-LD9ZZZ
+
3Y0AAA-3Y9ZZZ

Experimental stations:: LF2AAA-LF9ZZZ

=== Oman (Sultanate of)

Amateur stations:: A40AA-A48ZZ

Experimental stations:: A49AA-A49ZZ

=== Pakistan (Islamic Republic of)

Amateur stations and experimental stations:: AP2-AP9 followed by a group of not more than 3 letters


=== Papua New Guinea

Amateur stations:: P29BAA-P29BZZ – Beacons
+
P29CAA-P29CZZ –  Club stations
+
P29KAA-P29KZZ –  Combined licences
+
P29NAA-P29NZZ –  Novice licence
+
P29RAA-P29RZZ –  Repeaters
+
P29ZAA-P29ZZZ –  Limited licence

=== Paraguay (Republic of)

Amateur stations:: ZP followed by a digit (1-9, indicating the zone in which the station is situated) and by 2 or 3 letters characterizing the radio amateur (the first of which is neither letter I, nor O, nor Q)

Digits indicating the zones:: 1 – Departments of Alto Paraguay and Boquerón
+
2 – Department of Presidente Hayes
+
3 – Departments of Concepción and Amambay
+
4 – Departments of San Pedro and Canindeyú
+
5 – Asunción (Capital) – Municipio de Asunción
+
6 – Departments of Cordillera, Paraguari and Central
+
7 – Departments of Guairá, Caaguazú and Caazapá
+
8 – Departments of Misiones and Neembucú
+
9 – Departments of Itapúa and Alto Paraná

NOTE: The digit 0 is allocated to amateur stations during special occasions.

=== Peru

Amateur stations:: OA followed by a digit (0-9, indicating the zone in which the station is situated) and by 1, 2 or 3 letters

Digits indicating the zones:: 0 – Peruvian Antarctic
+
1 – Tumbes, Piura, Lambayeque
+
2 – Cajamarca, La Libertad
+
3 – Huánuco, Ancash
+
4 – Lima, Pasco Junín
+
5 – Ica, Ayacucho, Apurímac, Huancavelica
+
6 – Arequipa, Moquegua, Tacna
+
7 – Cuzco, Puno, Madre de Dios
+
8 – Loreto, Ucayali
+
9 – Amazonas, San Martín

NOTE: The prefix 4T is assigned on a temporary basis.

=== Philippines (Republic of the)

Amateur stations:: DU {blank}footnote:[Class A radio amateurs have the option to change the prefix DU by 4D, 4E or 4F.] followed by a digit (1-9, indicating the district in which the station is situated) and by a group of not more than 3 letters – Class A, B or C
+
DY followed by a digit (1-9, indicating the district in which the station is situated) and by a group of not more than 3 letters – Class D
+
DX or DZ followed by a digit (1-9, indicating the district in which the station is situated) and by a group of not more than 3 letters – Club stations

=== Poland (Republic of)

Amateur stations:: HF, SN, SO, SP, SQ or 3Z followed by a digit (1-9, indicating the province in which the station is situated) and by a group of not more than four characters, the last of which shall be a letter.
+
SO followed by a digit (1-9, indicating the province in which the station is situated) and by a group of not more than four characters, the last of which shall be a letter - for foreign radio amateurs visiting Poland.
+
SR followed by a digit (1-9, indicating the province in which the station is situated) and by a group of not more than four characters, the last of which shall be a letter - for unattented (automatic) amateur stations (repeaters, beacons, digital stations).
+
HF, SN, SO, SP, SQ or 3Z followed by a digit (1-9, indicating the province in which the station is situated or 0) and by a group of characters (as requested) - for special event stations or operating during amateur contests and competitions (up to one year).

Digits indicating the provinces:: 1 – Province of Zachodniopomorskie
+
2 – Provinces of Pomorskie and Kujawsko-Pomorskie
+
3 – Provinces of Wielkopolskie and Lubuskie
+
4 – Provinces of Warminsko-Mazurskie and Podlaskie
+
5 – Province of Mazowieckie
+
6 – Provinces of Dolnoslaskie and Opolskie
+
7 – Provinces of Lodzkie and Swietokrzyskie
+
8 – Provinces of Lubelskie and Podkarpackie
+
9 – Provinces of Slaskie and Malopolskie

=== Portugal

[%unnumbered]
|===
5+^.^| Amateur stations
^.^| Prefix ^.^| Suffix ^.^| Class ^.^| Geographical area ^.^| Note
^.^| 1 ^.^| 2 ^.^| 3 ^.^| 4 ^.^| 5
^.^| CQ0 ^.^| 2 to 4 characters ^.^| – ^.^| Portugal ^.^| {blank}footnote:portugal2[Call signs assigned to amateur stations of amateur associations (repeaters).]
^.^| CQ1 ^.^| 2 to 4 characters ^.^| – ^.^| Azores ^.^| {blank}footnote:portugal2[]
^.^| CQ2 ^.^| 2 to 4 characters ^.^| – ^.^| Madeira ^.^| {blank}footnote:portugal2[]
^.^| CR0 ^.^| 1 to 4 characters ^.^| – ^.^| Portugal, Madeira, Azores ^.^| {blank}footnote:portugal1[Call signs assigned to amateur stations of public protection and relief organizations.]
^.^| CR7 ^.^| 3 letters ^.^| 3 ^.^| Portugal ^.^| –
^.^| CR8 ^.^| 3 letters ^.^| 3 ^.^| Azores ^.^| –
^.^| CR9 ^.^| 3 letters ^.^| 3 ^.^| Madeira ^.^| –
^.^| CS0 ^.^| 3 letters ^.^| – ^.^| Portugal ^.^| {blank}footnote:portugal3[Call signs assigned to amateur stations of amateur associations (non-repeaters).]
^.^| CS1 ^.^| 3 letters ^.^| – ^.^| Portugal ^.^| {blank}footnote:portugal3[]
^.^| CS3 ^.^| 1 to 4 characters ^.^| – ^.^| Madeira ^.^| {blank}footnote:portugal3[]
^.^| CS4 ^.^| 1 to 4 characters ^.^| – ^.^| Azores ^.^| {blank}footnote:portugal3[]
^.^| CS5 ^.^| 1 to 4 characters ^.^| – ^.^| Portugal ^.^| {blank}footnote:portugal3[]
^.^| CS6 ^.^| 3 letters ^.^| – ^.^| Portugal ^.^| {blank}footnote:portugal3[]
^.^| CS7 ^.^| 3 letters ^.^| 2 ^.^| Portugal ^.^| –
^.^| CS8 ^.^| 3 letters ^.^| 2 ^.^| Azores ^.^| –
^.^| CS9 ^.^| 3 letters ^.^| 2 ^.^| Madeira ^.^| –
^.^| CT1 ^.^| 2 or 3 letters ^.^| A and B ^.^| Portugal ^.^| {blank}footnote:portugal3[]
^.^| CT2 ^.^| 2 or 3 letters ^.^| B ^.^| Portugal ^.^| –
^.^| CT3 ^.^| 2 or 3 letters ^.^| A, B and C ^.^| Madeira ^.^| –
^.^| CT4 ^.^| 2 or 3 letters ^.^| A and B ^.^| Portugal ^.^| –
^.^| CT5 ^.^| 3 letters ^.^| C ^.^| Portugal ^.^| –
^.^| CT6 ^.^| 3 letters ^.^| – ^.^| Portugal ^.^| {blank}footnote:portugal3[]
^.^| CT7 ^.^| 3 letters ^.^| 1 ^.^| Portugal ^.^| –
^.^| CT8 ^.^| 3 letters ^.^| 1 ^.^| Azores ^.^| –
^.^| CT9 ^.^| 3 letters ^.^| 1 ^.^| Madeira ^.^| –
^.^| CU0 ^.^| 3 letters ^.^| C ^.^| Azores (all islands) ^.^| –
^.^| CU1 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (Santa Maria) ^.^| {blank}footnote:portugal3[]
^.^| CU2 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (São Miguel) ^.^| {blank}footnote:portugal3[]
^.^| CU3 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (Terceira) ^.^| {blank}footnote:portugal3[]
^.^| CU4 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (Graciosa) ^.^| {blank}footnote:portugal3[]
^.^| CU5 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (São Jorge) ^.^| {blank}footnote:portugal3[]
^.^| CU6 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (Pico) ^.^| {blank}footnote:portugal3[]
^.^| CU7 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (Faial) ^.^| {blank}footnote:portugal3[]
^.^| CU8 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (Flores) ^.^| {blank}footnote:portugal3[]
^.^| CU9 ^.^| 2 or 3 letters ^.^| A and B ^.^| Azores (Corvo) ^.^| –

|===


[NOTE]
====
For occasional call signs (contests for example) and experimental stations, the following prefixes will be used:

* Portugal: CQ7, CR5, CR6 and CS2;

* Azores: CQ8, CR1 and CR2;

* Madeira: CQ3, CQ9 and CR3.
====

=== Qatar (State of)

Amateur stations:: A71AA-A71ZZ

Experimental stations:: A73AA-A73ZZ


=== Romania

Amateur stations::
. individual
+
YO followed by a digit and a group of not more than 3 letters (the first of which is not letter K)
+
. club
+
YO followed by a digit and a group of not more than 3 letters (the first of which is letter K)


NOTE: YP, YQ and YR followed by a digit and a group of not more than 3 letters are assigned to amateur stations operating during contests or special events.

=== Russian Federation

[%unnumbered]
|===
2+^.^| Amateur and experimental stations
a| RA0AA – RZ9ZZ +
UA0AA - UI9ZZ +
R0AA – R9ZZ {blank}footnote:[Subject to use of the amateur station for a period of not less than 25 calendar years.]

RA0A – RZ9Z {blank}footnote:[Subject to participation over the past five years in no fewer than ten international or all Russian wireless communication contests.]

UA0A – UI9Z
| Stations in the first qualification category operating with a HAREC certificate
| R0AAA – R9ZZZ +
RA0AAA - RZ9ZZZ +
UA0AAA – UA9ZZZ
| Stations in the second qualification category operating with a HAREC certificate
| UB0AAA – UD9ZZZ +
UF0AAA – UG9ZZZ
| Stations in the third qualification category operating with an ARNEC certificate (novice licence)
| UE0AAA – UE9ZZZ +
UH0AAA – UI9ZZZ
| Stations in the fourth qualification category (initial level)
| RR0AA – RR9ZZ +
RR0AAA – RR9ZZZ
| Repeaters
| RB0AA – RB9ZZ
| Radiobeacons
| RS0S – RS9S +
RS10S – RS99S
| Stations of the amateur-satellite service
| R0AAAA – R9ZZZZ +
R00AAA – R99ZZZ +
R000A – R999Z +
R000AA – R999ZZ +
R0000A – R9999Z +
RA00A – RZ99Z +
RA00AA – RZ99ZZ +
RA00AAA – RZ99ZZZ +
RA000A – RZ999Z +
RA000AA – RZ999ZZ
| Temporary use in special circumstances
| R0A – R9Z +
R00A – R99Z +
R00AA – R99ZZ {blank}footnote:[With the exclusion of call signs in the series +
R00SP - R99SP exclusively assigned to amateur stations of polar expeditions operating on the drift-ice of the Arctic Ocean.] | Stations participating in internal rounds of competitions

|===


=== Rwanda (Republic of)

Amateur stations:: 9X5AA-9X5ZZ

=== Samoa (Independent State of)

Amateur stations:: 5W followed by a digit and 2 letters

=== San Marino (Republic of)

Amateur stations:: T72AA-T72ZZ {blank}footnote:[VHF and above VHF.]
+
T77AA-T77ZZ {blank}footnote:sanMarino[All bands.]
+
Radio Club: T70A {blank}footnote:sanMarino[]
+
Temporary Radio Club: T71CE {blank}footnote:sanMarino[]


=== Sao Tome and Principe (Democratic Republic of)

Amateur stations:: S92AA-S92ZZ

=== Saudi Arabia (Kingdom of)

Amateur stations and experimental stations:: 7Z followed by a digit and 2 letters

=== Senegal (Republic of)

Amateur stations:: 6W1AA-6W1ZZ

Experimental stations:: 6V3AA-6V3ZZ

=== Seychelles (Republic of)

Amateur stations:: S79AAA-S79ZZZ

Experimental stations:: S78AA-S78AZ

=== Sierra Leone

Amateur stations:: 9L followed by a digit (0-8, indicating the area or the province in which the station is situated) and by 2 letters

Digits indicating the areas or provinces:: 0 – Small craft and off-shore islands
+
1 – Western area
+
2 – Northern province
+
3 – Southern province
+
4 – Eastern province
+
7 – Novice licence
+
8 – Class B licence (VHF/UHF)

NOTE: Foreign radio amateurs with temporary licence must use 9L followed by a stroke (/) and their own call sign.

=== Singapore (Republic of)

Amateur stations:: 9V1AA-9V1ZZ

Experimental stations:: 9V2A-9V2ZZ

NOTE: 9V0 followed by 2 or 3 letters is authorised to amateur stations on special occasions.

=== Sint Maarten (Dutch part)

Amateur stations:: PJ7AA-PJ7ZZZ

=== Slovak Republic

Amateur stations:: OM0AA-OM8ZZZ
+
OM0A-OM9Z {blank}footnote:[For international amateur contests.]
+
OM9AA-OM9ZZ {blank}footnote:[For extraordinary purposes and for period of persistence of such purposes only.]
+
OM9AAA-OM9SZZ {blank}footnote:[For foreigners transmitting from the Slovak Republic territory.]

Experimental stations:: OM9TAA-OM9ZZZ

=== Slovenia (Republic of)

Amateur stations:: S5 followed by a digit and by 1, 2 or 3 letters

=== Solomon Islands

Amateur stations and experimental stations:: H44AA-H44ZZ


=== South Africa (Republic of)

Amateur stations:: ZR {blank}footnote:[Full licence except VHF.], ZS {blank}footnote:[Full licence.] or ZU {blank}footnote:[Novice licence.] followed by a digit (indicating the province in which the station is situated) and by 1, 2 or 3 letters characterizing the radio amateur

Digits indicating the provinces:: 1 – Western Cape
+
2 – Eastern Cape
+
3 – Northern Cape
+
4 – Free State
+
5 – Kwazulu-Natal
+
6 – Gauteng, North-West Province, Mpumalanga, Northern Province
+
7 – Sanae Antarctica
+
8 – Marion Island
+
9 – Namibia
+
0 – DIG repeaters and bulletins boards

Experimental stations:: ZT followed by a digit and 1, 2 or 3 letters

=== Spain

Amateur stations:: One of the groups EA, EB or EC followed by a digit (indicating the province in which a fixed station is located or in which the licensee of a mobile station resides) and by a group of not more than 3 letters.
+
The second letter of groups EA, EB and EC indicates that the stations are of class A, B or C, respectively.

Temporary call signs:: Groups ED, EE and EF are used instead of EA, EB and EC; the second letter D, E or F means the same as the letters A, B and C (class of licence).

=== Sri Lanka (Democratic Socialist Republic of)

Amateur stations:: 4S5 followed by 2 or 3 letters  –  Novice class B (VHF only)
+
4S6 followed by 2 or 3 letters  –  Novice class A
+
4S7 followed by 2 or 3 letters  –  General/Advanced class

Experimental stations:: 4P3 followed by 2 letters


[NOTE]
====
i) Local radio amateurs who have received licence by submitting licences issued from foreign administrations will use 4S7 followed by 3 letters with last letter as R.

ii) Visiting radio amateurs will use 4S7 followed by home call sign.

iii) Foreign radio amateurs from administrations having reciprocal agreement will use 4S7 followed by 3 letters with last letter as G.
====


=== Suriname (Republic of)

Amateur stations and experimental stations:: PZ followed by a digit (2-9) and by a group of not more than 3 letters

=== Swaziland (Kingdom of)

Amateur stations:: 3DA0 followed by 2 letters  –  Full licence
+
3DA1 followed by 2 letters  –  Restricted licence

=== Sweden

Amateur stations:: SA, SI, SJ, SK, SL or SM (exceptionally 7S or 8S) followed by a digit and by 1, 2 or 3 letters
+
SH followed by a digit and by 3 letters


=== Switzerland (Confederation of)

Amateur stations:: HB9 or HB3 {blank}footnote:[Novice licence.] followed by 4 characters, the last of which shall be a letter


=== Syrian Arab Republic

Amateur stations and experimental stations:: YK followed by a digit (indicating the zone in which the station is situated) and by1, 2 or 3 letters

Digits indicating the zones:: 1 – Southern Region
+
2 – Northern Region
+
3 – Eastern Region
+
4 – Western Region
+
8 – Beacons
+
9 – Groups of foreign radio amateurs
+
0 – Club stations

[NOTE]
====
i) Foreign individual radio amateurs will use YK followed by a stroke (/) and their home call sign.

ii) Only for special events the radio amateurs will use 6C followed by a digit and by a group of not more than 3 letters.
====

=== Tanzania (United Republic of)

Amateur stations:: 5H3AA-5H3ZZ  –  Mainland
+
5H1AA-5H1ZZ  –  Zanzibar

=== Thailand

Amateur stations:: E2 or HS followed by a digit (indicating the area in which the station is situated) andby 2 or 3 letters

Digits indicating the areas:: 0, 1 – Bangkok, Samut Prakan, Pathum Thani, Nonthaburi, Phra Nakhon Si Ayutthaya, Angthong, Saraburi, Lop Buri, Sing Buri, Chainat
+
2 – Chon Buri, Rayong, Chanthaburi, Trat, Chachoengsao, Nakhon Nayok, Prachin Buri, Srakaew
+
3 – Nakhon Ratchasima, Chaiyaphum, Buriram, Surin, Sisaket, Ubon Ratchathani, Yasothon, Amnat Chareon
+
4 – Khon Kaen, Loei, Nong Khai, Udon Thani, Maha Sarakham, Kalasin, Sakon Nakhon, Mukdahan, Nakhon Phanom, Roi Et, Nong Bua Lum Phu
+
5 – Mae Hong Son, Chiang Mai, Lamphun, Lampang, Phrae, Uttaradit, Nan, Chiang Rai, Phayao
+
6 – Nakhon Sawan, Uthai Thani, Kamphaeng Phet, Tak, Phichit, Sukhothai, Phitsanulok, Phetchabun
+
7 – Ratchaburi, Samut Sokhon, Samut Songkhram, Nakhon Pathom, Suphan Buri, Kanchanaburi, Phetchaburi, Prachuap Khiri Khan
+
8 – Nakhon Si Thammarat, Krabi, Phangnga, Ranong, Surat Thani, Chumphon, Phuket
+
9 – Songkhla, Pattani, Yala, Narathiwat, Trang, Phatthalung, Satun

Experimental stations:: E22AAA-E22AZZ

=== Tonga (Kingdom of)

Amateur stations:: A35followed by 2 letters

Experimental stations:: A35 followed by 3 letters, the first of which shall be the letter X

=== Trinidad and Tobago

Amateur stations and experimental stations:: 9Y4AA-9Y4ZZ

=== Tunisia

Amateur stations:: 3V8AA-3V8ZZ

Experimental stations:: TS8AA-TS8ZZ

=== Turkey

Amateur stations:: TA followed by a digit and a group of not more than 3 letters

=== Tuvalu

Amateur stations:: T20AA-T29ZZ

Experimental stations:: T22AA-T29ZZ

=== Uganda (Republic of)

Amateur stations:: 5X5AA-5X5ZZ

=== Ukraine

Amateur stations and experimental stations:: UR, US, UT, UU, UV, UW, UX, UY, UZ, EM, EN or EO followed by a digit (0-9) and by 2 or 3 letters

=== United Arab Emirates

Amateur stations:: A61 followed by a group of not more than 3 letters

Experimental stations:: A62 followed by a group of not more than 3 letters

=== United Kingdom of Great Britain and Northern Ireland

[%unnumbered]
|===
2+^.^| Amateur and experimental stations
^.^| _Type of licence_ ^.^| _Form of call signs_
.2+| Full/advanced/Club {blank}footnote:uk1[Where the licensee's main station address or a special contest station address is in the location listed below and operation is from that address, the call sign is amended by the insertion of a letter after the first character of the call signs indicated in the table above in accordance with the list as detailed below:

None – England

U – Guernsey

D – Isle of Man

J – Jersey

I – Northern Ireland

M – Scotland

W – Wales] {blank}footnote:uk2[Where a club call sign is issued in the locations listed below, the call sign is amended by the insertion of a letter after the first character of the call signs indicated in the table above, in accordance with the list as detailed below:

X – England

P – Guernsey

T – Isle of Man

H – Jersey

N – Northern Ireland

S – Scotland

C – Wales.]
| G followed by a digit (0-8) and by 2 or 3 letters
| M followed by a digit (0, 1, 5) and by 3 letters
| Intermediate {blank}footnote:uk3[Where the licensee's main station address is in the location listed under note 1) and operation is from that address, the call sign is amended by the substitution of the second character of the call signs indicated in the table above in accordance with the list as detailed under note 1), with the provision that there is no substitution in the case of location in England.]
| 2E followed by a digit (0, 1) and by 3 letters
| Foundation {blank}footnote:uk1[] | M3 followed by 3 letters
| Repeater stations | GB3 followed by 2 letters
| Beacon stations | GB3 followed by 3 letters
| Data packet node stations | GB7 followed by 2 letters
| Data packet mailbox stations | GB7 followed by 3 letters
| Automatic position reporting system gateway stations | MB7U followed by 2 letters
| Simplex internet gateway (unattended) stations | MB7I followed by 2 letters
| Special event stations (temporary) | GB followed by a digit (0-2, 4-6, 8) and by 2 or 3 letters
| Special – Special event stations (temporary) | GB followed by 2 or 3 digits (0-9) and by 2 or 3 letters
| Special contest stations (temporary) a| G followed by a digit (0-9) and by a letter M followed by a digit (0-9) and by a letter
^.^| _Overseas territories_ ^.^| _Form of call signs_
| Anguilla | VP2E followed by 2 letters
| Montserrat | VP2M followed by 2 letters
| British Virgin Islands | VP2V followed by 2 letters
| Turks and Caicos Islands | VP5 followed by 3 letters
| Pitcairn Island and dependencies (Henderson, Ducie   and Oeno Islands) | VP6 followed by 3 letters
a| Falkland Islands (Malvinas) and dependencies (South Georgia, South Sandwich Islands) Antarctic Territories
a| VP8 followed by 3 letters  –  full licence VP8 followed by 4 letters  –  special licence (144-146 MHz   domestic use only, no examination)
| Bermuda | VP9 followed by 3 letters
| Turks and Caicos Islands | VQ5 followed by 3 letters
| Cayman Islands | VQ6 followed by 3 letters
| British Indian Ocean Territory (BIOT) (Diego Garcia   and Chagos Archipelago) | VQ9 followed by 3 letters
| Gibraltar | ZB0, ZB2 or ZB3 followed by 3 letters
| UK Sovereign Bases, Cyprus (Akrotiri and Dhekelia) | ZC4 followed by 3 letters
| Saint Helena | ZD7 followed by 1 to 3 letters
| Ascension Island | ZD8 followed by 1 to 3 letters
| Tristan da Cunha and Gough Island | ZD9 followed by 1 to 3 letters
| Cayman Islands – Grand Cayman | ZF1 or ZF2 followed by 3 letters
| Cayman Islands – Little Cayman | ZF8 followed by 3 letters
| Cayman Islands – Cayman Brac | ZF9 followed by 3 letters

|===


=== United States of America

[%unnumbered]
|===
2+^.^| Amateur stations
a| K0A-K9Z +
N0A-N9Z +
W0A-W9Z
| Except the letter X after the digit
a| K0AA-K9ZZZ +
N0AA-N9ZZZ +
W0AA-W9ZZZ
.2+a|
a| AA0A-AL9ZZ +
KA0A-KZ9ZZ +
NA0A-NZ9ZZ +
WA0A-WZ9ZZ
a| KA0AAA-KZ9ZZZ +
WA0AAA-WZ9ZZZ
| Except the letter X after the digit
2+^.^| Experimental stations
a| AA2XAA-AE9XZZ +
AL2XAA-AL9XZZ +
KA2XAA-KZ9XZZ +
WA2XAA-WZ9XZZ
a|

|===

=== Uruguay (Eastern Republic of)

Amateur stations:: CX followed by a digit (1-9) and a group of not more than 3 letters, the first indicating the department in which the station is situated

Experimental stations:: CV, CW or CX followed by a digit (1-9) and a group of not more than 3 letters

=== Vanuatu (Republic of)

Amateur stations:: YJ8 followed by 2 letters (usually the initials of the licensed radio amateur)
+
YJ8N {blank}footnote:[For amateur stations operated by beginners.] followed by 2 letters
+
YJ8V {blank}footnote:[For restricted licensees' amateur stations (VHF).] followed by 2 letters


=== Vatican City State

Amateur stations:: HV followed by a digit and 2 letters

=== Venezuela (Bolivarian Republic of)

Amateur stations:: YV, YX or 4M followed by a digit and 3 letters

=== Viet Nam (Socialist Republic of)

Amateur stations:: XV or 3W followed by a digit (2-9, indicating the area in which the station is located) and by 1 to 4 letters

=== Zambia (Republic of)

Amateur stations:: 9J2 followed by 2 characters, the last of which shall be a letter

=== Zimbabwe (Republic of)

Amateur stations:: Z21AA-Z29ZZ

<<<

== AMENDMENTS

[%unnumbered]
|===
^.^h| Amendment No. ^.^h| Operational Bulletin No. ^.^h| Administration
^.^| 1 | |
^.^| 2 | |
^.^| 3 | |
^.^| 4 | |
^.^| 5 | |
^.^| 6 | |
^.^| 7 | |
^.^| 8 | |
^.^| 9 | |
^.^| 10 | |
^.^| 11 | |
^.^| 12 | |
^.^| 13 | |
^.^| 14 | |
^.^| 15 | |
^.^| 16 | |
^.^| 17 | |
^.^| 18 | |
^.^| 19 | |
^.^| 20 | |
^.^| 21 | |
^.^| 22 | |
^.^| 23 | |
^.^| 24 | |
^.^| 25 | |
^.^| 26 | |
^.^| 27 | |
^.^| 28 | |
^.^| 29 | |
^.^| 30 | |

|===

